### ISSUE TITLE
Create an example project and an integration for Micronaut

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#1088]
Would be cool if Blaze-Persistence could be used in a Micronaut application. Maybe it's already possible, but we should create a sample project and if we need something special, we should write an integration.

**Comment by jwgmeligmeyling** [comment]
@sranjha Perhaps something for you 😄

**Comment by sranjha** [comment]
Perhaps 😄

**Comment by soberich** [comment]
So far it works, but I haven't tried the main feature of interest - Entity Views.
It produces
```console
13:51:45.363 [main] DEBUG o.h.p.entity.AbstractEntityPersister - Static SQL for entity: com.blazebit.persistence.impl.function.entity.ValuesEntity
13:51:45.364 [main] DEBUG o.h.p.entity.AbstractEntityPersister -  Version select: /* get version com.blazebit.persistence.impl.function.entity.ValuesEntity */ select value from ( select * from ValuesEntity ) where value =?
13:51:45.364 [main] DEBUG o.h.p.entity.AbstractEntityPersister -  Snapshot select: /* get current state com.blazebit.persistence.impl.function.entity.ValuesEntity */ select valuesenti_.value from ( select * from ValuesEntity ) valuesenti_ where valuesenti_.value=?
13:51:45.364 [main] DEBUG o.h.p.entity.AbstractEntityPersister -  Insert 0: /* insert com.blazebit.persistence.impl.function.entity.ValuesEntity */ insert into ( select * from ValuesEntity ) (value) values (?)
13:51:45.364 [main] DEBUG o.h.p.entity.AbstractEntityPersister -  Update 0: null
13:51:45.364 [main] DEBUG o.h.p.entity.AbstractEntityPersister -  Delete 0: /* delete com.blazebit.persistence.impl.function.entity.ValuesEntity */ delete from ( select * from ValuesEntity ) where value=?
13:51:45.400 [main] DEBUG o.h.l.p.b.spi.LoadPlanTreePrinter - LoadPlan(entity=com.blazebit.persistence.impl.function.entity.ValuesEntity)
    - Returns
       - EntityReturnImpl(entity=com.blazebit.persistence.impl.function.entity.ValuesEntity, querySpaceUid=<gen:0>, path=com.blazebit.persistence.impl.function.entity.ValuesEntity)
    - QuerySpaces
       - EntityQuerySpaceImpl(uid=<gen:0>, entity=com.blazebit.persistence.impl.function.entity.ValuesEntity)
          - SQL table alias mapping - valuesenti0_
          - alias suffix - 0_
          - suffixed key columns - {value1_4_0_}

13:51:45.403 [main] DEBUG o.h.l.p.b.spi.LoadPlanTreePrinter - LoadPlan(entity=com.blazebit.persistence.impl.function.entity.ValuesEntity)
    - Returns
       - EntityReturnImpl(entity=com.blazebit.persistence.impl.function.entity.ValuesEntity, querySpaceUid=<gen:0>, path=com.blazebit.persistence.impl.function.entity.ValuesEntity)
    - QuerySpaces
       - EntityQuerySpaceImpl(uid=<gen:0>, entity=com.blazebit.persistence.impl.function.entity.ValuesEntity)
          - SQL table alias mapping - valuesenti0_
          - alias suffix - 0_
          - suffixed key columns - {value1_4_0_}
```

So integration works with stack Micronaut with Spring annotations running on KTOR, Gradle 6.7-SNAP, Java 14, Kotlin 1.3-1.4.

Next I'll be adding entity views and make it more "examplish" more simple.

**Comment by soberich** [comment]
I am getting this
```
21:54:37.847 [main] INFO  o.h.e.t.j.p.i.JtaPlatformInitiator - HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
Aug 29, 2020 9:54:38 PM com.blazebit.persistence.impl.CriteriaBuilderConfigurationProviderImpl createConfiguration
INFO: Blaze-Persistence version: Blaze-Persistence 'Zemo' 1.5.0-SNAPSHOT
21:54:38.231 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Error instantiating bean of type  [com.example.marvel.domain.employee.$EmployeeBlockingServiceNamespaceImplDefinition$Intercepted]e-service.runner:runShadow

Message: com/blazebit/persistence/spi/JpqlFunctionKind
Path Taken: new KtorNettyEmbeddedServer(ApplicationContext ctx,HttpServerConfiguration serverConfiguration,[ApplicationEngineEnvironment engineEnvironment],KtorApplication ktorApplication) --> ApplicationEngineEnvironment.applicationEngineEnvironment([ApplicationEngineEnvironmentBuilder builder],Environment env,HttpServerConfiguration serverConfiguration) --> ApplicationEngineEnvironmentBuilder.applicationEngineEnvironmentBuilder(KtorApplication ktorApplication,List ktorApplicationBuilders,[List ktorRoutingBuilders]) --> new Router([EmployeeResourceAdapter employees],ProjectResourceAdapter projects,Validator validator) --> new EmployeeOrchestrationResource([EmployeeOperationsServiceNamespace employees]) --> $EmployeeBlockingServiceNamespaceImplDefinition$Intercepted.cbf
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [com.example.marvel.domain.employee.$EmployeeBlockingServiceNamespaceImplDefinition$Intercepted]

Message: com/blazebit/persistence/spi/JpqlFunctionKind
Path Taken: new KtorNettyEmbeddedServer(ApplicationContext ctx,HttpServerConfiguration serverConfiguration,[ApplicationEngineEnvironment engineEnvironment],KtorApplication ktorApplication) --> ApplicationEngineEnvironment.applicationEngineEnvironment([ApplicationEngineEnvironmentBuilder builder],Environment env,HttpServerConfiguration serverConfiguration) --> ApplicationEngineEnvironmentBuilder.applicationEngineEnvironmentBuilder(KtorApplication ktorApplication,List ktorApplicationBuilders,[List ktorRoutingBuilders]) --> new Router([EmployeeResourceAdapter employees],ProjectResourceAdapter projects,Validator validator) --> new EmployeeOrchestrationResource([EmployeeOperationsServiceNamespace employees]) --> $EmployeeBlockingServiceNamespaceImplDefinition$Intercepted.cbf
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1916)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2635)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2621)
        at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2296)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2270)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1240)
        at io.micronaut.context.AbstractBeanDefinition.getBeanForField(AbstractBeanDefinition.java:1441)
        at io.micronaut.context.AbstractBeanDefinition.getBeanForField(AbstractBeanDefinition.java:1203)
        at com.example.marvel.domain.employee.$EmployeeBlockingServiceNamespaceImplDefinition.injectBean(Unknown Source)
        at com.example.marvel.domain.employee.$$EmployeeBlockingServiceNamespaceImplDefinition$InterceptedDefinition.injectBean(Unknown Source)
        at com.example.marvel.domain.employee.$$EmployeeBlockingServiceNamespaceImplDefinition$InterceptedDefinition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1889)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2635)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2621)
        at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2296)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2270)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1240)
        at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1013)
        at com.example.marvel.domain.employee.$EmployeeOrchestrationResourceDefinition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1889)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2635)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2621)
        at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2296)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2270)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1240)
        at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1013)
        at com.example.marvel.runtime.$RouterDefinition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1889)
        at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:2961)
        at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2872)
        at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:1040)
        at io.micronaut.context.AbstractBeanDefinition.lambda$getBeansOfTypeForConstructorArgument$9(AbstractBeanDefinition.java:1143)
        at io.micronaut.context.AbstractBeanDefinition.resolveBeanWithGenericsFromConstructorArgument(AbstractBeanDefinition.java:1820)
        at io.micronaut.context.AbstractBeanDefinition.getBeansOfTypeForConstructorArgument(AbstractBeanDefinition.java:1138)
        at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:990)
        at io.micronaut.ktor.factory.$KtorMicronautApplicationFactory$ApplicationEngineEnvironmentBuilder0Definition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1889)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2635)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2621)
        at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2296)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2270)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1240)
        at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1013)
        at io.micronaut.ktor.factory.$KtorMicronautApplicationFactory$ApplicationEngineEnvironment1Definition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1889)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2635)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2621)
        at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2296)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2270)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1240)
        at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1013)
        at io.micronaut.ktor.server.$KtorNettyEmbeddedServerDefinition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1889)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2635)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2621)
        at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2296)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2270)
        at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:1261)
        at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:739)
        at io.micronaut.context.BeanLocator.findBean(BeanLocator.java:149)
        at io.micronaut.runtime.Micronaut.start(Micronaut.java:66)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:294)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:269)
        at io.micronaut.ktor.KtorApplicationKt.runApplication(KtorApplication.kt:51)
        at com.example.marvel.runtime.ApplicationKt.main(Application.kt:50)
Caused by: java.lang.NoClassDefFoundError: com/blazebit/persistence/spi/JpqlFunctionKind
        at com.blazebit.persistence.impl.CriteriaBuilderConfigurationImpl.loadFunctions(CriteriaBuilderConfigurationImpl.java:735)
        at com.blazebit.persistence.impl.CriteriaBuilderConfigurationImpl.<init>(CriteriaBuilderConfigurationImpl.java:538)
        at com.blazebit.persistence.impl.CriteriaBuilderConfigurationProviderImpl.createConfiguration(CriteriaBuilderConfigurationProviderImpl.java:47)
        at com.blazebit.persistence.Criteria.getDefault(Criteria.java:59)
        at com.example.marvel.runtime.BlazePersistenceConfiguration.createCriteriaBuilderFactory(BlazePersistenceConfiguration.kt:30)
        at com.example.marvel.runtime.$BlazePersistenceConfiguration$CreateCriteriaBuilderFactory0Definition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1889)
        ... 64 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.blazebit.persistence.spi.JpqlFunctionKind
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 71 common frames omitted

```

Thought it's some JPMS (mr jar actually) related issue, but after removing `-release` nothing changed. 
If I remove the injection at `com.example.marvel.domain.employee.$EmployeeBlockingServiceNamespaceImplDefinition$Intercepted` 
it works, but probably because because injection does not occur, hence `Criteria.getDefault` is not called.

**Comment by soberich** [comment]
@beikov I got it working, I think Blaze Persistence is really a cherry on a pie. It's a great library.
There is a bug. If entity class extends generic mappedsuperclass type
```kotlin
class RecordEntity : AbstractAuditingEntity<RecordEntity.RecordId>() 
```
i'll fails at https://github.com/Blazebit/blaze-persistence/blob/c8c1525d1b947674647c328725373d8ff01fae5e/entity-view/processor/src/main/java/com/blazebit/persistence/view/processor/ImplementationClassWriter.java#L1344

with NPE
```java
context.getElementUtils().getTypeElement(entityElement.getSuperclass().toString()); // returns null!!
```
returns `null`.

A workaround I did is to just to "mask" it.

**Comment by beikov** [comment]
Thanks for the report @soberich, I will look into this issue. Are you saying that there is no need for a micronaut integration because everything just works when using the annotation processor?

**Comment by beikov** [comment]
The PR https://github.com/Blazebit/blaze-persistence/pull/1149 will come with a fix for the issue that you found @soberich

**Comment by soberich** [comment]
> The PR #1149 will come with a fix for the issue that you found @soberich

Thanks for letting me know.

> Thanks for the report @soberich, I will look into this issue. Are you saying that there is no need for a micronaut integration because everything just works when using the annotation processor?

So far, yes. I will continue trying more edge cases. Hence, it's not valid to say "everything" untill I'll finally write tests.  I might  be slow to report, I am trying to marry a lot of technologies in that playground, so there are some side effects when I introduce something new.
Annotation processor is a great solution, I think. I remember we talked ByteBuddy vs. Javassist, I am am happy with annotation processor much more. I'll report whatever I find.
