### ISSUE TITLE
EntityViewId annotation has no effect in Quarkus resource

### ISSUE THREAD

**Issue by kekbur** [Blazebit/blaze-persistence#1129]
### Description
The [Quarkus guide on using blaze-persistence](https://quarkus.io/guides/blaze-persistence) and [blaze-persistence-examples-quarkus sample project](https://github.com/Blazebit/blaze-persistence/blob/master/examples/quarkus/base/src/main/java/com/blazebit/persistence/examples/quarkus/base/resource/PersonResource.java) indicate that the annotation `com.blazebit.persistence.integration.jaxrs.EntityViewId` can be used to bind a path parameter to an entity view id. However, the annotation does not seem to have any effect.

Additionally, it is not clear whether a project needs to declare `org.glassfish.jersey.core:jersey-common` as a dependency to use this annotation. If the dependency is not declared, Quarkus gives the following warning:

```
2020-07-11 00:39:36,389 WARN  [io.qua.arc.pro.BeanArchives] (build-20) Failed to index org.glassfish.jersey.model.Parameter: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader
2020-07-11 00:39:36,389 INFO  [io.qua.arc.pro.IndexClassLookupUtils] (build-20) Class for name: org.glassfish.jersey.model.Parameter was not found in Jandex index. Please ensure the class is part of the index.
```

I noticed that `blaze-persistence-integration-jaxrs`, which contains `EntityViewId.class`, declares `jersey-common` as an optional dependency.

The annotation behaves the same regardless.

### Expected behavior
Entity view id is set to the value supplied in a path parameter.

### Actual behavior
Entity view id is null.

### Steps to reproduce
1. `git clone https://github.com/kekbur/blaze-persistence-quarkus-test.git && cd blaze-persistence-quarkus-test`
2. `./mvnw quarkus:dev`
3. `curl -H "Content-Type: application/json" -d '{"name":"Test"}' -X PUT "http://localhost:8080/persons/2c426b89-c102-45ad-8527-07cbbeb0a243"`

The PUT request above results in a `HTTP 400 - Bad Request` response, because [personUpdateView.getId() returns null](https://github.com/kekbur/blaze-persistence-quarkus-test/blob/06bf073e6c4bcd0d1b1606a3e566784bedd2b5a0/src/main/java/com/github/kekbur/blazepersistencequarkustest/resource/PersonResource.java#L52).

### Environment
Version:            1.5.0-Alpha5
JPA-Provider:       Hibernate 5.4.16.Final
DBMS:               H2
Application Framework: Quarkus 1.5.0.Final

**Comment by beikov** [comment]
The issue here seems to be that Resteasy does not seem to provide a `ParamConverterProvider` for `UUID`. I'll have to investigate and do some further tests to see how this can be resolved more properly, but for now you could try to add something like the following class which I would have expected Resteasy provides just like Jersey.

```
@ApplicationScoped
public class MyParamConverterProvider implements ParamConverterProvider {
  @Override
  public <T> ParamConverter<T> getConverter(Class<T> clazz, Type type, Annotation[] annotations) {
    Method m = clazz.getMethod("fromString", String.class);
    if (m == null) {
      return null;
    }
    return new MyParamConverter<>(m);
  }

  private static class MyParamConverter<T> implements ParamConverter<T> {
    private final Method m;
    public MyParamConverter(Method m) {
      this.m = m;
    }

    @Override
    public T fromString(String s) {
      return m.invoke(null, s);
    }

    @Override
    public String toString(T o) {
      return o.toString();
    }
  }
}

```

**Comment by beikov** [comment]
Seems like we will have to implement such a fallback strategy manually as this such a provider is Jersey specific and can't be expected by a JAX-RS implementation in general. I guess we can do something similar like `org.glassfish.jersey.internal.inject.ParamConverters.AggregatedProvider` in `com.blazebit.persistence.integration.jaxrs.EntityViewMessageBodyReader#init`

**Comment by kekbur** [comment]
Thank you. This seems to have done the trick:

```java
@ApplicationScoped
public class FromStringParamConverterProvider implements ParamConverterProvider
{
	@Override
	public <T> ParamConverter<T> getConverter(Class<T> clazz, Type type, Annotation[] annotations)
	{
		try
		{
			return new ParamConverter<>(clazz.getMethod("fromString", String.class));
		}
		catch (NoSuchMethodException | SecurityException e)
		{
			return null;
		}
	}
	
	private static class ParamConverter<T> implements javax.ws.rs.ext.ParamConverter<T>
	{
		private final Method fromString;
		
		public ParamConverter(Method fromString)
		{
			this.fromString = fromString;
		}
		
		@Override
		@SuppressWarnings("unchecked")
		public T fromString(String s)
		{
			try
			{
				return (T) fromString.invoke(null, s);
			}
			catch (IllegalAccessException | IllegalArgumentException | InvocationTargetException e)
			{
				throw new BadRequestException("Malformed input: " + s);
			}
		}
		
		@Override
		public String toString(T o)
		{
			return o.toString();
		}
	}
}
```

**Comment by kekbur** [comment]
Uh-oh. Spoke too soon. It doesn't work when running a native image. Id is null just like before.

**Comment by kekbur** [comment]
And this is the cause:

```
java.lang.NoSuchMethodException: java.util.UUID.fromString(java.lang.String)
        at java.lang.Class.getMethod(DynamicHub.java:1036)
        at org.acme.FromStringParamConverterProvider.getConverter(FromStringParamConverterProvider.java:22)
        at org.acme.FromStringParamConverterProvider_ClientProxy.getConverter(FromStringParamConverterProvider_ClientProxy.zig:191)
        at org.acme.FromStringParamConverterProvider.getConverter(FromStringParamConverterProvider.java:12)
        at com.blazebit.persistence.integration.jaxrs.EntityViewMessageBodyReader$1.getValue(EntityViewMessageBodyReader.java:84)
        at com.blazebit.persistence.integration.jackson.EntityViewReferenceDeserializer.retrieveId(EntityViewReferenceDeserializer.java:115)
        at com.blazebit.persistence.integration.jackson.EntityViewReferenceDeserializer.deserialize(EntityViewReferenceDeserializer.java:78)
        at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1719)
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1228)
        at com.blazebit.persistence.integration.jaxrs.EntityViewMessageBodyReader.readFrom(EntityViewMessageBodyReader.java:129)
        at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.readFrom(AbstractReaderInterceptorContext.java:101)
        at org.jboss.resteasy.core.interception.jaxrs.ServerReaderInterceptorContext.readFrom(ServerReaderInterceptorContext.java:63)
        at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:80)
        at org.jboss.resteasy.core.MessageBodyParameterInjector.inject(MessageBodyParameterInjector.java:213)
        at org.jboss.resteasy.core.MethodInjectorImpl.injectArguments(MethodInjectorImpl.java:95)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:128)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:638)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:504)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:454)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:456)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:417)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:391)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:68)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:488)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:259)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:160)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:163)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:245)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:132)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:37)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:94)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
```

Line 22 of FromStringParamConverterProvider.java is `return new ParamConverter<>(clazz.getMethod("fromString", String.class));`

Somehow reflectively accessing UUID.fromString does not work under GraalVM. This is a bit unfamiliar territory to me.

**Comment by beikov** [comment]
Hmm, you are right, we will have to implement some default conversions ourselves for this to work and the rest will be up to the user.
