### ISSUE TITLE
Quarkus Snapshot issue

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#1150]
The current snapshot build(https://github.com/quarkusio/quarkus/issues/9142#event-3708343393) failed. Maybe we need to increase the Xmx value? Here is the relevant output:

```
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] docker run -v /home/runner/work/blaze-persistence/blaze-persistence/current-repo/examples/quarkus/testsuite/native/h2/target/h2-test-app-native-image-source-jar:/project:z --env LANG=C --user 1001:116 --rm quay.io/quarkus/ubi-quarkus-native-image:20.2.0-java11 -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-DCoordinatorEnvironmentBean.transactionStatusManagerEnable=false -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=1 -J-Duser.language=en -J-Dfile.encoding=UTF-8 --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -jar h2-test-app-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -J-Xmx3g -H:-AddAllCharsets -H:EnableURLProtocols=http,https --enable-all-security-services --no-server -H:-UseServiceLoaderFeature -H:+StackTrace h2-test-app-runner
[h2-test-app-runner:25]    classlist:  18,982.01 ms,  1.64 GB
[h2-test-app-runner:25]        (cap):   1,020.00 ms,  1.64 GB
[h2-test-app-runner:25]        setup:   3,352.22 ms,  1.64 GB
05:24:21,072 INFO  [com.bla.per.imp.CriteriaBuilderConfigurationProviderImpl] Blaze-Persistence version: Blaze-Persistence 'Zemo' 1.5.0-SNAPSHOT
05:24:21,137 INFO  [org.hib.Version] HHH000412: Hibernate ORM core version 5.4.19.Final
05:24:21,154 INFO  [org.hib.ann.com.Version] HCANN000001: Hibernate Commons Annotations {5.1.0.Final}
05:24:21,207 INFO  [org.hib.dia.Dialect] HHH000400: Using dialect: io.quarkus.hibernate.orm.runtime.dialect.QuarkusH2Dialect
05:24:21,302 WARN  [io.qua.hib.orm.run.pro.ProxyDefinitions] Unable to find a build time generated proxy for entity com.blazebit.persistence.impl.function.entity.ValuesEntity
05:24:57,309 INFO  [org.jbo.threads] JBoss Threads version 3.1.1.Final
[h2-test-app-runner:25]     (clinit):   1,048.42 ms,  1.82 GB
[h2-test-app-runner:25]   (typeflow):  52,468.23 ms,  1.82 GB
[h2-test-app-runner:25]    (objects):  63,576.33 ms,  1.82 GB
[h2-test-app-runner:25]   (features):   1,772.53 ms,  1.82 GB
[h2-test-app-runner:25]     analysis: 121,766.17 ms,  1.82 GB
[h2-test-app-runner:25]     universe:   4,746.67 ms,  1.91 GB
[h2-test-app-runner:25]      (parse):  28,678.21 ms,  2.64 GB
[h2-test-app-runner:25]     (inline): 638,932.68 ms,  2.67 GB
ANTLR Tool version 4.7.2 used for code generation does not match the current runtime version 4.8ANTLR Runtime version 4.7.2 used for parser compilation does not match the current runtime version 4.8ANTLR Tool version 4.7.2 used for code generation does not match the current runtime version 4.8ANTLR Runtime version 4.7.2 used for parser compilation does not match the current runtime version 4.8Exception in thread "native-image pid watcher" java.lang.OutOfMemoryError: GC overhead limit exceeded
[h2-test-app-runner:25]    (compile): 1,585,897.01 ms,  2.67 GB
[h2-test-app-runner:25]      compile: 2,271,974.93 ms,  2.67 GB
3 fatal errors detected:
Fatal error:org.graalvm.compiler.debug.GraalError: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at method: Connection java.sql.DriverManager.getConnection(String, Properties, Class)  [Direct call from Connection DriverManagerConnectionCreator.makeConnection(String, Properties)]
	at com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:1016)
	at com.oracle.svm.hosted.code.CompileQueue.doCompile(CompileQueue.java:947)
	at com.oracle.svm.hosted.code.CompileQueue$CompileTask.run(CompileQueue.java:263)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
Fatal error:org.graalvm.compiler.debug.GraalError: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at method: void com.blazebit.persistence.integration.hibernate.Hibernate53MetadataContributor.configure(Map)  [Virtual call from void SessionFactoryServiceRegistryImpl.configureService(ServiceBinding), callTarget void Configurable.configure(Map)]
	at com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:1016)
	at com.oracle.svm.hosted.code.CompileQueue.doCompile(CompileQueue.java:947)
	at com.oracle.svm.hosted.code.CompileQueue$CompileTask.run(CompileQueue.java:263)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
	Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
Fatal error:org.graalvm.compiler.debug.GraalError: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at method: void org.hibernate.boot.registry.internal.BootstrapServiceRegistryImpl.configureService(ServiceBinding)  [Virtual call from Service AbstractServiceRegistryImpl.initializeService(ServiceBinding), callTarget void ServiceBinding$ServiceLifecycleOwner.configureService(ServiceBinding)]
	at com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:1016)
	at com.oracle.svm.hosted.code.CompileQueue.doCompile(CompileQueue.java:947)
	at com.oracle.svm.hosted.code.CompileQueue$CompileTask.run(CompileQueue.java:263)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
Error: Image build request failed with exit status 1
```

Apart from that, I also saw the ANTLR mismatch, don't know if that is an issue, but maybe you can investigate this?

If you have to change something in the quarkus-ecosystem-ci, it would be cool if you could bump the version to the latest Alpha version.

**Comment by Mobe91** [comment]
What ANTLR mismatch?

**Comment by beikov** [comment]
>ANTLR Tool version 4.7.2 used for code generation does not match the current runtime version 4.8ANTLR Runtime version 4.7.2 used for parser compilation does not match the current runtime version 4.8ANTLR Tool version 4.7.2 used for code generation does not match the current runtime version 4.8ANTLR Runtime version 4.7.2 used for parser compilation does not match the current runtime version 4.8Exception in thread "native-image pid watcher" java.lang.OutOfMemoryError: GC overhead limit exceeded
