### ISSUE TITLE
Bytecode enhancement fails.

### ISSUE THREAD

**Issue by soberich** [Blazebit/blaze-persistence#1159]
### Description

When apply bytecode enhancement it fails.

### Actual behavior

```console
Caused by: java.lang.IllegalStateException: Cannot resolve type description for com.example.marvel.api.RecordCollectionDetailedView
	at net.bytebuddy.pool.TypePool$Resolution$Illegal.resolve(TypePool.java:157)
	at net.bytebuddy.pool.TypePool$Default$WithLazyResolution$LazyTypeDescription.delegate(TypePool.java:912)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase$OfSimpleType$WithDelegation.getSuperClass(TypeDescription.java:8271)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase.isAssignable(TypeDescription.java:7649)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase.isAssignableFrom(TypeDescription.java:7676)
	at net.bytebuddy.description.type.TypeDescription$ForLoadedType.isAssignableFrom(TypeDescription.java:8508)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase.isAssignable(TypeDescription.java:7656)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase.isAssignableTo(TypeDescription.java:7690)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase.isAssignableTo(TypeDescription.java:7683)
	at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl.alreadyEnhanced(EnhancerImpl.java:346)
	at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl.doEnhance(EnhancerImpl.java:153)
	at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl.lambda$enhance$0(EnhancerImpl.java:132)
	at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl$$Lambda$1860/00000000410C3420.apply(Unknown Source)
	at org.hibernate.bytecode.internal.bytebuddy.ByteBuddyState.rewrite(ByteBuddyState.java:141)
	at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl.enhance(EnhancerImpl.java:132)
	... 112 more

```
### Steps to reproduce

I'll fill this if it'll be hard to reproduce, but it should be easy.

Probably a good solution will be for all Blaze Persistence managed types to implement `org.hibernate.engine.spi.Managed`, which will resolve this issue due to check in `EnhancerImpl#alreadyEnhanced`. This also seem quite logical to mark Blaze Persistence managed types for Hibernate to be aware 

### Environment

Version:            1.5.0-SNAPSHOT
JPA-Provider:       Hibernate 5.4.+
DBMS:               H2
Application Server: Tomcat(Spring Boot), Netty (Micronaut)

**Comment by beikov** [comment]
Hi soberich,

I am not sure what the exact problem is that you are facing. Hibernate enhancement shouldn't touch entity view classes, so maybe this is a misconfiguration or this is a Hibernate bug. Could you please create a reproducer for this?

**Comment by beikov** [comment]
Would you mind giving some more details here @soberich? I'll close the issue for now until you write back as I don't understand the issue and can therefore not reproduce it.
