### ISSUE TITLE
Handle null initial values properly in CollectionAttributeFlusher

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#1179]
When using `evm.convert` we set the initial value of attributes to null when using the MARK_NEW flag which we don't handle correctly in `CollectionAttributeFlusher` and maybe some other collection flushers as well. This should be fixed.

```
Caused by: java.lang.NullPointerException
	at com.blazebit.persistence.view.impl.update.flush.CollectionAttributeFlusher.getDirtyFlusher(CollectionAttributeFlusher.java:1210)
	at com.blazebit.persistence.view.impl.update.flush.CompositeAttributeFlusher.updateFlushers(CompositeAttributeFlusher.java:1214)
	at com.blazebit.persistence.view.impl.update.flush.CompositeAttributeFlusher.getNestedDirtyFlusher(CompositeAttributeFlusher.java:1194)
	at com.blazebit.persistence.view.impl.update.EntityViewUpdaterImpl.getNestedDirtyFlusher(EntityViewUpdaterImpl.java:607)
	at com.blazebit.persistence.view.impl.update.EntityViewUpdaterImpl.update(EntityViewUpdaterImpl.java:683)
	at com.blazebit.persistence.view.impl.update.EntityViewUpdaterImpl.executeUpdate(EntityViewUpdaterImpl.java:622)
	at com.blazebit.persistence.view.impl.EntityViewManagerImpl.update(EntityViewManagerImpl.java:1165)
	at com.blazebit.persistence.view.impl.EntityViewManagerImpl.update(EntityViewManagerImpl.java:1125)
	at com.blazebit.persistence.view.impl.EntityViewManagerImpl.save(EntityViewManagerImpl.java:1042)
```

**Comment by di-d6** [comment]
> When using `evm.convert` we set the initial value of attributes to null when using the MARK_NEW flag which we don't handle correctly in `CollectionAttributeFlusher` and maybe some other collection flushers as well. This should be fixed.
> 
> ```
> Caused by: java.lang.NullPointerException
> 	at com.blazebit.persistence.view.impl.update.flush.CollectionAttributeFlusher.getDirtyFlusher(CollectionAttributeFlusher.java:1210)
> 	at com.blazebit.persistence.view.impl.update.flush.CompositeAttributeFlusher.updateFlushers(CompositeAttributeFlusher.java:1214)
> 	at com.blazebit.persistence.view.impl.update.flush.CompositeAttributeFlusher.getNestedDirtyFlusher(CompositeAttributeFlusher.java:1194)
> 	at com.blazebit.persistence.view.impl.update.EntityViewUpdaterImpl.getNestedDirtyFlusher(EntityViewUpdaterImpl.java:607)
> 	at com.blazebit.persistence.view.impl.update.EntityViewUpdaterImpl.update(EntityViewUpdaterImpl.java:683)
> 	at com.blazebit.persistence.view.impl.update.EntityViewUpdaterImpl.executeUpdate(EntityViewUpdaterImpl.java:622)
> 	at com.blazebit.persistence.view.impl.EntityViewManagerImpl.update(EntityViewManagerImpl.java:1165)
> 	at com.blazebit.persistence.view.impl.EntityViewManagerImpl.update(EntityViewManagerImpl.java:1125)
> 	at com.blazebit.persistence.view.impl.EntityViewManagerImpl.save(EntityViewManagerImpl.java:1042)
> ```



> When using `evm.convert` we set the initial value of attributes to null when using the MARK_NEW flag which we don't handle correctly in `CollectionAttributeFlusher` and maybe some other collection flushers as well. This should be fixed.
> 
> ```
> Caused by: java.lang.NullPointerException
> 	at com.blazebit.persistence.view.impl.update.flush.CollectionAttributeFlusher.getDirtyFlusher(CollectionAttributeFlusher.java:1210)
> 	at com.blazebit.persistence.view.impl.update.flush.CompositeAttributeFlusher.updateFlushers(CompositeAttributeFlusher.java:1214)
> 	at com.blazebit.persistence.view.impl.update.flush.CompositeAttributeFlusher.getNestedDirtyFlusher(CompositeAttributeFlusher.java:1194)
> 	at com.blazebit.persistence.view.impl.update.EntityViewUpdaterImpl.getNestedDirtyFlusher(EntityViewUpdaterImpl.java:607)
> 	at com.blazebit.persistence.view.impl.update.EntityViewUpdaterImpl.update(EntityViewUpdaterImpl.java:683)
> 	at com.blazebit.persistence.view.impl.update.EntityViewUpdaterImpl.executeUpdate(EntityViewUpdaterImpl.java:622)
> 	at com.blazebit.persistence.view.impl.EntityViewManagerImpl.update(EntityViewManagerImpl.java:1165)
> 	at com.blazebit.persistence.view.impl.EntityViewManagerImpl.update(EntityViewManagerImpl.java:1125)
> 	at com.blazebit.persistence.view.impl.EntityViewManagerImpl.save(EntityViewManagerImpl.java:1042)
> ```
