### ISSUE TITLE
Can't order by

### ISSUE THREAD

**Issue by luyuanx2** [Blazebit/blaze-persistence#1225]
When i order by `productCostCte.productCost.desc()` 

```text
java.lang.IllegalStateException: The order by items of the query builder are not guaranteed to produce unique tuples! Consider also ordering by the entity identifier!
	at com.blazebit.persistence.impl.PaginatedCriteriaBuilderImpl.prepareAndCheck(PaginatedCriteriaBuilderImpl.java:703)
	at com.blazebit.persistence.impl.PaginatedCriteriaBuilderImpl.getQuery(PaginatedCriteriaBuilderImpl.java:461)
	at com.blazebit.persistence.impl.PaginatedCriteriaBuilderImpl.getResultList(PaginatedCriteriaBuilderImpl.java:552)
	at com.blazebit.persistence.querydsl.AbstractBlazeJPAQuery.fetchPage(AbstractBlazeJPAQuery.java:198)
```

my code:
```java
new BlazeJPAQuery<>(entityManager, cbf)
                .with(resourceCostCte,
                        select(
                                ...
                )
                .with(productCostCte,
                        select(
                                ...

                ).with(saveCostCte,
                        select(
                                ...

                ).select(
                        Projections.bean(ResourceCostDTO.class,
                                ...
                        )
                )
                .from(resourceCostCte)
                .leftJoin(productCostCte).on(resourceCostCte.resourceId.eq(productCostCte.resourceId))
                .leftJoin(saveCostCte).on(productCostCte.resourceId.eq(saveCostCte.resourceId))
                .orderBy(productCostCte.productCost.desc())
                .fetchPage((int) pageRequest.getOffset(), pageRequest.getPageSize());

**Comment by beikov** [comment]
Hi @luyuanx2,

you can't paginate `resourceCostCte` objects when ordering just by the product cost. The ordering must be unambiguous, meaning that you have to add some unique attribute to the order by clause.

Usually, this is done by adding the primary key at as last order by item. I don't know your model, but I guess if you add `.orderBy(productCostCte.id.desc())` it should work.

**Comment by beikov** [comment]
I'll close this for now as I think my comment should help you resolve the issue. Feel free to comment further on this issue if that doesn't work for you.

**Comment by luyuanx2** [comment]
> I'll close this for now as I think my comment should help you resolve the issue. Feel free to comment further on this issue if that doesn't work for you.

When i add some unique attribute`.orderBy(productCostItemCte.productCost.desc(), costItemCte.resourceCostItemCtePK.resourceId.asc()
                        ,costItemCte.resourceCostItemCtePK.billingItemId.asc())`, other error occurred. if order by with unique attribute`.orderBy(costItemCte.resourceCostItemCtePK.resourceId.asc(),costItemCte.resourceCostItemCtePK.billingItemId.asc())`,  it's ok
```text
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'resourcepr27_.productCost' in 'order clause'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3970)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3906)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2677)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2549)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1962)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:228)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:57)
	at org.hibernate.loader.Loader.getResultSet(Loader.java:2292)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2050)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2012)
	at org.hibernate.loader.Loader.doQuery(Loader.java:953)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:354)
	at org.hibernate.loader.Loader.doList(Loader.java:2838)
	at org.hibernate.loader.Loader.doList(Loader.java:2820)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2652)
	at org.hibernate.loader.Loader.list(Loader.java:2647)
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:506)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:396)
	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:219)
	at com.blazebit.persistence.integration.hibernate.Hibernate53Access.performList(Hibernate53Access.java:140)
	at com.blazebit.persistence.integration.hibernate.base.HibernateExtendedQuerySupport.list(HibernateExtendedQuerySupport.java:387)
	at com.blazebit.persistence.integration.hibernate.base.HibernateExtendedQuerySupport.getResultList(HibernateExtendedQuerySupport.java:312)
	at com.blazebit.persistence.impl.plan.CustomSelectQueryPlan.getResultList(CustomSelectQueryPlan.java:58)
	at com.blazebit.persistence.impl.query.CustomSQLTypedQuery.getResultList(CustomSQLTypedQuery.java:51)
	at com.blazebit.persistence.impl.query.TypedQueryWrapper.getResultList(TypedQueryWrapper.java:45)
	at com.blazebit.persistence.impl.query.ObjectBuilderTypedQuery.getResultList(ObjectBuilderTypedQuery.java:59)
	at com.blazebit.persistence.impl.PaginatedTypedQueryImpl.getResultList(PaginatedTypedQueryImpl.java:388)
	at com.blazebit.persistence.impl.PaginatedTypedQueryImpl.getResultList(PaginatedTypedQueryImpl.java:203)
	at com.blazebit.persistence.impl.PaginatedCriteriaBuilderImpl.getResultList(PaginatedCriteriaBuilderImpl.java:552)
	at com.blazebit.persistence.querydsl.AbstractBlazeJPAQuery.fetchPage(AbstractBlazeJPAQuery.java:198)
```

**Comment by luyuanx2** [comment]
I used sql tool validate the print sql，it find error too. why auto add order by `resourcepr27_.productCost DESC` in tmp table
![image](https://user-images.githubusercontent.com/26129033/100958008-7917e200-3556-11eb-87c0-5852f4692f5b.png)

**Comment by jwgmeligmeyling** [comment]
It didn't automatically add it, you specified it:

```java
orderBy(
     productCostItemCte.productCost.desc(), // <--
     costItemCte.resourceCostItemCtePK.resourceId.asc() ,
     costItemCte.resourceCostItemCtePK.billingItemId.asc())
```

I think `productCostItemCte.productCost` is simply unreachable in your final query.
