### ISSUE TITLE
NumberFormatException in OracleDbmsLimitHandler

### ISSUE THREAD

**Issue by Lightmoor** [Blazebit/blaze-persistence#1283]
Hello I found a NumberFormatException in OracleDbmsLimitHandler.

I try to search over different entitys (AntragBlau, AntragRot) via union.
The result typ is a custom CTE.

When I select all elements it works fine, but when I add maxResult and firstResult it crashed.
With page instead of setMaxResults and setFirstResult the same issue.

I debug a litte in saw in AbstractDbmsLimitHandler the 5 is replaced by ? and this crashed in OracleDbmsLimitHandler.
Is there any special reason for that?

Hopefully you can fix that.
nice greetings from Germany

```
@CTE
@Entity
public class PostkorbCTEItem {
    @Id
    Long id;
       String kursnummer;
    String standortnummer;
}

```

```
CriteriaBuilder<PostkorbCTEItem> cb = criteriaBuilderFactory.create(em, PostkorbCTEItem.class).with(PostkorbCTEItem.class)
                .from(AntragBlau.class, "antrag")
                        .bind("kursnummer").select("antrag.kursnummer")
                        .bind("standortnummer").select("antrag.standortnummer")
                        .bind("id").select("antrag.id")
                    .unionAll()
                        .from(AntragRot.class, "antrag")
                        .bind("kursnummer").select("antrag.kursnummer")
                        .bind("standortnummer").select("antrag.standortnummer")
                        .bind("id").select("antrag.id")
                .endSet().end().setMaxResults(5).setFirstResult(5).orderByAsc("kursnummer").getResultList();

```
				
```
java.lang.NumberFormatException: For input string: "?"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.blazebit.persistence.impl.dialect.OracleDbmsLimitHandler.applySql(OracleDbmsLimitHandler.java:88)
	at com.blazebit.persistence.impl.dialect.AbstractDbmsLimitHandler.applySql(AbstractDbmsLimitHandler.java:71)
	at com.blazebit.persistence.integration.hibernate.Hibernate53LimitHandler.processSql(Hibernate53LimitHandler.java:64)
```

Environment
Version: 1.5.1

**Comment by beikov** [comment]
Thanks for the bug report. Let's see what the tests say :)

Can you verify if this fixes your issues? https://github.com/Blazebit/blaze-persistence/pull/1284

**Comment by Lightmoor** [comment]
Helllo beikov, 
thank you for the fast replay. 
The Fix looks fine and works for me.

Thank you!

**Comment by beikov** [comment]
Thanks for confirming!
