### ISSUE TITLE
Remove view by id with cascaded collection having embedded id fails

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#1299]
`evm.remove(em, MyView.class, id)` fails if `MyView` contains a collection with cascade delete, when the id of the element type is an embeddable. The problem is, that the InverseFlusher passes entity ids to the deleter, but for views, it expects view ids.

**Comment by EugenMayer** [comment]
Thank you!

**Comment by EugenMayer** [comment]
It has fixed one of 2 cascade scenarios.

Using 1.6.0 i get 

```
com.blazebit.persistence.parser.expression.SyntaxErrorException: Could not parse expression 'id.', line 1:3 missing {AFTER, ALL, AND, ANY, AS, ASC, BEFORE, BETWEEN, BOTH, BY, CASE, COLLATE, CONTAINING, COUNT, CROSS, CURRENT, DELETE, DESC, DISTINCT, ELSE, EMPTY, END, ENTRY, ESCAPE, EXCEPT, EXCLUDE, EXISTS, FETCH, FILTER, FIRST, FOLLOWING, FROM, FULL, GROUP, GROUPS, HAVING, IN, INDEX, INNER, INSERT, INTERSECT, INTO, IS, JOIN, JUMP, KEY, LAST, LEADING, LEFT, LIKE, LIMIT, MEMBER, NEW, NO, NOT, NULLS, OBJECT, OF, OFFSET, ON, OR, ORDER, OTHERS, OUTER, OVER, PAGE, PARTITION, PRECEDING, RANGE, RECURSIVE, RETURNING, RIGHT, ROW, ROWS, SELECT, SET, SOME, THEN, TIES, TO, TRAILING, TREAT, TRIM, TYPE, UNBOUNDED, UNION, UPDATE, VALUE, VALUES, WHEN, WHERE, WINDOW, WITH, IDENTIFIER} at '<EOF>'
	at com.blazebit.persistence.parser.expression.AbstractExpressionFactory.createExpression(AbstractExpressionFactory.java:183)
	at com.blazebit.persistence.parser.expression.AbstractExpressionFactory.createSimpleExpression(AbstractExpressionFactory.java:226)
	at com.blazebit.persistence.parser.expression.AbstractCachingExpressionFactory$2.get(AbstractCachingExpressionFactory.java:56)
	at com.blazebit.persistence.parser.expression.AbstractCachingExpressionFactory.getOrDefault(AbstractCachingExpressionFactory.java:158)
	at com.blazebit.persistence.parser.expression.AbstractCachingExpressionFactory.createSimpleExpression(AbstractCachingExpressionFactory.java:109)
	at com.blazebit.persistence.impl.JpqlMacroAwareExpressionFactory.createSimpleExpression(JpqlMacroAwareExpressionFactory.java:95)
	at com.blazebit.persistence.impl.AbstractCommonQueryBuilder.where(AbstractCommonQueryBuilder.java:1407)
	at com.blazebit.persistence.view.impl.update.flush.CompositeAttributeFlusher.remove(CompositeAttributeFlusher.java:1050)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: com.blazebit.persistence.parser.expression.SyntaxErrorException: line 1:3 missing {AFTER, ALL, AND, ANY, AS, ASC, BEFORE, BETWEEN, BOTH, BY, CASE, COLLATE, CONTAINING, COUNT, CROSS, CURRENT, DELETE, DESC, DISTINCT, ELSE, EMPTY, END, ENTRY, ESCAPE, EXCEPT, EXCLUDE, EXISTS, FETCH, FILTER, FIRST, FOLLOWING, FROM, FULL, GROUP, GROUPS, HAVING, IN, INDEX, INNER, INSERT, INTERSECT, INTO, IS, JOIN, JUMP, KEY, LAST, LEADING, LEFT, LIKE, LIMIT, MEMBER, NEW, NO, NOT, NULLS, OBJECT, OF, OFFSET, ON, OR, ORDER, OTHERS, OUTER, OVER, PAGE, PARTITION, PRECEDING, RANGE, RECURSIVE, RETURNING, RIGHT, ROW, ROWS, SELECT, SET, SOME, THEN, TIES, TO, TRAILING, TREAT, TRIM, TYPE, UNBOUNDED, UNION, UPDATE, VALUE, VALUES, WHEN, WHERE, WINDOW, WITH, IDENTIFIER} at '<EOF>'
	at com.blazebit.persistence.parser.expression.AbstractExpressionFactory$1.syntaxError(AbstractExpressionFactory.java:58)
	at com.blazebit.persistence.parser.antlr.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at com.blazebit.persistence.parser.antlr.Parser.notifyErrorListeners(Parser.java:544)
	at com.blazebit.persistence.parser.antlr.DefaultErrorStrategy.reportMissingToken(DefaultErrorStrategy.java:409)
	at com.blazebit.persistence.parser.antlr.DefaultErrorStrategy.singleTokenInsertion(DefaultErrorStrategy.java:519)
	at com.blazebit.persistence.parser.antlr.DefaultErrorStrategy.recoverInline(DefaultErrorStrategy.java:476)
	at com.blazebit.persistence.parser.JPQLNextParser.identifier(JPQLNextParser.java:10908)
	at com.blazebit.persistence.parser.JPQLNextParser.simpleSubpath(JPQLNextParser.java:4815)
	at com.blazebit.persistence.parser.JPQLNextParser.generalSubpath(JPQLNextParser.java:4875)
	at com.blazebit.persistence.parser.JPQLNextParser.path(JPQLNextParser.java:4443)
	at com.blazebit.persistence.parser.JPQLNextParser.expression(JPQLNextParser.java:6988)
	at com.blazebit.persistence.parser.JPQLNextParser.parseExpression(JPQLNextParser.java:420)
	at com.blazebit.persistence.parser.expression.ExpressionFactoryImpl$1.invokeRule(ExpressionFactoryImpl.java:38)
	at com.blazebit.persistence.parser.expression.AbstractExpressionFactory.createExpression(AbstractExpressionFactory.java:179)
```

Seems to be some wrong JPQL expression?

**Comment by beikov** [comment]
Maybe. Could you show me the model?
