### ISSUE TITLE
NPE when flushing updatable entity view with plural mapping for element collection using embeddable types 

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#1308]
See the reproducer here https://github.com/ahofmeister/bp-collection-updating-reproducer

The exception seems to be:

```
Request failed: java.lang.NullPointerException
	at com.blazebit.persistence.view.impl.update.flush.AbstractPluralAttributeFlusher.invokeFlushOperation(AbstractPluralAttributeFlusher.java:282)
	at com.blazebit.persistence.view.impl.update.flush.CollectionAttributeFlusher.flushQuery(CollectionAttributeFlusher.java:285)
	at com.blazebit.persistence.view.impl.update.flush.CollectionAttributeFlusher.flushQuery(CollectionAttributeFlusher.java:62)
	at com.blazebit.persistence.view.impl.update.flush.CompositeAttributeFlusher.flushQuery(CompositeAttributeFlusher.java:450)
	at com.blazebit.persistence.view.impl.update.EntityViewUpdaterImpl.update(EntityViewUpdaterImpl.java:710)
	at com.blazebit.persistence.view.impl.update.EntityViewUpdaterImpl.executeUpdate(EntityViewUpdaterImpl.java:636)
	at com.blazebit.persistence.view.impl.EntityViewManagerImpl.update(EntityViewManagerImpl.java:1182)
	at com.blazebit.persistence.view.impl.EntityViewManagerImpl.update(EntityViewManagerImpl.java:1142)
	at com.blazebit.persistence.view.impl.EntityViewManagerImpl.save(EntityViewManagerImpl.java:1059)
```

I think this can be worked-around by using an `@UpdatableEntityView` for the embeddable type instead.

**Comment by ahofmeister** [comment]
I don't think, the workaround will work. I added `@UpdatableEntityView` to the `FoodUnitUpdateView` and replaced it in the `FoodUpdateView`, started the test and t's the same exception and the same Stacktrace.
