### ISSUE TITLE
Enum fields with an Converter are not supported during partial updates

### ISSUE THREAD

**Issue by EugenMayer** [Blazebit/blaze-persistence#1312]
### Description
When having an `Entity` with an enum which is using an converter like

```java
  @Convert(converter = UserLanguageConverter.class)
  @Column(columnDefinition = "VARCHAR(12) default 'de'")
  private UserLanguage language;
```

And then using an update view which uses partial updates like 

```java
@EntityView(User.class)
@UpdatableEntityView(strategy = FlushStrategy.ENTITY, mode = FlushMode.PARTIAL)
public interface UserProfilePictureUpdateView extends UserIdView
{
  @UpdatableMapping(cascade = CascadeType.DELETE)
  UploadedFileIdView getPicture();

  void setPicture(UploadedFileIdView uploadedFileIdView);
}
```

It will always throw an exception like that the  attribute converter `UserLanguageConverter` cannot convert `null`.

### Expected behavior

Due to the partial update mode, it should not try to set / convert that enum / field `language` at all.
It should just be an partial update

### Actual behavior

An exception is thrown

<details>
<summary>Exception</summary>
12:25:55.780 [http-nio-8080-exec-9] ERROR d.k.d.b.a.e.GeneralExceptionResolver ⬩ Resolving exception as problem response:javax.persistence.PersistenceException: Error attempting to apply AttributeConverter	at org.hibernate.type.descriptor.converter.AttributeConverterSqlTypeDescriptorAdapter$2.doConversion(AttributeConverterSqlTypeDescriptorAdapter.java:148) ~[hibernate-core-5.4.30.Final.jar!/:5.4.30.Final]	at org.hibernate.type.descriptor.converter.AttributeConverterSqlTypeDescriptorAdapter$2.extract(AttributeConverterSqlTypeDescriptorAdapter.java:121) ~[hibernate-core-5.4.30.Final.jar!/:5.4.30.Final]	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:257) ~[hibernate-core-5.4.30.Final.jar!/:5.4.30.Final]	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:253) ~[hibernate-core-5.4.30.Final.jar!/:5.4.30.Final]	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:243) ~[hibernate-core-5.4.30.Final.jar!/:5.4.30.Final]	at org.hibernate.type.AbstractStandardBasicType.hydrate(AbstractStandardBasicType.java:329) ~[hibernate-core-5.4.30.Final.jar!/:5.4.30.Final]	at org.hibernate.persister.entity.AbstractEntityPersister.hydrate(AbstractEntityPersister.java:3130) ~[hibernate-core-5.4.30.Final.jar!/:5.4.30.Final]	at org.hibernate.loader.Loader.loadFromResultSet(Loader.java:1869) ~[hibernate-core-5.4.30.Final.jar!/:5.4.30.Final]	at org.hibernate.loader.Loader.hydrateEntityState(Loader.java:1797) ~[hibernate-core-5.4.30.Final.jar!/:5.4.30.Final]	at org.hibernate.loader.Loader.instanceNotYetLoaded(Loader.java:1770) ~[hibernate-core-5.4.30.Final.jar!/:5.4.30.Final]	at org.hibernate.loader.Loader.getRow(Loader.java:1622) ~[hibernate-core-5.4.30.Final.jar!/:5.4.30.Final]	at org.hibernate.loader.Loader.getRowFromResultSet(Loader.java:740) ~[hibernate-core-5.4.30.Final.jar!/:5.4.30.Final]	at org.hibernate.loader.Loader.getRowsFromResultSet(Loader.java:1039) ~[hibernate-core-5.4.30.Final.jar!/:5.4.30.Final]	at org.hibernate.loader.Loader.processResultSet(Loader.java:990) ~[hibernate-core-5.4.30.Final.jar!/:5.4.30.Final]	at org.hibernate.loader.Loader.doQuery(Loader.java:959) ~[hibernate-core-5.4.30.Final.jar!/:5.4.30.Final]	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:349) ~[hibernate-core-5.4.30.Final.jar!/:5.4.30.Final]	at org.hibernate.loader.Loader.doList(Loader.java:2849) ~[hibernate-core-5.4.30.Final.jar!/:5.4.30.Final]	at org.hibernate.loader.Loader.doList(Loader.java:2831) ~[hibernate-core-5.4.30.Final.jar!/:5.4.30.Final]	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2663) ~[hibernate-core-5.4.30.Final.jar!/:5.4.30.Final]	at org.hibernate.loader.Loader.list(Loader.java:2658) ~[hibernate-core-5.4.30.Final.jar!/:5.4.30.Final]	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:506) ~[hibernate-core-5.4.30.Final.jar!/:5.4.30.Final]	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:400) ~[hibernate-core-5.4.30.Final.jar!/:5.4.30.Final]	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:219) ~[hibernate-core-5.4.30.Final.jar!/:5.4.30.Final]	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1414) ~[hibernate-core-5.4.30.Final.jar!/:5.4.30.Final]	at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1625) ~[hibernate-core-5.4.30.Final.jar!/:5.4.30.Final]	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1593) ~[hibernate-core-5.4.30.Final.jar!/:5.4.30.Final]	at org.hibernate.query.Query.getResultList(Query.java:165) ~[hibernate-core-5.4.30.Final.jar!/:5.4.30.Final]	at com.blazebit.persistence.view.impl.entity.ReferenceEntityLoader.queryEntity(ReferenceEntityLoader.java:80) ~[blaze-persistence-entity-view-impl-1.6.0.jar!/:1.6.0]	at com.blazebit.persistence.view.impl.entity.AbstractEntityLoader.getReferenceOrLoad(AbstractEntityLoader.java:127) ~[blaze-persistence-entity-view-impl-1.6.0.jar!/:1.6.0]	at com.blazebit.persistence.view.impl.entity.ReferenceEntityLoader.toEntity(ReferenceEntityLoader.java:65) ~[blaze-persistence-entity-view-impl-1.6.0.jar!/:1.6.0]	at com.blazebit.persistence.view.impl.entity.TargetViewClassBasedEntityLoader.toEntity(TargetViewClassBasedEntityLoader.java:57) ~[blaze-persistence-entity-view-impl-1.6.0.jar!/:1.6.0]	at com.blazebit.persistence.view.impl.entity.AbstractViewToEntityMapper.loadEntity(AbstractViewToEntityMapper.java:193) ~[blaze-persistence-entity-view-impl-1.6.0.jar!/:1.6.0]	at com.blazebit.persistence.view.impl.update.flush.SubviewAttributeFlusher.flushEntity(SubviewAttributeFlusher.java:411) ~[blaze-persistence-entity-view-impl-1.6.0.jar!/:1.6.0]	at com.blazebit.persistence.view.impl.update.flush.CompositeAttributeFlusher.flushEntity(CompositeAttributeFlusher.java:700) ~[blaze-persistence-entity-view-impl-1.6.0.jar!/:1.6.0]	at com.blazebit.persistence.view.impl.update.EntityViewUpdaterImpl.executePersist(EntityViewUpdaterImpl.java:732) ~[blaze-persistence-entity-view-impl-1.6.0.jar!/:1.6.0]	at com.blazebit.persistence.view.impl.update.EntityViewUpdaterImpl.executePersist(EntityViewUpdaterImpl.java:727) ~[blaze-persistence-entity-view-impl-1.6.0.jar!/:1.6.0]	at com.blazebit.persistence.view.impl.EntityViewManagerImpl.update(EntityViewManagerImpl.java:1180) ~[blaze-persistence-entity-view-impl-1.6.0.jar!/:1.6.0]
</details>

### Steps to reproduce

- an entity with one String field1 and one Enum enum1
- the enum field should have an converter as show above
- create an update partial update view updating field1 not including enum1 (as show above)
- run evm.udpate on that view

**Important**: One important thing is, that this issue does not occur when the entire entity is already in the L1 cache. So pre-fetching before updating will fix this issue. So when reproducing this, `entityManager.clear()` should be used

### Environment			
Version:            1.6.0		
JPA-Provider:       Hibernate 5.4.30.Final		
DBMS:               MariaDB 12			
Application Server: Spring Boot 2.4.5

**Comment by EugenMayer** [comment]
This was a false positive all the way down. 

In the end it was a wrong, unexpected database value (empty string .. not just null) which could not be handled when the entity was loaded during the entity flush strategy. 

Sorry!
