### ISSUE TITLE
Add support for Spring boot 2.5+/Spring data 2021.0

### ISSUE THREAD

**Issue by ask4gilles** [Blazebit/blaze-persistence#1333]
Hi,

I just tried 1.6.1 together with SB 2.5.4 and got several issues regarding java.time module not added in the entityViewObjectMapper and exceptions regarding generated queries.

Do you plan to support this latest version?
Thanks!

**Comment by ask4gilles** [comment]
Hi @beikov

First, sorry to comment on a closed issue.

In fact, regarding the `java.time` issue, it is well present, but I should have mention that the issue lies in the `spring-hateoas-webmvc` module where a new `ObjectMapper` bean is created at different places without the `JavaTimeModule` registered...
So, even though in my configuration I don't create `ObjectMapper` and I define a `JavaTimeModule` bean,
when performing the keyset pagination with hateoas, I get the following exception:

```
- com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type `java.time.Instant` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling
java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type `java.time.Instant` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling
        at com.blazebit.persistence.spring.hateoas.webmvc.KeysetAwarePagedResourcesAssembler.serialize(KeysetAwarePagedResourcesAssembler.java:231)
        at com.blazebit.persistence.spring.hateoas.webmvc.KeysetAwarePagedResourcesAssembler.createLink(KeysetAwarePagedResourcesAssembler.java:195)
        at com.blazebit.persistence.spring.hateoas.webmvc.KeysetAwarePagedResourcesAssembler.addPaginationLinks(KeysetAwarePagedResourcesAssembler.java:160)
        at com.blazebit.persistence.spring.hateoas.webmvc.KeysetAwarePagedResourcesAssembler.createModel(KeysetAwarePagedResourcesAssembler.java:138)
        at com.blazebit.persistence.spring.hateoas.webmvc.KeysetAwarePagedResourcesAssembler.toModel(KeysetAwarePagedResourcesAssembler.java:88)
        at com.blazebit.persistence.spring.hateoas.webmvc.KeysetAwarePagedResourcesAssembler.toModel(KeysetAwarePagedResourcesAssembler.java:80)
[...]
```
If I downgrade jackson to `2.11.4` (still with BP `1.6.1`), then it's fine.
Do you see any other workaround for now?

**Comment by beikov** [comment]
I can look at it tomorrow and I plan to do a release this weekend anyway, so maybe you don't need a workaround :)

Do you have an idea how this could be fixed?

**Comment by ask4gilles** [comment]
Wow, it would be awesome since we had to cancel today's release because of that :/
I think that we should either just rely on the SB autoconfigured `ObjectMapper` either register the time module when you instantiate it:

```
objectMapper.registerModule(new JavaTimeModule());
```

**Comment by beikov** [comment]
Let's move the discussion to this issue: https://github.com/Blazebit/blaze-persistence/issues/1348

**Comment by beikov** [comment]
Would be cool if you could checkout the following PR and let me know if that works for you @ask4gilles: https://github.com/Blazebit/blaze-persistence/pull/1347

**Comment by ask4gilles** [comment]
@beikov sure, I’ll have a look at it tomorrow !
