### ISSUE TITLE
java.lang.NoSuchFieldError: hints

### ISSUE THREAD

**Issue by H-Lo** [Blazebit/blaze-persistence#1340]
### Getting exception _java.lang.NoSuchFieldError: hints_

Trying to run relatively simple query and exception pops out telling me _NoSuchFieldError: hints_ - but I don't use hints at all.

### Expected behavior

Expecting query result as long value of count

### Actual behavior

Exception pops out

### Steps to reproduce

	public long countByStatus_Blaze(Article.Status status) {
		QArticle article = QArticle.article;
		return
			new BlazeJPAQuery<>(this.entityManager, this.criteriaBuilderFactory)
				.select(article)
				.from(article)
				.where(article.status.eq(status))
				.fetchCount();
	}

### Environment

Version:            
JPA-Provider:       
DBMS:               
Application Server: 

	INFO  org.springframework.boot.web.embedded.tomcat.TomcatWebServer    Tomcat initialized with port(s): 80 (http)
	INFO  org.apache.catalina.core.StandardService                        Starting service [Tomcat]
	INFO  org.apache.catalina.core.StandardEngine                         Starting Servlet engine: [Apache Tomcat/9.0.52]

### pom.xml

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.5.4</version>
		<relativePath />
	</parent>

	<properties>
		<hibernate.version>5.5.6.Final</hibernate.version>
		<hibernate-search-orm.version>5.11.9.Final</hibernate-search-orm.version>
		<blaze-persistence.version>1.5.1</blaze-persistence.version>
	</properties>

	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-data-jpa</artifactId>
	</dependency>
	<dependency>
		<groupId>com.blazebit</groupId>
		<artifactId>blaze-persistence-core-api</artifactId>
		<version>${blaze-persistence.version}</version>
	</dependency>
	<dependency>
		<groupId>com.blazebit</groupId>
		<artifactId>blaze-persistence-core-impl</artifactId>
		<version>${blaze-persistence.version}</version>
	</dependency>
	<dependency>
		<groupId>com.blazebit</groupId>
		<artifactId>blaze-persistence-integration-hibernate-base</artifactId>
		<version>${blaze-persistence.version}</version>
	</dependency>
	<dependency>
		<groupId>com.blazebit</groupId>
		<artifactId>blaze-persistence-integration-hibernate-5.4</artifactId>
		<version>${blaze-persistence.version}</version>
	</dependency>
	<dependency>
		<groupId>com.blazebit</groupId>
		<artifactId>blaze-persistence-integration-querydsl-expressions</artifactId>
		<version>${blaze-persistence.version}</version>
	</dependency>

### Stack trace:

	java.lang.NoSuchFieldError: hints
		at com.blazebit.persistence.querydsl.AbstractBlazeJPAQuery.getQueryable(AbstractBlazeJPAQuery.java:234)
		at com.blazebit.persistence.querydsl.AbstractBlazeJPAQuery.getFullQueryBuilder(AbstractBlazeJPAQuery.java:213)
		at com.blazebit.persistence.querydsl.AbstractBlazeJPAQuery.createQuery(AbstractBlazeJPAQuery.java:169)
		at com.blazebit.persistence.querydsl.AbstractBlazeJPAQuery.fetchCount(AbstractBlazeJPAQuery.java:258)
		at com.thevegcat.app.entities.article.repository.ArticleRepositoryImpl.countByStatus_Blaze(ArticleRepositoryImpl.java:71)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
		at org.springframework.data.repository.core.support.RepositoryMethodInvoker$RepositoryFragmentMethodInvoker.lambda$new$0(RepositoryMethodInvoker.java:289)
		at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:137)
		at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:121)
		at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:529)
		at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:285)
		at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:599)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
		at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:163)
		at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:138)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
		at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
		at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
		at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
		at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
		at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
		at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:174)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
		at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
		at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
		at com.sun.proxy.$Proxy183.countByStatus_Blaze(Unknown Source)
		at com.thevegcat.app.entities.article.ArticleServiceImpl.countByStatus_Blaze(ArticleServiceImpl.java:96)
		at com.thevegcat.app.entities.article.ArticleServiceImpl$$FastClassBySpringCGLIB$$3bb7278b.invoke(<generated>)
		at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
		at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
		at com.thevegcat.app.entities.article.ArticleServiceImpl$$EnhancerBySpringCGLIB$$326ede00.countByStatus_Blaze(<generated>)
		at com.thevegcat.app.test.springboot.ArticleTest.countTest(ArticleTest.java:45)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
		at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
		at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
		at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
		at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
		at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
		at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
		at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
		at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
		at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
		at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
		at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
		at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
		at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
		at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
		at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
		at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
		at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
		at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
		at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
		at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
		at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
		at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
		at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
		at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
		at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
		at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:84)
		at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:98)
		at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
		at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
		at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
		at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
		at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

**Comment by beikov** [comment]
Thanks for the report. I suppose you are using QueryDSL 5? Support for that version will land in the upcoming 1.6.2 release and is already available on the snapshot build, in case you want to try it out already.

```
            <repository>
               <id>sonatype-nexus-snapshots</id>
               <name>Sonatype Nexus Snapshots</name>
               <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            </repository>
```

**Comment by jwgmeligmeyling** [comment]
Yes, unfortunately in Querydsl 5 we had to introduce a breaking API change because "hints" was a Guava Multimap and we wanted to get rid of Guava. 

Blaze-Persistence 1.6.2 has the fix for Querydsl 5 whilst maintaining backwards compatibility.

**Comment by H-Lo** [comment]
> Thanks for the report. I suppose you are using QueryDSL 5? Support for that version will land in the upcoming 1.6.2 release and is already available on the snapshot build, in case you want to try it out already.
> 
> ```
>             <repository>
>                <id>sonatype-nexus-snapshots</id>
>                <name>Sonatype Nexus Snapshots</name>
>                <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
>             </repository>
> ```

I'm only able to find 1.6.1 and none of 1.6.2

**Comment by beikov** [comment]
You might have to enable snapshots. I can find it here: https://oss.sonatype.org/service/local/repositories/snapshots/content/com/blazebit/blaze-persistence-core-api/1.6.2-SNAPSHOT/blaze-persistence-core-api-1.6.2-20210829.093537-7.jar

**Comment by H-Lo** [comment]
> Thanks for the report. I suppose you are using QueryDSL 5? Support for that version will land in the upcoming 1.6.2 release and is already available on the snapshot build, in case you want to try it out already.
> 
> ```
>             <repository>
>                <id>sonatype-nexus-snapshots</id>
>                <name>Sonatype Nexus Snapshots</name>
>                <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
>             </repository>
> ```

Well, it was not visible in browse mode @ https://oss.sonatype.org/ but I added it with "-SNAPSHOT" suffix and it works as expected.
