### ISSUE TITLE
java.lang.NoSuchMethodError: 'java.lang.Class sun.misc.Unsafe.defineClass(java.lang.String, byte[], int, int, java.lang.ClassLoader, java.security.ProtectionDomain)'

### ISSUE THREAD

**Issue by nmvr2600** [Blazebit/blaze-persistence#1345]
exceptions under uber-jar mode

### Description
I got exceptions when I tried run quarkun application under uber-jar mode，but eveything works fine under fast jar mode。

### Expected behavior
can render view correctly

### Actual behavior
2021-08-31 10:26:06,312 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /api/dashboard?userId=1 failed, error id: 9a53edfb-56dc-4475-9a79-ec58fad5abba-1: org.jboss.resteasy.spi.UnhandledException: java.lang.NoSuchMethodError: 'java.lang.Class sun.misc.Unsafe.defineClass(java.lang.String, byte[], int, int, java.lang.ClassLoader, java.security.ProtectionDomain)'
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:138)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:536)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NoSuchMethodError: 'java.lang.Class sun.misc.Unsafe.defineClass(java.lang.String, byte[], int, int, java.lang.ClassLoader, java.security.ProtectionDomain)'
	at com.blazebit.persistence.view.impl.proxy.UnsafeHelper.define(UnsafeHelper.java:51)
	at com.blazebit.persistence.view.impl.proxy.ProxyFactory.defineOrGetClass(ProxyFactory.java:1024)
	at com.blazebit.persistence.view.impl.proxy.ProxyFactory.createProxyClass(ProxyFactory.java:625)
	at com.blazebit.persistence.view.impl.proxy.ProxyFactory.getProxy(ProxyFactory.java:263)
	at com.blazebit.persistence.view.impl.proxy.ProxyFactory.getProxy(ProxyFactory.java:180)
	at com.blazebit.persistence.view.impl.proxy.TupleConstructorReflectionInstantiator.<init>(TupleConstructorReflectionInstantiator.java:40)
	at com.blazebit.persistence.view.impl.proxy.AbstractReflectionInstantiator.createInstantiator(AbstractReflectionInstantiator.java:93)
	at com.blazebit.persistence.view.impl.objectbuilder.ViewTypeObjectBuilderTemplate.createInstantiator(ViewTypeObjectBuilderTemplate.java:394)
	at com.blazebit.persistence.view.impl.objectbuilder.ViewTypeObjectBuilderTemplate.<init>(ViewTypeObjectBuilderTemplate.java:329)
	at com.blazebit.persistence.view.impl.objectbuilder.ViewTypeObjectBuilderTemplate.<init>(ViewTypeObjectBuilderTemplate.java:127)
	at com.blazebit.persistence.view.impl.objectbuilder.ViewTypeObjectBuilderTemplate$Key.createValue(ViewTypeObjectBuilderTemplate.java:1523)
	at com.blazebit.persistence.view.impl.EntityViewManagerImpl.getTemplate(EntityViewManagerImpl.java:1375)
	at com.blazebit.persistence.view.impl.EntityViewManagerImpl.createObjectBuilder(EntityViewManagerImpl.java:1359)
	at com.blazebit.persistence.view.impl.EntityViewManagerImpl.applyObjectBuilder(EntityViewManagerImpl.java:1325)
	at com.blazebit.persistence.view.impl.EntityViewSettingHelper.apply(EntityViewSettingHelper.java:104)
	at com.blazebit.persistence.view.impl.EntityViewManagerImpl.applySetting(EntityViewManagerImpl.java:1224)
	at com.fudao.compass.controller.DashboardController.dashboard(DashboardController.java:52)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	... 15 more

### Environment

Version:            1.6.1
JPA-Provider:       Hibernate 5.5.6.Final
DBMS:               mysql 8
Application Server: quarkus uber jar
Jdk：jdk11

**Comment by beikov** [comment]
Hi, it seems the problem is that the uber-jar process does not handle MR-JARs properly and the entity-view-impl.jar is such a MR-JAR. When running normally, a class loader would try to pick the class from META-INF/versions/X where X is lower or equal to the Java version of the running JVM.

Can you check if the uber-jar contains that directory `META-INF/versions/9` and within that the class file for `com.blazebit.persistence.view.impl.proxy.UnsafeHelper`? Maybe the uber-jar process does not copy these files or the class loader in use does not consider the platform version specific classes.

**Comment by nmvr2600** [comment]
Thanks for your reply. I found one solution,  add the blaze-persistence-entity-view-processor as annotationProcessor can avoid this problem.
Currently, I checked META-INF/versions/9 folder, UnsafeHelper file was there.

**Comment by nmvr2600** [comment]
I think I can close this issue.

**Comment by beikov** [comment]
Yeah, using the annotation processor will also be required if you want to compile to native, but nonetheless it would be interesting to understand why the uber-jar mode does not work properly. I assume though that this is a Quarkus issue, so maybe you can report it in their issue tracker.
