### ISSUE TITLE
Make sure ObjectMapper uses retain Spring configured modules

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#1348]
Follow up of https://github.com/Blazebit/blaze-persistence/issues/1333 as the issue seems Spring HATEOAS related

**Comment by ask4gilles** [comment]
Hi @beikov,

Thanks a lot!

- This fixes the `java.time`issue with the `ObjectMapper`.

(I'd have expected some tests with and without provided `ObjectMapper` to be on the safe side ;-) )


- FYI, I build this branch locally but got an error regarding the examples module:

```
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.blazebit:blaze-persistence-examples-spring-data-dgs:1.6.2-SNAPSHOT (C:\Users\e101586\dev\repos\blaze-persistence\examples\spring-data-dgs\pom.xml) has 9 errors
[ERROR]     Non-resolvable import POM: Could not find artifact org.springframework:spring-framework-bom:pom:${version.spring} in MC Artifactory (https://artifacts.mastercard.int/artifactory/maven-all/) @ line 44, column 25 -> [Help 2]
[ERROR]     'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-web:jar must be a valid version but is '${version.spring.boot}'. @ line 65, column 22
[ERROR]     'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-tomcat:jar must be a valid version but is '${version.spring.boot}'. @ line 70, column 22
[ERROR]     'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-test:jar must be a valid version but is '${version.spring.boot}'. @ line 75, column 22
[ERROR]     'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-data-jpa:jar must be a valid version but is '${version.spring.boot}'. @ line 80, column 22
[ERROR]     'dependencies.dependency.version' for org.springframework:spring-context:jar is missing. @ line 136, column 21
[ERROR]     'dependencies.dependency.version' for org.springframework:spring-orm:jar is missing. @ line 140, column 21
[ERROR]     'dependencies.dependency.version' for org.springframework:spring-test:jar is missing. @ line 157, column 21
```
I had to exclude it to build the whole thing.

- Apart from that, **I still have to downgrade the spring-data version** when using this `1.6.2-SNAPSHOT`, otherwhise, I got troubles with `2.5`:

```
org.springframework.dao.InvalidDataAccessApiUsageException: Attribute 'generatedTokenRangeParameters_2' not found on type 'BundleRequestEntity'; nested exception is java.lang.IllegalArgumentException: Attribute 'generatedTokenRangeParameters_2' not found on type 'BundleRequestEntity'
        at org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:374)
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:235)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:551)
        at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)
        at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:152)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at com.blazebit.persistence.spring.data.base.repository.EntityViewAwareCrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(EntityViewAwareCrudMethodMetadataPostProcessor.java:142)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
        at com.sun.proxy.$Proxy183.findByBundleRequestParametersTokenRangeKeyAlias(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
        at com.sun.proxy.$Proxy183.findByBundleRequestParametersTokenRangeKeyAlias(Unknown Source)
```
This is maybe a corner case: the query is performed on an entity containing an `Embedded` which itself contains an `Embedded` like this:
```
@Entity
@Table(name = "BUNDLE_REQUEST")
public class BundleRequestEntity {
@Embedded
private BundleRequestParameters bundleRequestParameters;
}
```

```
@Embeddable
public class BundleRequestParameters {

@Embedded
private TokenRangeParameters tokenRange;
}

```

```
@Embeddable
public class TokenRangeParameters {

	@Column(name = "tokenrange_keyalias")
	private String keyAlias;
```

and here is my `Repository` definition:

```
@Repository
public interface RequestRepository extends JpaRepository<BundleRequestEntity, UUID> {

	List<BundleRequestEntity> findByBundleRequestParametersTokenRangeKeyAlias(String keyAlias);
```

**Comment by beikov** [comment]
>This fixes the java.timeissue with the ObjectMapper.

Great to hear that, thanks for confirming.

>(I'd have expected some tests with and without provided ObjectMapper to be on the safe side ;-) )

I tested this locally, but I might as well commit the change in the model to verify this :)

>FYI, I build this branch locally but got an error regarding the examples module:

How did you build this? I think `mvn clean install -DskipTests -DskipITs` should be enough. Anything else might require that you specify some profiles.

>Apart from that, I still have to downgrade the spring-data version when using this 1.6.2-SNAPSHOT, otherwhise, I got troubles with 2.5:

Looks like a bug in Spring Data 2.5 ;)

You can make use of a specification to model this though or if you want to use an entity view, use an attribute filter:

```
@EntityView(BundleRequestEntity.class)
public interface BundleRequestSimpleView {
    @AttributeFilter(EqualFilter.class)
    @Mapping("bundleRequestParameters.tokenRange.keyAlias")
    String getKeyAlias();
}
@Repository
public interface RequestRepository extends JpaRepository<BundleRequestEntity, UUID> {
    default List<BundleRequestSimpleView> findByBundleRequestParametersTokenRangeKeyAlias(String keyAlias) {
        return findAll(setting -> setting.withAttributeFilter("keyAlias", keyAlias));
    }
    List<BundleRequestSimpleView> findAll(EntityViewSettingProcessor<BundleRequestSimpleView> processor);
}
```

**Comment by ask4gilles** [comment]
> How did you build this? I think mvn clean install -DskipTests -DskipITs should be enough. Anything else might require that you specify some profiles.
mvn clean install
Then I commented the examples module and full rebuild (~50 min though 😅)

Thanks for the hint, I’ll give it a shot.
