### ISSUE TITLE
Blaze EntityViews not found on Quarkus Native build

### ISSUE THREAD

**Issue by tolsam** [Blazebit/blaze-persistence#1372]
### Description

We have a quarkus project that uses Blaze-Persistence and classes annotated with `@EntityView`. It works fine except when we perform a native build and deploy it on an OpenShift cluster.

We have add all the needed dependencies also the processor in the native profile
```
<profile>
      <id>native</id>
      <dependencies>
        <dependency>
          <groupId>com.blazebit</groupId>
          <artifactId>blaze-persistence-entity-view-processor</artifactId>
          <version>${blaze-persistence.version}</version>
          <scope>provided</scope>
        </dependency>
```

### Expected behavior

The program finds the Views on runtime and works fine.

### Actual behavior

We get the following exception
```
Caused by: java.lang.RuntimeException: Probably we did something wrong, please contact us if you see this message.
        at com.blazebit.persistence.view.impl.proxy.ProxyFactory.createProxyClass(ProxyFactory.java:627)
        at com.blazebit.persistence.view.impl.proxy.ProxyFactory.getProxy(ProxyFactory.java:263)
        at com.blazebit.persistence.view.impl.proxy.ProxyFactory.getProxy(ProxyFactory.java:180)
        at com.blazebit.persistence.view.impl.proxy.TupleConstructorReflectionInstantiator.<init>(TupleConstructorReflectionInstantiator.java:40)
        at com.blazebit.persistence.view.impl.proxy.AbstractReflectionInstantiator.createInstantiator(AbstractReflectionInstantiator.java:93)
        at com.blazebit.persistence.view.impl.objectbuilder.ViewTypeObjectBuilderTemplate.createInstantiator(ViewTypeObjectBuilderTemplate.java:394)
        at com.blazebit.persistence.view.impl.objectbuilder.ViewTypeObjectBuilderTemplate.<init>(ViewTypeObjectBuilderTemplate.java:329)
        at com.blazebit.persistence.view.impl.objectbuilder.ViewTypeObjectBuilderTemplate.applySubviewMapping(ViewTypeObjectBuilderTemplate.java:923)
        at com.blazebit.persistence.view.impl.objectbuilder.ViewTypeObjectBuilderTemplate.applyMapping(ViewTypeObjectBuilderTemplate.java:506)
        at com.blazebit.persistence.view.impl.objectbuilder.ViewTypeObjectBuilderTemplate.<init>(ViewTypeObjectBuilderTemplate.java:306)
        at com.blazebit.persistence.view.impl.objectbuilder.ViewTypeObjectBuilderTemplate.<init>(ViewTypeObjectBuilderTemplate.java:127)
        at com.blazebit.persistence.view.impl.objectbuilder.ViewTypeObjectBuilderTemplate$Key.createValue(ViewTypeObjectBuilderTemplate.java:1523)
        at com.blazebit.persistence.view.impl.EntityViewManagerImpl.getTemplate(EntityViewManagerImpl.java:1375)
        at com.blazebit.persistence.view.impl.EntityViewManagerImpl.createObjectBuilder(EntityViewManagerImpl.java:1359)
        at com.blazebit.persistence.view.impl.EntityViewManagerImpl.applyObjectBuilder(EntityViewManagerImpl.java:1325)
        at com.blazebit.persistence.view.impl.EntityViewSettingHelper.apply(EntityViewSettingHelper.java:104)
        at com.blazebit.persistence.view.impl.EntityViewManagerImpl.applySetting(EntityViewManagerImpl.java:1224)
        ...
        at java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:643)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:507)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:457)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:459)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:419)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:393)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:68)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        ... 19 more
Caused by: javassist.NotFoundException: ch.admin.blv.infofito.lexicon.language.view.DataView
        at javassist.ClassPool.get(ClassPool.java:445)
        at com.blazebit.persistence.view.impl.proxy.ProxyFactory.createProxyClass(ProxyFactory.java:391)
        ... 52 more
        ...
```

### Environment

Version:            1.6.1
JPA-Provider:      Hibernate 
DBMS:               MS SQL Server 2019
Application Server: Quarkus Native on OpenShift

**Comment by beikov** [comment]
I guess you have these dependencies also?

```
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>blaze-persistence-integration-quarkus</artifactId>
            <version>${project.version}</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>blaze-persistence-integration-hibernate-5.4</artifactId>
            <version>${project.version}</version>
            <scope>runtime</scope>
        </dependency>
```

It's odd as it seems the entity view java type is not in the native image. Can you share the type?

**Comment by tolsam** [comment]
It seems that the generated implementations i.e. DataViewImpl were not packaged into the JAR, because we added the processor in the mvn compiler plugin and it worked (the class is now found)

```<plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${compiler-plugin.version}</version>
        <configuration>
          <parameters>${maven.compiler.parameters}</parameters>
          <annotationProcessorPaths>
            <path>
              <groupId>org.projectlombok</groupId>
              <artifactId>lombok</artifactId>
              <version>${lombok.version}</version>
            </path>
            <!--must define the Lombok dependency before the one for the MapStruct processor-->
            <path>
              <groupId>org.mapstruct</groupId>
              <artifactId>mapstruct-processor</artifactId>
              <version>${mapstruct.version}</version>
            </path>
            <path>
              <groupId>com.blazebit</groupId>
              <artifactId>blaze-persistence-entity-view-processor</artifactId>
              <version>${blaze-persistence.version}</version>
            </path>
          </annotationProcessorPaths>
        </configuration>
      </plugin>```

Do we need to package the files manually or the processor in the native profile just doesn't works?

**Comment by tolsam** [comment]
We added the blaze processor in the compile plugin and the Impl classes were generated. We then started to have the same problem as in the native version initally that was solved with adding a Fetch Strategy

But we still get the same error only in the native version
```Caused by: javassist.NotFoundException: ch.admin.blv.infofito.lexicon.language.view.DataView
        at javassist.ClassPool.get(ClassPool.java:430)
        at com.blazebit.persistence.view.impl.proxy.ProxyFactory.createProxyClass(ProxyFactory.java:391)
        ... 51 more```

If you observe the `DataView` class is not found and not the `DataViewImpl`. Do you have any idea?

**Comment by tolsam** [comment]
> Not sure what you mean by adding a fetch strategy, could you elaborate this?
The following code was working without the `fetch = FetchStrategy.MULTISET` part. It wasn't working on the native build and also when we added the processor also on the compiler plugin (run quarkus through IntelliJ)
```protected KeyView (
      @Mapping(value = "data", fetch = FetchStrategy.MULTISET) Set<DataView> data,
```
> if the Quarkus extension is not enabled properly
It seems that this could be the problem
