### ISSUE TITLE
Unable to use Spring webmvc/webflux integrations in the same application

### ISSUE THREAD

**Issue by dsarlo-viso** [Blazebit/blaze-persistence#1389]
### Description

We are trying to set up updatable/createable entity views for our Spring application. When using these entity views in request bodies, Spring has no way of deserializing the json to the entity views so we need to use the spring webmvc/webflux integrations. 

When attempting to use the spring webmvc integration alone, everything works as expected for version 1.6.0. However, version 1.6.3 has an issue with our webflux endpoints (this is not a problem on 1.6.0, but we need to be on 1.6.3 in order for validation annotations to work properly).

Example of the internal server error we get on all webflux related endpoints when on version 1.6.3 (Note, these webflux endpoints return entity views)
```
org.hibernate.exception.GenericJDBCException: could not advance using next()
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
	at org.hibernate.internal.ScrollableResultsImpl.convert(ScrollableResultsImpl.java:71)
	at org.hibernate.internal.ScrollableResultsImpl.next(ScrollableResultsImpl.java:106)
	at org.hibernate.query.internal.ScrollableResultsIterator.hasNext(ScrollableResultsIterator.java:33)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1811)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
	at java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:132)
	at reactor.core.publisher.FluxStream.subscribe(FluxStream.java:71)
	at reactor.core.publisher.FluxUsing.subscribe(FluxUsing.java:102)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8185)
	at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onComplete(FluxConcatArray.java:208)
	at reactor.core.publisher.FluxConcatArray.subscribe(FluxConcatArray.java:80)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8185)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onNext(MonoFlatMapMany.java:195)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815)
	at reactor.core.publisher.MonoCompletionStage.lambda$subscribe$0(MonoCompletionStage.java:82)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705)
	at org.springframework.security.concurrent.DelegatingSecurityContextRunnable.run(DelegatingSecurityContextRunnable.java:82)
	at io.github.jhipster.async.ExceptionHandlingAsyncTaskExecutor.lambda$createWrappedRunnable$1(ExceptionHandlingAsyncTaskExecutor.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.postgresql.util.PSQLException: This ResultSet is closed.
	at org.postgresql.jdbc.PgResultSet.checkClosed(PgResultSet.java:2905)
	at org.postgresql.jdbc.PgResultSet.next(PgResultSet.java:1924)
	at com.zaxxer.hikari.pool.HikariProxyResultSet.next(HikariProxyResultSet.java)
	at org.hibernate.internal.ScrollableResultsImpl.next(ScrollableResultsImpl.java:101)
	... 26 common frames omitted
```
In an attempt to fix this issue, I also added the spring webflux integration for blaze. At this point, both dependencies are added to the project. This is the exception we see when attempting to start the application:

```
Description:

Parameter 0 of method entityViewIdAwareWebFilter in com.blazebit.persistence.spring.data.webflux.impl.BlazePersistenceWebConfiguration required a bean of type 'org.springframework.web.reactive.result.method.annotation.RequestMappingHandlerMapping' that could not be found.


Action:

Consider defining a bean of type 'org.springframework.web.reactive.result.method.annotation.RequestMappingHandlerMapping' in your configuration.
```

Finally, I wanted to see if we could get the spring webflux integration working alone. Here is the issue we get when attempting to get the webflux integration working by itself (no webmvc integration dependency)

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'keysetPageableResolver' defined in class path resource [com/blazebit/persistence/spring/data/webflux/impl/BlazePersistenceWebConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.blazebit.persistence.spring.data.webflux.impl.KeysetPageableHandlerMethodArgumentResolver]: Factory method 'keysetPageableResolver' threw exception; nested exception is java.lang.IllegalStateException: @Bean method BlazePersistenceWebConfiguration.sortResolver called as bean reference for type [com.blazebit.persistence.spring.data.webflux.impl.SortHandlerMethodArgumentResolver] but overridden by non-compatible bean instance of type [org.springframework.data.web.SortHandlerMethodArgumentResolver]. Overriding bean of same name declared in: class path resource [org/springframework/data/web/config/SpringDataWebConfiguration.class]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:486)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:769)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.blazebit.persistence.spring.data.webflux.impl.KeysetPageableHandlerMethodArgumentResolver]: Factory method 'keysetPageableResolver' threw exception; nested exception is java.lang.IllegalStateException: @Bean method BlazePersistenceWebConfiguration.sortResolver called as bean reference for type [com.blazebit.persistence.spring.data.webflux.impl.SortHandlerMethodArgumentResolver] but overridden by non-compatible bean instance of type [org.springframework.data.web.SortHandlerMethodArgumentResolver]. Overriding bean of same name declared in: class path resource [org/springframework/data/web/config/SpringDataWebConfiguration.class]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 18 common frames omitted
Caused by: java.lang.IllegalStateException: @Bean method BlazePersistenceWebConfiguration.sortResolver called as bean reference for type [com.blazebit.persistence.spring.data.webflux.impl.SortHandlerMethodArgumentResolver] but overridden by non-compatible bean instance of type [org.springframework.data.web.SortHandlerMethodArgumentResolver]. Overriding bean of same name declared in: class path resource [org/springframework/data/web/config/SpringDataWebConfiguration.class]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.resolveBeanReference(ConfigurationClassEnhancer.java:386)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:334)
	at com.blazebit.persistence.spring.data.webflux.impl.BlazePersistenceWebConfiguration$$EnhancerBySpringCGLIB$$65a6d753.sortResolver(<generated>)
	at com.blazebit.persistence.spring.data.webflux.impl.BlazePersistenceWebConfiguration.keysetPageableResolver(BlazePersistenceWebConfiguration.java:68)
	at com.blazebit.persistence.spring.data.webflux.impl.BlazePersistenceWebConfiguration$$EnhancerBySpringCGLIB$$65a6d753.CGLIB$keysetPageableResolver$2(<generated>)
	at com.blazebit.persistence.spring.data.webflux.impl.BlazePersistenceWebConfiguration$$EnhancerBySpringCGLIB$$65a6d753$$FastClassBySpringCGLIB$$68ec23ea.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at com.blazebit.persistence.spring.data.webflux.impl.BlazePersistenceWebConfiguration$$EnhancerBySpringCGLIB$$65a6d753.keysetPageableResolver(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 19 common frames omitted
```

### Expected behavior
We should be able to use both spring-webmvc and spring-webflux integrations for the same project since we do use both webmvc and webflux throughout. EntityViews should be properly deserialized when passed as request bodies on both webflux and webmvc endpoints.

### Actual behavior
Multiple outcomes noted above during troubleshooting. Unable to get spring integrations working properly with our solution.

### Steps to reproduce

A Spring project using blaze 1.6.3 that also utilizes webmvc and webflux together. I can assist in clarifying this step with additional details if needed. I believe the description covers this mostly.

### Environment

Version: 1.6.3           
JPA-Provider: Hibernate 5.4.29.Final (Spring Data JPA 2.4.4)       
DBMS: PostgreSQL 9.6              
Application Server: Spring Boot 2.4.4

**Comment by beikov** [comment]
As far as this article explains, this is not so easily possible https://stackoverflow.com/questions/53883037/can-i-use-springmvc-and-webflux-together

I tried very hard to setup a sample for this, but this is too much Spring magic for my skills. If you can provide a sample application I can look into this, but until then, you have to decide to either use WebMvc or WebFlux

**Comment by dsarlo-viso** [comment]
> org.hibernate.exception.GenericJDBCException: could not advance using next()

Take a look here:

https://github.com/dsarlo-viso/blaze-web-implementation-issues

Was unable to reproduce the issue around `org.hibernate.exception.GenericJDBCException: could not advance using next()` 

Will dig into this myself to see why this is only happening in our application and not the sample here. Thanks!

**Comment by jwgmeligmeyling** [comment]
Result set streaming was only added recently (#1344) and it could be that there is an issue still with entity views. It appears as if the underlying scrollable result is closed before the (transformed?) stream is consumed.

As a workaround you can temporarily use `getResultList().stream()`. I don't think this original issue was even related to WebMvc and Webflux interopability.

**Comment by dsarlo-viso** [comment]
[](url)> Result set streaming was only added recently (#1344) and it could be that there is an issue still with entity views. It appears as if the underlying scrollable result is closed before the (transformed?) stream is consumed. Could you perhaps put a breakpoint on ScrollableResults#close and back track what calls it? Wondering whether this could be a Hibernate or Blaze-Persistence bug.
> 
> As a workaround you can temporarily use `getResultList().stream()`. I don't think this original issue was even related to WebMvc and Webflux interopability.

Thanks for that workaround! The spring-webmvc integration by itself now works properly for us with that change. Irrelevant to the description of this issue, but this does help!

This is what the call stack looks like:

![Screen Shot 2021-11-22 at 3 03 07 PM](https://user-images.githubusercontent.com/81384153/142927689-d3f43e1b-13d7-4f75-b649-f9aae6dc38e3.png)

**Comment by jason-visotrust** [comment]
> As a workaround you can temporarily use `getResultList().stream()`. I don't think this original issue was even related to WebMvc and Webflux interopability.

I specifically built this using streaming because the result sets are large. Any idea what's breaking this in 1.6.3?

**Comment by dsarlo-viso** [comment]
Opened - https://github.com/Blazebit/blaze-persistence/issues/1393 - to continue the discussion around result set streaming

**Comment by beikov** [comment]
Does that mean, the usage of webmvc and webflux together works now, or is https://github.com/dsarlo-viso/blaze-web-implementation-issues the reproducer/example for that? If that's still an issue, we have to keep this issue open :)

**Comment by dsarlo-viso** [comment]
@beikov When using just the spring webmvc integration (which I believe is most likely what we should be doing since you can't actually take full advantage of webflux in a webmvc application), everything works as expected. Our endpoints using reactive types were failing due to the getResultStream method throwing an exception. This doesn't have anything to do with using webmvc and webflux together. There is still some bean clashing when using both integrations together, but I don't think anyone should be using both integrations given that if both webmvc and webflux are added to a project, spring will still start an mvc web server and will not need the webflux integration you provide.

Thanks again for the great support thus far!

**Comment by beikov** [comment]
>There is still some bean clashing when using both integrations together

I added a fix for that here, not sure if that helps you: https://github.com/Blazebit/blaze-persistence/pull/1391

You're welcome. Now hopefully we can figure out the streaming issue as well :)
