### ISSUE TITLE
Not compatible with current spring boot 2.5 which uses also spring data 2.5

### ISSUE THREAD

**Issue by MichaelF25** [Blazebit/blaze-persistence#1392]
### Description
Integrated blaze-persistence into my spring boot 2.5 app wich uses spring data jpa 2.5 with hibernate (versions managed by spring boot). At application startup following exception is shown and the start fails:

`org.springframework.dao.InvalidDataAccessApiUsageException: No fragment found for method public abstract java.lang.Object org.springframework.data.jpa.repository.JpaRepository.getById(java.lang.Object); nested exception is java.lang.IllegalArgumentException: No fragment found for method public abstract java.lang.Object org.springframework.data.jpa.repository.JpaRepository.getById(java.lang.Object)
	at org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:374)
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:235)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:551)
	at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)
	at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:152)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at com.blazebit.persistence.spring.data.base.repository.EntityViewAwareCrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(EntityViewAwareCrudMethodMetadataPostProcessor.java:142)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)`

### Expected behavior
Successful application start

### Actual behavior
Unrecoverable Exception which prevents application to start (see above). AFAIK the `getById()` method was added with spring data jpa 2.5.

### Steps to reproduce
Integrate blaze-persistence in existing spring boot 2.5 app and add `repositoryFactoryBeanClass = BlazePersistenceRepositoryFactoryBean.class)` to the `@EnableJpaRepositories` annotation as described in the documentation.

### Environment
Version: 1.6.3 (current stable)
JPA-Provider:       Hibernate 5.4.32.Final
DBMS:               MS SQL 2019
Application Server: Embedded Tomcat from spring boot (default)

**Comment by beikov** [comment]
Hi and thanks for the report. I'll look into this. Do you happen to know what else was added to Spring Data 2.5 or have a link to the release notes for me to go through?

**Comment by MichaelF25** [comment]
Unfortunately I have no release notes. We've just stumbled over this new method in the `JpaRepository<>` as we upgraded to Spring Boot 2.5 since we added a method with the same signature in our own `CommonRepository<>` extending `JpaRepository<>`.

**Comment by beikov** [comment]
Found it https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#new-features.2-5-0 :)

**Comment by MichaelF25** [comment]
Yeah, seems to be indeed the only (in this case breaking) change

**Comment by MichaelF25** [comment]
Wow, that was fast!
