### ISSUE TITLE
Comparison in select clause not working

### ISSUE THREAD

**Issue by mch9003** [Blazebit/blaze-persistence#1447]
### Description

Hi, I'm using searching query from some table but I get error about it.

```
com.blazebit.persistence.parser.expression.SyntaxErrorException: Could not parse expression 'sometable.somecolumn is not null', line 1:16 mismatched input 'is' expecting {<EOF>, '.', '[', '+', '-', '*', '/', '%', '||'}
        at com.blazebit.persistence.parser.expression.AbstractExpressionFactory.createExpression(AbstractExpressionFactory.java:183) ~[blaze-persistence-core-parser-1.6.6.jar:1.6.6]
        at com.blazebit.persistence.parser.expression.AbstractExpressionFactory.createSimpleExpression(AbstractExpressionFactory.java:226) ~[blaze-persistence-core-parser-1.6.6.jar:1.6.6]
        at com.blazebit.persistence.parser.expression.AbstractCachingExpressionFactory$2.get(AbstractCachingExpressionFactory.java:56) ~[blaze-persistence-core-parser-1.6.6.jar:1.6.6]
        at com.blazebit.persistence.parser.expression.AbstractCachingExpressionFactory.getOrDefault(AbstractCachingExpressionFactory.java:158) ~[blaze-persistence-core-parser-1.6.6.jar:1.6.6]
        at com.blazebit.persistence.parser.expression.AbstractCachingExpressionFactory.createSimpleExpression(AbstractCachingExpressionFactory.java:109) ~[blaze-persistence-core-parser-1.6.6.jar:1.6.6]
        at com.blazebit.persistence.impl.JpqlMacroAwareExpressionFactory.createSimpleExpression(JpqlMacroAwareExpressionFactory.java:95) ~[blaze-persistence-core-impl-1.6.6.jar:1.6.6]
        at com.blazebit.persistence.impl.AbstractCommonQueryBuilder.select(AbstractCommonQueryBuilder.java:1295) ~[blaze-persistence-core-impl-1.6.6.jar:1.6.6]        
        at com.blazebit.persistence.impl.AbstractCommonQueryBuilder.select(AbstractCommonQueryBuilder.java:1290) ~[blaze-persistence-core-impl-1.6.6.jar:1.6.6]        
        at com.blazebit.persistence.querydsl.BlazeCriteriaBuilderRenderer$SelectBuilderExpressionSetter.setExpression(BlazeCriteriaBuilderRenderer.java:755) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
        at com.blazebit.persistence.querydsl.BlazeCriteriaBuilderRenderer$SelectBuilderExpressionSetter.setExpression(BlazeCriteriaBuilderRenderer.java:749) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
        at com.blazebit.persistence.querydsl.BlazeCriteriaBuilderRenderer.setExpressionSubqueries(BlazeCriteriaBuilderRenderer.java:835) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
        at com.blazebit.persistence.querydsl.BlazeCriteriaBuilderRenderer.renderSingleSelect(BlazeCriteriaBuilderRenderer.java:667) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
        at com.blazebit.persistence.querydsl.BlazeCriteriaBuilderRenderer.access$1900(BlazeCriteriaBuilderRenderer.java:106) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
        at com.blazebit.persistence.querydsl.BlazeCriteriaBuilderRenderer$FactoryExpressionObjectBuilder.applySelects(BlazeCriteriaBuilderRenderer.java:974) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
        at com.blazebit.persistence.impl.SelectManager.selectNew(SelectManager.java:629) ~[blaze-persistence-core-impl-1.6.6.jar:1.6.6]
        at com.blazebit.persistence.impl.AbstractFullQueryBuilder.selectNew(AbstractFullQueryBuilder.java:1011) ~[blaze-persistence-core-impl-1.6.6.jar:1.6.6]
        at com.blazebit.persistence.impl.CriteriaBuilderImpl.selectNew(CriteriaBuilderImpl.java:118) ~[blaze-persistence-core-impl-1.6.6.jar:1.6.6]
        at com.blazebit.persistence.impl.CriteriaBuilderImpl.selectNew(CriteriaBuilderImpl.java:36) ~[blaze-persistence-core-impl-1.6.6.jar:1.6.6]
        at com.blazebit.persistence.querydsl.BlazeCriteriaBuilderRenderer$1.visit(BlazeCriteriaBuilderRenderer.java:268) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
        at com.querydsl.core.types.SubQueryExpressionImpl.accept(SubQueryExpressionImpl.java:57) ~[querydsl-core-5.0.0.jar:?]
        at com.querydsl.core.support.FetchableSubQueryBase.accept(FetchableSubQueryBase.java:150) ~[querydsl-core-5.0.0.jar:?]
        at com.blazebit.persistence.querydsl.BlazeCriteriaBuilderRenderer.serializeSubQuery(BlazeCriteriaBuilderRenderer.java:131) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
        at com.blazebit.persistence.querydsl.BlazeCriteriaBuilderRenderer.render(BlazeCriteriaBuilderRenderer.java:127) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
        at com.blazebit.persistence.querydsl.AbstractBlazeJPAQuery.getQueryable(AbstractBlazeJPAQuery.java:223) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
        at com.blazebit.persistence.querydsl.AbstractBlazeJPAQuery.getFullQueryBuilder(AbstractBlazeJPAQuery.java:214) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
        at com.blazebit.persistence.querydsl.AbstractBlazeJPAQuery.fetchPage(AbstractBlazeJPAQuery.java:197) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
...
```

And this is my query. BlazePersistence with QueryDsl style.

```
 blazeQueryFactory
      .select(
        new QTableDTO(Expressions.booleanTemplate("{0} is not null", Arrays.asList(sometable.somecolumn))) // same with sometable.somecolumn.isNotNull()
      )
      .from(table)
      .where(builder)
      .orderBy(orders)
      .fetch()
```

I used Identical query with querydsl but it worked well.
Another comparison using '=' was not working as well.
Any help will be appreciated.
Thanks.

### Environment

Version:            1.6.6
JPA-Provider:      Hibernate 5.6.1.Final 
DBMS:               PostgreSQL 9
Application Server: Spring boot 2.6.0

**Comment by beikov** [comment]
Hi, predicates are usually only allowed in a predicate clause like `WHERE`, `HAVING` etc. If you want a boolean expression, you currently have to use a template like `case when {0} is not null then true else false end`
