### ISSUE TITLE
CustomMultiTableBulkIdStrategy delegates depricated method to a class that does (seemingly?) not implement it anymore

### ISSUE THREAD

**Issue by tom-mayer** [Blazebit/blaze-persistence#1471]
### Description
The `prepare()` method is depricated in `MultiTableBulkIdStrategy` and has been removed from some Hibernate classes it seems.

The class `CustomMultiTableBulkIdStrategy` which implements `MultiTableBulkIdStrategy` still implements the `prepare()`. This is not directly leading to an error but the `prepare()` method gets delegated to the Hibernate class `LocalTemporaryTableBulkIdStrategy`. The `prepare()` method is implemented in the `AbstractMultiTableBulkIdStrategyImpl` but looking at the stacktrace it seems to be missing.

The stacktrace is:
```
Failed to load ApplicationContext
java.lang.IllegalStateException: Failed to load ApplicationContext
...
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is java.lang.IllegalStateException: prepare() was not implemented!
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804)
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at app//org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at app//org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at app//org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at app//org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at app//org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1154)
	at app//org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:908)
	at app//org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at app//org.springframework.boot.SpringApplication.refresh(SpringApplication.java:740)
	at app//org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:415)
	at app//org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at app//org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:136)
	at app//org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
	at app//org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)
	... 59 more

```

This leads to the `entitiyManager` Bean not being able to be initialized and Spring Boot crashing on boot. 

### Steps to reproduce
Not sure if this issue is specific to our code or how we use BP. But it seems like a general issue.

### Environment
Spring Boot: 2.6.5
Version: 1.6.6
JPA-Provider: Hibernate 5.6.7.Final

**Comment by beikov** [comment]
You will have to upgrade to the hibernate-5.6 integration to resolve this. Also see https://github.com/Blazebit/blaze-persistence/issues/1433

**Comment by tom-mayer** [comment]
Hey thanks for answering,... I just saw it and wanted to close the issue, we were still at 5.4. Didn't see that.

**Comment by beikov** [comment]
No worries :)
