### ISSUE TITLE
Set operation of multiple BlazeJPAQuery fails during execution

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#1516]
### Description

Creating a union of multiple BlazeJPAQuery and executing that doesn't work.

### Expected behavior

Should produce a result

### Actual behavior

```
java.lang.IllegalStateException: Modifications to a query after connecting with a set operation is not allowed!
	at com.blazebit.persistence.impl.AbstractCommonQueryBuilder.prepareForModification(AbstractCommonQueryBuilder.java:3526) ~[blaze-persistence-core-impl-1.6.6.jar:1.6.6]
	at com.blazebit.persistence.impl.AbstractFullQueryBuilder.prepareForModification(AbstractFullQueryBuilder.java:134) ~[blaze-persistence-core-impl-1.6.6.jar:1.6.6]
	at com.blazebit.persistence.impl.CriteriaBuilderImpl.prepareForModification(CriteriaBuilderImpl.java:48) ~[blaze-persistence-core-impl-1.6.6.jar:1.6.6]
	at com.blazebit.persistence.impl.AbstractCommonQueryBuilder.with(AbstractCommonQueryBuilder.java:531) ~[blaze-persistence-core-impl-1.6.6.jar:1.6.6]
	at com.blazebit.persistence.impl.AbstractCommonQueryBuilder.with(AbstractCommonQueryBuilder.java:518) ~[blaze-persistence-core-impl-1.6.6.jar:1.6.6]
	at com.blazebit.persistence.impl.AbstractCommonQueryBuilder.with(AbstractCommonQueryBuilder.java:508) ~[blaze-persistence-core-impl-1.6.6.jar:1.6.6]
	at com.blazebit.persistence.querydsl.BlazeCriteriaBuilderRenderer$JPQLNextExpressionSerializer.visitOperation(BlazeCriteriaBuilderRenderer.java:1106) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
	at com.querydsl.core.support.SerializerBase.visit(SerializerBase.java:273) ~[querydsl-core-5.0.0.jar:na]
	at com.blazebit.persistence.querydsl.BlazeCriteriaBuilderRenderer$JPQLNextExpressionSerializer.visit(BlazeCriteriaBuilderRenderer.java:1160) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
	at com.blazebit.persistence.querydsl.BlazeCriteriaBuilderRenderer$JPQLNextExpressionSerializer.visit(BlazeCriteriaBuilderRenderer.java:1022) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
	at com.querydsl.core.types.OperationImpl.accept(OperationImpl.java:88) ~[querydsl-core-5.0.0.jar:na]
	at com.blazebit.persistence.querydsl.BlazeCriteriaBuilderRenderer.renderCTEs(BlazeCriteriaBuilderRenderer.java:368) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
	at com.blazebit.persistence.querydsl.BlazeCriteriaBuilderRenderer.access$400(BlazeCriteriaBuilderRenderer.java:106) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
	at com.blazebit.persistence.querydsl.BlazeCriteriaBuilderRenderer$1.visit(BlazeCriteriaBuilderRenderer.java:255) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
	at com.querydsl.core.types.SubQueryExpressionImpl.accept(SubQueryExpressionImpl.java:57) ~[querydsl-core-5.0.0.jar:na]
	at com.blazebit.persistence.querydsl.BlazeCriteriaBuilderRenderer.serializeSubQuery(BlazeCriteriaBuilderRenderer.java:131) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
	at com.blazebit.persistence.querydsl.BlazeCriteriaBuilderRenderer.setExpressionSubqueries(BlazeCriteriaBuilderRenderer.java:841) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
	at com.blazebit.persistence.querydsl.BlazeCriteriaBuilderRenderer.renderWhere(BlazeCriteriaBuilderRenderer.java:431) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
	at com.blazebit.persistence.querydsl.BlazeCriteriaBuilderRenderer.access$800(BlazeCriteriaBuilderRenderer.java:106) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
	at com.blazebit.persistence.querydsl.BlazeCriteriaBuilderRenderer$1.visit(BlazeCriteriaBuilderRenderer.java:260) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
	at com.querydsl.core.types.SubQueryExpressionImpl.accept(SubQueryExpressionImpl.java:57) ~[querydsl-core-5.0.0.jar:na]
	at com.querydsl.core.support.FetchableSubQueryBase.accept(FetchableSubQueryBase.java:150) ~[querydsl-core-5.0.0.jar:na]
	at com.blazebit.persistence.querydsl.BlazeCriteriaBuilderRenderer$1.visit(BlazeCriteriaBuilderRenderer.java:230) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
	at com.querydsl.core.types.OperationImpl.accept(OperationImpl.java:88) ~[querydsl-core-5.0.0.jar:na]
	at com.blazebit.persistence.querydsl.BlazeCriteriaBuilderRenderer$1.visit(BlazeCriteriaBuilderRenderer.java:172) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
	at com.querydsl.core.types.OperationImpl.accept(OperationImpl.java:88) ~[querydsl-core-5.0.0.jar:na]
	at com.blazebit.persistence.querydsl.BlazeCriteriaBuilderRenderer$1.visit(BlazeCriteriaBuilderRenderer.java:252) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
	at com.querydsl.core.types.SubQueryExpressionImpl.accept(SubQueryExpressionImpl.java:57) ~[querydsl-core-5.0.0.jar:na]
	at com.querydsl.core.support.FetchableSubQueryBase.accept(FetchableSubQueryBase.java:150) ~[querydsl-core-5.0.0.jar:na]
	at com.blazebit.persistence.querydsl.BlazeCriteriaBuilderRenderer.serializeSubQuery(BlazeCriteriaBuilderRenderer.java:131) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
	at com.blazebit.persistence.querydsl.BlazeCriteriaBuilderRenderer.render(BlazeCriteriaBuilderRenderer.java:127) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
	at com.blazebit.persistence.querydsl.AbstractBlazeJPAQuery.getQueryable(AbstractBlazeJPAQuery.java:223) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
	at com.blazebit.persistence.querydsl.AbstractBlazeJPAQuery.createQuery(AbstractBlazeJPAQuery.java:174) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
	at com.blazebit.persistence.querydsl.AbstractBlazeJPAQuery.createQuery(AbstractBlazeJPAQuery.java:165) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
	at com.querydsl.jpa.impl.AbstractJPAQuery.fetch(AbstractJPAQuery.java:242) ~[querydsl-jpa-5.0.0.jar:na]
	at com.blazebit.persistence.querydsl.SetExpressionImpl.fetch(SetExpressionImpl.java:61) ~[blaze-persistence-integration-querydsl-expressions-1.6.6.jar:1.6.6]
```

### Steps to reproduce

Use a query like this `new BlazeJPAQuery<Tuple>(criteriaBuilderFactory).union(mainSelect1, mainSelect2, mainSelect3);` where the individual selects are simple queries.

### Environment

Version:            1.6.6
JPA-Provider:       Hibernate
DBMS:               -
Application Server: -

**Comment by jwgmeligmeyling** [comment]
Although a reproducer was not found, this issue is _likely_ to be caused by the fact that CTE rendering happened whenever we stumbled upon a CTE. CTE's should be rendered first thing before starting set builders.
