### ISSUE TITLE
Cascading DELETE on an OneToOne relation leads to NPE

### ISSUE THREAD

**Issue by EugenMayer** [Blazebit/blaze-persistence#1520]
Following up on https://github.com/Blazebit/blaze-persistence/issues/1306 with a reproduction that we have in our code. We yet do not  know what it would take to have a common reproduction. Maybe an on-spot debug session would help identify this?

### Description

When cascading deletes in OneToOne mappings, we get an exception when running the query:
```
java.lang.NullPointerException: Cannot invoke "com.blazebit.persistence.view.spi.type.EntityViewProxy.$$_getEntityViewClass()" because the return value of "com.blazebit.persistence.view.impl.update.DefaultUpdateContext$ViewCacheEntry.access$100(com.blazebit.persistence.view.impl.update.DefaultUpdateContext$ViewCacheEntry)" is null

	at com.blazebit.persistence.view.impl.update.DefaultUpdateContext.getEntityView(DefaultUpdateContext.java:158)
	at com.blazebit.persistence.view.impl.update.DefaultUpdateContext.getEntityView(DefaultUpdateContext.java:128)
	at com.blazebit.persistence.view.impl.update.Listeners.invokePostRemove(Listeners.java:180)
	at com.blazebit.persistence.view.impl.update.ListenerManager.invokePostRemove(ListenerManager.java:351)
	at com.blazebit.persistence.view.impl.update.DefaultUpdateContext.invokePostRemove(DefaultUpdateContext.java:287)
	at com.blazebit.persistence.view.impl.update.flush.UnmappedBasicAttributeCascadeDeleter.removeWithoutPreCascadeDelete(UnmappedBasicAttributeCascadeDeleter.java:269)
	at com.blazebit.persistence.view.impl.update.flush.UnmappedBasicAttributeCascadeDeleter.removeById(UnmappedBasicAttributeCascadeDeleter.java:100)
	at com.blazebit.persistence.view.impl.update.flush.CompositeAttributeFlusher.remove(CompositeAttributeFlusher.java:1088)
	at com.blazebit.persistence.view.impl.update.flush.CompositeAttributeFlusher.remove(CompositeAttributeFlusher.java:938)
	at com.blazebit.persistence.view.impl.update.EntityViewUpdaterImpl.remove(EntityViewUpdaterImpl.java:745)
	at com.blazebit.persistence.view.impl.EntityViewManagerImpl.remove(EntityViewManagerImpl.java:1135)
	at com.blazebit.persistence.view.impl.EntityViewManagerImpl.remove(EntityViewManagerImpl.java:1125)
	at de.kontextwork.dw.platform.commons.jpa.sql.blazepersistence.RegularEntityViewRepository.delete(RegularEntityViewRepository.java:261)
	at de.kontextwork.dw.platform.commons.jpa.sql.blazepersistence.RegularEntityViewRepository$$FastClassBySpringCGLIB$$8b139629.invoke(<generated>)
```

While having this on our entity User

```
  @OneToOne(fetch = FetchType.LAZY, cascade = CascadeType.REMOVE)
  @JoinColumn(name = "picture", referencedColumnName = "fid", columnDefinition = "INT(10) UNSIGNED")
  private UploadedFile picture;
```

It seems to happen when we try to Delete the entity User with a profile picture that just has been created in the same tx (test scope)

### Expected behavior
It should work without issues

### Actual behavior
Throws an NPE

### Steps to reproduce
not sure yet

- onetoone relation
- create and entity including that onetoone relation, including the relation in one test, then delete it

### Environment
 Version:            1.6.6
JPA-Provider:       Hibernate 5.6.9.Final	
DBMS:             MariaDb 10.3

Version:            
JPA-Provider:       
DBMS:               
Application Server:

**Comment by EugenMayer** [comment]
As an update, i could isolate that this issue most probably is related to only OneToOne relations, which define a joinColumn. Using a PrimaryKeyColumn relation does work with cascade - so not all OneToOne relations are affected by this

**Comment by EugenMayer** [comment]
@beikov this one is related to #1456 but it is not entirely fixed yet. With the fix of #1456 this one becomes an issue in regard on how the relation is mapped

```
java.lang.IllegalArgumentException: Attribute 'uploadedFile' not found on type 'UploadedFile'

	at com.blazebit.persistence.parser.PathTargetResolvingExpressionVisitor.visit(PathTargetResolvingExpressionVisitor.java:244)
	at com.blazebit.persistence.parser.expression.PropertyExpression.accept(PropertyExpression.java:41)
	at com.blazebit.persistence.parser.PathTargetResolvingExpressionVisitor.visit(PathTargetResolvingExpressionVisitor.java:337)
	at com.blazebit.persistence.parser.expression.PathExpression.accept(PathExpression.java:85)
	at com.blazebit.persistence.impl.JpaUtils.getAttributeForJoining(JpaUtils.java:476)
	at com.blazebit.persistence.impl.JoinManager.createOrUpdateNode(JoinManager.java:3632)
	at com.blazebit.persistence.impl.JoinManager.implicitJoinSingle(JoinManager.java:3556)
	at com.blazebit.persistence.impl.JoinManager.implicitJoin(JoinManager.java:3472)
	at com.blazebit.persistence.impl.JoinManager.implicitJoin(JoinManager.java:3298)
	at com.blazebit.persistence.impl.JoinManager.implicitJoin(JoinManager.java:2687)
	at com.blazebit.persistence.impl.JoinVisitor.visit(JoinVisitor.java:268)
	at com.blazebit.persistence.impl.JoinVisitor.visit(JoinVisitor.java:219)
	at com.blazebit.persistence.parser.expression.PathExpression.accept(PathExpression.java:85)
	at com.blazebit.persistence.impl.JoinVisitor.removeAssociationIdIfPossible(JoinVisitor.java:444)
	at com.blazebit.persistence.impl.JoinVisitor.visit(JoinVisitor.java:376)
	at com.blazebit.persistence.parser.predicate.EqPredicate.accept(EqPredicate.java:57)
	at com.blazebit.persistence.parser.expression.VisitorAdapter.visit(VisitorAdapter.java:230)
	at com.blazebit.persistence.parser.predicate.CompoundPredicate.accept(CompoundPredicate.java:77)
	at com.blazebit.persistence.impl.PredicateManager.acceptVisitor(PredicateManager.java:249)
	at com.blazebit.persistence.impl.AbstractCommonQueryBuilder.applyImplicitJoins(AbstractCommonQueryBuilder.java:2692)
	at com.blazebit.persistence.impl.AbstractCommonQueryBuilder.prepareAndCheck(AbstractCommonQueryBuilder.java:3662)
	at com.blazebit.persistence.impl.AbstractCommonQueryBuilder.getBaseQueryStringWithCheck(AbstractCommonQueryBuilder.java:2831)
	at com.blazebit.persistence.impl.AbstractCommonQueryBuilder.getTypedQuery(AbstractCommonQueryBuilder.java:2846)
	at com.blazebit.persistence.impl.AbstractQueryBuilder.getQuery(AbstractQueryBuilder.java:53)
	at com.blazebit.persistence.impl.AbstractQueryBuilder.getResultList(AbstractQueryBuilder.java:58)
	at com.blazebit.persistence.view.impl.update.flush.UnmappedBasicAttributeCascadeDeleter.removeByOwnerId(UnmappedBasicAttributeCascadeDeleter.java:133)
	at com.blazebit.persistence.view.impl.update.flush.UnmappedCollectionAttributeCascadeDeleter.removeByOwnerId(UnmappedCollectionAttributeCascadeDeleter.java:125)
	at com.blazebit.persistence.view.impl.update.flush.UnmappedBasicAttributeCascadeDeleter.removeById(UnmappedBasicAttributeCascadeDeleter.java:98)
	at com.blazebit.persistence.view.impl.update.flush.CompositeAttributeFlusher.remove(CompositeAttributeFlusher.java:1088)
	at com.blazebit.persistence.view.impl.update.flush.CompositeAttributeFlusher.remove(CompositeAttributeFlusher.java:938)
	at com.blazebit.persistence.view.impl.update.EntityViewUpdaterImpl.remove(EntityViewUpdaterImpl.java:745)
	at com.blazebit.persistence.view.impl.EntityViewManagerImpl.remove(EntityViewManagerImpl.java:1135)
	at com.blazebit.persistence.view.impl.EntityViewManagerImpl.remove(EntityViewManagerImpl.java:1125)

```

which should be related to

```jjava
  /**
   * Optional relation, if this is a {@link AttachmentRevision}
   */
  @OneToMany(mappedBy = "uploadedFile", fetch = FetchType.LAZY, cascade = CascadeType.REMOVE)
  private Set<PageRevisionUploadedFileRelation> pageRevisionUploadedFileRelations;

  @OneToOne(fetch = FetchType.LAZY, cascade = CascadeType.REMOVE)
  @JoinColumn(name = "picture", referencedColumnName = "fid", columnDefinition = "INT(10) UNSIGNED")
  private UploadedFile picture;
```

while the other side is mapped via


```jjava
  /**
   * Optional relation, if this is a profile picture  of an {@link User}
   */
  @OneToOne(mappedBy = "picture", fetch = FetchType.LAZY)
  private User pictureOfUser;
```

This relation does not cause any issues on non-delete cases in general. Not sure what details i could add here

**Comment by beikov** [comment]
Please also post the `PageRevisionUploadedFileRelation` entity

**Comment by EugenMayer** [comment]
@beikov updated the post above, added `PageRevisionUploadedFileRelation` and `PageRevisionUploadedFileRelationId`

**Comment by beikov** [comment]
Please also post what entity view you are using for the `EntityViewManager.remove()` call.

**Comment by EugenMayer** [comment]
It's the smallest view (idView)

```java
repository.delete(idView.getId(), UserIdView.class);
.....
    flushClearCache();
    entityViewManager.remove(entityManager, idViewClass, id);
```

```java
public interface UserIdView extends SubjectIdView
{
  /**
   * @see User#getUid()
   */
  @AttributeFilter(value = EqualFilter.class)
  Long getUid();

  void setUid(Long uid);
}
```

```java
public interface SubjectIdView extends LongIdView
{
}
```

```java
public interface LongIdView extends Serializable
{
  @IdMapping
  Long getId();
}
```
