### ISSUE TITLE
Optionally generate also Kotlin data class implementations of the EntityViews

### ISSUE THREAD

**Issue by david-kubecka** [Blazebit/blaze-persistence#1571]
Although even currently the generated java classes have the full-arg constructor, data classes still bring additional benefits:
- `copy` method
- default property values (could be generated from default view interface methods if present)

Moreover, data classes already have suitable equals/hashCode, so the code should be simpler to generate.

**Comment by beikov** [comment]
> copy method

You can copy entity views with `EntityViewManager#convert` i.e. `evm.convert(source, source.getClass())`. In addition to that, you can also transform a subset into another entity view and also specify how updatable entity views should be treated. It's pretty flexible and IMO not that worse from a code POV. To improve the code further, I think you will like this proposal here: https://github.com/Blazebit/blaze-persistence/issues/989

>default property values (could be generated from default view interface methods if present)

Could you elaborate a bit on what you are imagining here?

>Moreover, data classes already have suitable equals/hashCode, so the code should be simpler to generate.

The `equals/hashCode` implementations probably consider all fields, which is not really suitable. Also, generation of such implementation classes is not that easy, especially when considering that updatable views do inline dirty tracking. If you have any ideas for improving the generated Java code for interop with Kotlin, I'm open to that, but unless someone steps up to do the work and maintenance, I won't consider adding a new code generator, as it's too much work, especially because of the planned changes that are necessary to support JAXB and other libraries.

**Comment by david-kubecka** [comment]
> Could you elaborate a bit on what you are imagining here?

I thought something like this would be nice:
```
// input view
interface TransactionTagView {
    @get:IdMapping
    val id: Long
    val name: String?
        get() = "default"
}

// generated data class
data class TransactionTagViewImpl(
    override val id: Long,
    override val name: String? = "default",
) : TransactionTagView
```
Since Java doesn't have default parameters, that's only possible with Kotlin data classes.

I will first study the options you suggested, though, and hopefully will realize that they are usable after all.

**Comment by beikov** [comment]
To initialize mutable state of a creatable entity view, we usually suggest users to add a `@PostCreate` callback method i.e. 

```
@CreatableEntityView
@EntityView(TransactionTag.class)
interface TransactionTagView {
    @IdMapping
    Long getId();
    String getName();
    void setName(String name);

    @PostCreate
    default void init() {
        setName( "default" );
    }
}
```

By the way, note that you don't have to use interfaces for read-only entity views. You should be able to use data classes directly if you want to be in full control.

```
@EntityView(TransactionTag.class)
data class TransactionTagView {
    @get:IdMapping
    val id: Long
    val name: String?
        get() = "default"
}
```

**Comment by david-kubecka** [comment]
Well, I thought that data classes are out of the game because they are final by definition. Still, I gave it a try but got an error which I didn't pursue further given my low confidence that they could work. Given the fact that you suggest that, though I think I will at least post here the error I got when processing following view at the startup:
```
@EntityView(TransactionTag::class)
data class TransactionTagView(
    @get:IdMapping
    val id: Long,
    val name: String,
    val colorIndex: Int,
)
```
Relevant part of the stacktrace:
```
Could not determine the attribute for the parameter at index 1 of the canonical constructor: public com.vacuumlabs.robo.backend.views.TransactionTagView(long,java.lang.String,int)
	at com.blazebit.persistence.view.impl.EntityViewManagerImpl.<init>(EntityViewManagerImpl.java:285)
	at com.blazebit.persistence.view.impl.EntityViewConfigurationImpl.createEntityViewManager(EntityViewConfigurationImpl.java:206)
```

**Comment by beikov** [comment]
>Well, I thought that data classes are out of the game because they are final by definition.

The are, but that's no issue for entity views. It's just an issue for updatable/creatable entity views, because these types must implement change tracking, which you probably won't do by yourself :)

>Relevant part of the stacktrace:

Interesting. Could you please share the class file of this thing. I don't use Kotlin and don't really want to install the whole toolchain etc. I guess that the byte code analysis simply fails for the bytecode shape generated by Kotlin, but that is certainly fixable.

**Comment by david-kubecka** [comment]
Here's the classfile of `TransactionTagView`: [TransactionTagView.class.gz](https://github.com/Blazebit/blaze-persistence/files/9807558/TransactionTagView.class.gz)

**Comment by beikov** [comment]
Ok, I found the bug. Thanks for the reproducer. Here is the issue you can track: https://github.com/Blazebit/blaze-persistence/issues/1575

**Comment by david-kubecka** [comment]
Thanks! What can I expect once #1575 is fixed? That I could use data classes (possibly nested) for simple immutable entity views? Any ETA for the fix?
