### ISSUE TITLE
Hibernate 6 NULLIF throws exceptions

### ISSUE THREAD

**Issue by EugenMayer** [Blazebit/blaze-persistence#1700]
Using some mapping like

```
  @Mapping("COALESCE(NULLIF(CONCAT(firstName, ' ', lastName),''), userName)")
  String getName();
```

an exception is thrown when used with hibernate 6 (hibernate 5 is working)
```
org.hibernate.QueryException: Function nullif() has 2 parameters, but 1 arguments given
	at org.hibernate.query.sqm.produce.function.StandardArgumentsValidators$4.validate(StandardArgumentsValidators.java:107)
	at org.hibernate.query.sqm.function.AbstractSqmFunctionDescriptor.generateSqmExpression(AbstractSqmFunctionDescriptor.java:104)
	at com.blazebit.persistence.integration.hibernate.base.function.HibernateSqmFunctionDescriptorAdapter.getReturnType(HibernateSqmFunctionDescriptorAdapter.java:96)
```

**Comment by jwgmeligmeyling** [comment]
Is this a Hibernate 6 issue or BP?

**Comment by beikov** [comment]
BP issue
