### ISSUE TITLE
[Kotlin] PostCreate not working on kotlin interfaces

### ISSUE THREAD

**Issue by EugenMayer** [Blazebit/blaze-persistence#1703]
```kotlin
@EntityView(Log::class)
@CreatableEntityView
interface LogCreateView : LogIdView {
    @PostCreate
    fun init() {
        created = LocalDateTime.now()
    }

    var created: LocalDateTime
    var message: String
    var severity: LogSeverity
    var component: LogComponent
}
```

Doing that, get an validation error

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.blazebit.persistence.view.EntityViewManager]: Factory method 'entityViewManager' threw exception; nested exception is java.lang.IllegalArgumentException: There are error(s) in entity views!
The given method 'pre_init' from the entity view 'de.kontextwork.dw.platform.feature.log.model.view.LogCreateView' is no bean style getter or setter!
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 77 more
Caused by: java.lang.IllegalArgumentException: There are error(s) in entity views!
The given method 'pre_init' from the entity view 'de.kontextwork.dw.platform.feature.log.model.view.LogCreateView' is no bean style getter or setter!
	at com.blazebit.persistence.view.impl.EntityViewManagerImpl.<init>(EntityViewManagerImpl.java:285)
	at com.blazebit.persistence.view.impl.EntityViewConfigurationImpl.createEntityViewManager(EntityViewConfigurationImpl.java:206)
	at
```

**Comment by EugenMayer** [comment]
Thank you, so in the end, it just needs to be an abstract class

```
@EntityView(CustomerLog::class)
@CreatableEntityView
abstract class CustomerLogCreateView : CustomerLogIdView {
    @PostCreate
    fun init() {
        created = LocalDateTime.now()
    }

    abstract fun setId(id: Long?)
    abstract var created: LocalDateTime?
    abstract var message: String
    abstract var severity: LogSeverity
    abstract var component: LogComponent
}
```

Closing this issue - maybe helpful to somebody later on

**Comment by EugenMayer** [comment]
Alternative is to use

`-Xjvm-default all` as by https://kotlinlang.org/docs/java-to-kotlin-interop.html#default-methods-in-interfaces

So with gradle we have

```groovy
compileKotlin {
    compilerOptions {
        freeCompilerArgs = [ "-Xjvm-default=all"]
    }
}

compileTestKotlin {
    compilerOptions {
        freeCompilerArgs = [ "-Xjvm-default=all"]
    }
}
```

and 

```kotlin
@EntityView(CustomerLog::class)
@CreatableEntityView
interface CustomerLogCreateView : CustomerLogIdView {
    @PostCreate
    fun init() {
        created = LocalDateTime.now()
    }

    fun setId(id: Long?)
    var created: LocalDateTime?
    var message: String
    var severity: LogSeverity
    var component: LogComponent
}
```

**Comment by EugenMayer** [comment]
@beikov as with the 'default impl interop' in #1702 this might be something for the BP specific 'kotlin FAQ' or docs. Maybe you want to label this kotlin.

I think at some point it can be handy to have something like 'BP with Kotlin' FAQ for the most common issues.
