### ISSUE TITLE
java.lang.StringBuilder org.hibernate.sql.ast.spi.AbstractSqlAstTranslator.getSqlBuffer()

### ISSUE THREAD

**Issue by GuillaumeVT** [Blazebit/blaze-persistence#1750]
Hello there!

I'm using Blaze Persistence and QueryDSL together on a project.

I was waiting for the release of the 1.6.9 version of BP adding the support for Hibernate 6.2

Here is my env:
- Spring Boot 3.1.0
- Hibernate 6.2.2.FINAL (packaged with SB 3.1.0)
- Blaze Persistance 1.6.9
- QueryDSL 5.0.0

Here is a sample of my build.gradle:

```groovy
    implementation group: 'com.querydsl', name: 'querydsl-jpa', version: "${querydsl_version}", classifier: 'jakarta'
    implementation group: 'com.querydsl', name: 'querydsl-apt', version: "${querydsl_version}", classifier: 'jakarta'
    annotationProcessor group: 'com.querydsl', name: 'querydsl-apt', version: "${querydsl_version}", classifier: 'jakarta'
    implementation group: 'com.blazebit', name: 'blaze-persistence-integration-hibernate-6.2', version: "${blaze_version}"
    runtimeOnly group: 'com.blazebit', name: 'blaze-persistence-core-impl-jakarta', version: "${blaze_version}"
    implementation group: 'com.blazebit', name: 'blaze-persistence-integration-querydsl-expressions-jakarta', version: "${blaze_version}"
```

Browsing the decompiled classes, I can see `getSqlBuffer` is indeed missing when used in `HibernateJpqlFunctionAdapter` and the `AbstractSqlAstTranslator` instance is being picked up from Hibernate Core 6.2.2.FINAL:

![image](https://github.com/Blazebit/blaze-persistence/assets/31916395/60f4ca28-228f-4fd7-bd1b-a215b51b2fa6)

Here is the full callstack:
```
'java.lang.StringBuilder org.hibernate.sql.ast.spi.AbstractSqlAstTranslator.getSqlBuffer()'
java.lang.NoSuchMethodError: 'java.lang.StringBuilder org.hibernate.sql.ast.spi.AbstractSqlAstTranslator.getSqlBuffer()'
	at com.blazebit.persistence.integration.hibernate.base.function.HibernateJpqlFunctionAdapter.render(HibernateJpqlFunctionAdapter.java:139)
	at com.blazebit.persistence.integration.hibernate.base.function.HibernateJpqlFunctionAdapter.render(HibernateJpqlFunctionAdapter.java:133)
	at org.hibernate.query.sqm.function.AbstractSqmSelfRenderingFunctionDescriptor.lambda$generateSqmFunctionExpression$0(AbstractSqmSelfRenderingFunctionDescriptor.java:90)
	at org.hibernate.query.sqm.function.SelfRenderingFunctionSqlAstExpression.renderToSql(SelfRenderingFunctionSqlAstExpression.java:139)
	at org.hibernate.sql.ast.spi.AbstractSqlAstTranslator.visitSelfRenderingExpression(AbstractSqlAstTranslator.java:6625)
	at org.hibernate.sql.ast.tree.expression.SelfRenderingExpression.accept(SelfRenderingExpression.java:20)
	at org.hibernate.sql.ast.spi.AbstractSqlAstTranslator.visitNullnessPredicate(AbstractSqlAstTranslator.java:7322)
	at org.hibernate.sql.ast.tree.predicate.NullnessPredicate.accept(NullnessPredicate.java:38)
	at org.hibernate.sql.ast.spi.AbstractSqlAstTranslator.visitJunctionPredicate(AbstractSqlAstTranslator.java:7151)
	at org.hibernate.sql.ast.spi.AbstractSqlAstTranslator.visitJunction(AbstractSqlAstTranslator.java:7129)
	at org.hibernate.sql.ast.tree.predicate.Junction.accept(Junction.java:76)
	at org.hibernate.sql.ast.spi.AbstractSqlAstTranslator.visitGroupedPredicate(AbstractSqlAstTranslator.java:6745)
	at org.hibernate.sql.ast.tree.predicate.GroupedPredicate.accept(GroupedPredicate.java:33)
	at org.hibernate.sql.ast.spi.AbstractSqlAstTranslator.renderTableGroup(AbstractSqlAstTranslator.java:5206)
	at org.hibernate.sql.ast.spi.AbstractSqlAstTranslator.renderTableGroupJoin(AbstractSqlAstTranslator.java:5577)
	at org.hibernate.sql.ast.spi.AbstractSqlAstTranslator.processTableGroupJoin(AbstractSqlAstTranslator.java:5542)
	at org.hibernate.sql.ast.spi.AbstractSqlAstTranslator.lambda$processTableGroupJoins$7(AbstractSqlAstTranslator.java:5522)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.hibernate.sql.ast.tree.from.AbstractTableGroup.visitTableGroupJoins(AbstractTableGroup.java:150)
	at org.hibernate.sql.ast.spi.AbstractSqlAstTranslator.processTableGroupJoins(AbstractSqlAstTranslator.java:5522)
	at org.hibernate.sql.ast.spi.AbstractSqlAstTranslator.renderRootTableGroup(AbstractSqlAstTranslator.java:5152)
	at org.hibernate.sql.ast.spi.AbstractSqlAstTranslator.renderFromClauseRoot(AbstractSqlAstTranslator.java:5133)
	at org.hibernate.sql.ast.spi.AbstractSqlAstTranslator.visitFromClause(AbstractSqlAstTranslator.java:5113)
	at org.hibernate.sql.ast.spi.AbstractSqlAstTranslator.visitQuerySpec(AbstractSqlAstTranslator.java:3010)
	at org.hibernate.dialect.MySQLSqlAstTranslator.visitQuerySpec(MySQLSqlAstTranslator.java:135)
	at org.hibernate.sql.ast.tree.select.QuerySpec.accept(QuerySpec.java:119)
	at org.hibernate.sql.ast.spi.AbstractSqlAstTranslator.visitSelectStatement(AbstractSqlAstTranslator.java:969)
	at org.hibernate.sql.ast.spi.AbstractSqlAstTranslator.translateSelect(AbstractSqlAstTranslator.java:832)
	at org.hibernate.sql.ast.spi.AbstractSqlAstTranslator.translate(AbstractSqlAstTranslator.java:782)
	at com.blazebit.persistence.integration.hibernate.base.HibernateExtendedQuerySupport.getJdbcOperation(HibernateExtendedQuerySupport.java:1274)
	at com.blazebit.persistence.integration.hibernate.base.HibernateExtendedQuerySupport.getSqlFromInfo(HibernateExtendedQuerySupport.java:293)
	at com.blazebit.persistence.impl.AbstractCommonQueryBuilder.collectEntityFunctionNodes(AbstractCommonQueryBuilder.java:3142)
	at com.blazebit.persistence.impl.AbstractCommonQueryBuilder.collectEntityFunctionNodes(AbstractCommonQueryBuilder.java:2975)
	at com.blazebit.persistence.impl.AbstractCommonQueryBuilder.collectEntityFunctionNodes(AbstractCommonQueryBuilder.java:2958)
	at com.blazebit.persistence.impl.AbstractCommonQueryBuilder.getEntityFunctionNodes(AbstractCommonQueryBuilder.java:2947)
	at com.blazebit.persistence.impl.AbstractCTECriteriaBuilder.getQuery(AbstractCTECriteriaBuilder.java:134)
	at com.blazebit.persistence.impl.AbstractCTECriteriaBuilder.getQuery(AbstractCTECriteriaBuilder.java:104)
	at com.blazebit.persistence.impl.AbstractCommonQueryBuilder.collectEntityFunctionNodes(AbstractCommonQueryBuilder.java:3138)
	at com.blazebit.persistence.impl.AbstractCommonQueryBuilder.collectEntityFunctionNodes(AbstractCommonQueryBuilder.java:2975)
	at com.blazebit.persistence.impl.AbstractCommonQueryBuilder.collectEntityFunctionNodes(AbstractCommonQueryBuilder.java:2958)
	at com.blazebit.persistence.impl.AbstractCommonQueryBuilder.getEntityFunctionNodes(AbstractCommonQueryBuilder.java:2947)
	at com.blazebit.persistence.impl.AbstractCommonQueryBuilder.getTypedQuery(AbstractCommonQueryBuilder.java:2895)
	at com.blazebit.persistence.impl.AbstractQueryBuilder.getQuery(AbstractQueryBuilder.java:53)
	at com.blazebit.persistence.querydsl.AbstractBlazeJPAQuery.createQuery(AbstractBlazeJPAQuery.java:177)
	at com.blazebit.persistence.querydsl.AbstractBlazeJPAQuery.fetchOne(AbstractBlazeJPAQuery.java:323)
	at com.querydsl.core.support.FetchableQueryBase.fetchFirst(FetchableQueryBase.java:51)

```

Could you advise if I did something wrong with my dependencies?
Let me know if there is anything else that I can provide.

**Comment by jwgmeligmeyling** [comment]
According to the release notes you have to update Hibernate to 6.2.5 minimally.

**Comment by GuillaumeVT** [comment]
Thank you, this indeed solved my issue.

For anyone who is interested though, bumping hibernate core to 6.2.5.Final in SB 3.1.0 with Blaze 1.6.9 doesn't work currently.
I will have to wait for a later release of SB compatible with this version of hibernate.

**Comment by GuillaumeVT** [comment]
Working fantastically with SB 3.1.1 now which ships with Hibernate to 6.2.5
