### ISSUE TITLE
Using an IN clause in SELECT statement throws error

### ISSUE THREAD

**Issue by ctobe-zen** [Blazebit/blaze-persistence#1760]
## Description
When using an IN clause in a SELECT statement to get a boolean value, the following error is thrown:

```
com.blazebit.persistence.parser.expression.SyntaxErrorException: Could not parse expression 'userRoleEntity.role in :param_3', line 1:20 mismatched input 'in' expecting {<EOF>, '.', '[', '+', '-', '*', '/', '%', '||'}
	at com.blazebit.persistence.parser.expression.AbstractExpressionFactory.createExpression(AbstractExpressionFactory.java:183)
	at com.blazebit.persistence.parser.expression.AbstractExpressionFactory.createSimpleExpression(AbstractExpressionFactory.java:226)
	at com.blazebit.persistence.parser.expression.AbstractCachingExpressionFactory$2.get(AbstractCachingExpressionFactory.java:56)
	at com.blazebit.persistence.parser.expression.AbstractCachingExpressionFactory.getOrDefault(AbstractCachingExpressionFactory.java:158)
	at com.blazebit.persistence.parser.expression.AbstractCachingExpressionFactory.createSimpleExpression(AbstractCachingExpressionFactory.java:109)
	at com.blazebit.persistence.impl.JpqlMacroAwareExpressionFactory.createSimpleExpression(JpqlMacroAwareExpressionFactory.java:95) 
        at com.blazebit.persistence.impl.AbstractCommonQueryBuilder.select(AbstractCommonQueryBuilder.java:1305)
```

Using a standard QueryDSL query factory, there is no error.

```
String[] ROLES = new String[] { ROLE_1, ROLE_2, ROLE_3, ROLE_4};
return this.queryFactory
         .select(Projections.fields(CustomerContactDTO.class,
                Tables.customerMember.id.as("id"),
                Tables.customerMember.user.id.as("userId"),
                Tables.userRole.role.in(ROLES).as("allowLogin"))).distinct()
         .from(foo);
```

Using a blaze query factory, you get the error.
```
String[] ROLES = new String[] { ROLE_1, ROLE_2, ROLE_3, ROLE_4};
return this.blazeJPAQueryFactory.
         .select(Projections.fields(CustomerContactDTO.class,
                Tables.customerMember.id.as("id"),
                Tables.customerMember.user.id.as("userId"),
                Tables.userRole.role.in(ROLES).as("allowLogin"))).distinct()
         .from(foo);
```

## Expected behavior
Standard QueryDSL with JPA does not throw any errors and correctly handles the IN clause.

## Actual behavior
An error is thrown in the createSimpleExpression logic in blaze.

## Work Around
As a work around, you can create a case expression which will fix the issue.

```
BooleanExpression allowLogin = new CaseBuilder().when(Tables.userRole.role.in(CUSTOMER_AND_ADVISOR_ROLES)).then(true).otherwise(false);
return this.blazeJPAQueryFactory
         .select(Projections.fields(CustomerContactDTO.class,
                Tables.customerMember.id.as("id"),
                Tables.customerMember.user.id.as("userId"),
                allowLogin.as("allowLogin"))).distinct()
         .from(foo);
```

## Environment
Java: 17
JPA-Provider: Hibernate 5.6.11.Final
DBMS: MySQL 8
Blaze-Persistence: 1.6.8

**Comment by jwgmeligmeyling** [comment]
I think this is caused by #340.

**Comment by ctobe-zen** [comment]
Thanks @jwgmeligmeyling !
