### ISSUE TITLE
Spring boot 2.6 -> 3.1.2 - "Could not autowire. No beans of 'EntityViewConfiguration' type found. "

### ISSUE THREAD

**Issue by bigalnz** [Blazebit/blaze-persistence#1789]
During upgrade of project from Spring Boot 2.6 to 3.1.2 I now get the following gradle build error on my `BlazePersistenceConfiguration` class:
```
import com.blazebit.persistence.Criteria;
import com.blazebit.persistence.CriteriaBuilderFactory;
import com.blazebit.persistence.spi.CriteriaBuilderConfiguration;
import com.blazebit.persistence.view.EntityViewManager;
import com.blazebit.persistence.view.spi.EntityViewConfiguration;

import jakarta.persistence.EntityManagerFactory;
import jakarta.persistence.PersistenceContext;
import jakarta.persistence.PersistenceUnit;
import org.springframework.beans.factory.config.ConfigurableBeanFactory;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Lazy;
import org.springframework.context.annotation.Scope;


@Configuration
public class BlazePersistenceConfiguration {
    @PersistenceUnit
    private EntityManagerFactory entityManagerFactory;

    @Bean
    @Scope(ConfigurableBeanFactory.SCOPE_SINGLETON)
    @Lazy(false)
    public CriteriaBuilderFactory createCriteriaBuilderFactory() {
        CriteriaBuilderConfiguration config = Criteria.getDefault();
        // do some configuration
        return config.createCriteriaBuilderFactory(entityManagerFactory);
    }

    @Bean
    @Scope(ConfigurableBeanFactory.SCOPE_SINGLETON)
    @Lazy(false)
    // inject the criteria builder factory which will be used along with the entity view manager
    public EntityViewManager createEntityViewManager(CriteriaBuilderFactory cbf, EntityViewConfiguration entityViewConfiguration) {
        return entityViewConfiguration.createEntityViewManager(cbf);
    }
}
```
Specifically the IDE is underlining 'entityViewConfiguration' with the "Could not autowire. No beans of 'EntityViewConfiguration' type found. " message.

Build.gradle is:
```
buildscript {
	repositories { jcenter() }
	dependencies {
		classpath "org.springframework.boot:spring-boot-gradle-plugin:3.1.2"
		classpath 'org.springframework:springloaded:1.2.6.RELEASE'
	}
}

plugins {
	id 'org.springframework.boot' version '3.1.2'
	//id 'io.spring.dependency-management' version '1.0.11.RELEASE'
	id 'io.spring.dependency-management' version '1.1.2'
	id 'java'
	id 'idea'
}

idea {
	module {
		inheritOutputDirs = false
		outputDir = file("$buildDir/classes/main/")
	}
}
ext['h2.version'] = '1.4.197'

group = 'com.nz'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '17'

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

/*ext {
	set('azureVersion', "3.14.0")
}*/

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-web'

	compileOnly 'org.projectlombok:lombok'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'


	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'

	implementation 'com.blazebit:blaze-persistence-entity-view-api:1.6.9'
	implementation 'com.blazebit:blaze-persistence-integration-spring-data-base:1.6.9'
	implementation group: 'com.blazebit', name: 'blaze-persistence-integration-spring-data-webmvc', version: '1.6.9'
	implementation group: 'com.blazebit', name: 'blaze-persistence-integration-spring-data-3.1', version: '1.6.9'
	implementation group: 'com.blazebit', name: 'blaze-persistence-integration-hibernate-6.2', version: '1.6.9'
	implementation group: 'com.blazebit', name: 'blaze-persistence-core-api-jakarta', version: '1.6.9'
	runtimeOnly group: 'com.blazebit', name: 'blaze-persistence-core-impl-jakarta', version: '1.6.9'


	implementation group: 'org.locationtech.jts', name: 'jts-core', version: '1.18.2'
	implementation group: 'com.graphhopper.external', name: 'jackson-datatype-jts', version: '1.0-2.7'
	implementation group: 'org.hibernate', name: 'hibernate-spatial', version: '6.2.6.Final', ext: 'pom'

	implementation group: 'org.orbisgis', name: 'h2gis', version: '1.5.0'
	implementation group: 'org.modelmapper', name: 'modelmapper', version: '2.4.4'
	implementation group: 'mysql', name: 'mysql-connector-java', version: '8.0.28'
	runtimeOnly 'mysql:mysql-connector-java'


	implementation 'org.mapstruct:mapstruct:1.4.2.Final'
	annotationProcessor 'org.mapstruct:mapstruct-processor:1.4.2.Final'

	implementation group: 'com.vladmihalcea', name: 'hibernate-types-52', version: '2.12.1'

}

bootJar {
	duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

/*dependencyManagement {
	imports {
		mavenBom "com.azure.spring:azure-spring-boot-bom:${azureVersion}"
	}
}*/

tasks.named('test') {
	useJUnitPlatform()
}
```
More information available on stack trace:
```
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'kiwiApplication': Unsatisfied dependency expressed through field 'weightMeasurementsRepository': Error creating bean with name 'weightMeasurementsRepository': Unsatisfied dependency expressed through field 'evm': Error creating bean with name 'createEntityViewManager' defined in class path resource [com/nz/kiwi/config/BlazePersistenceConfiguration.class]: Unsatisfied dependency expressed through method 'createEntityViewManager' parameter 1: Error creating bean with name 'entityViewConfigurationProducer': Failed to instantiate [com.blazebit.persistence.integration.view.spring.impl.EntityViewConfigurationProducer$$SpringCGLIB$$0]: Constructor threw exception
	at app//org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:716)
	at app//org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:696)
	at app//org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:145)
	at app//org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:483)
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1416)
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:597)
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
	at app//org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at app//org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at app//org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at app//org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at app//org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973)
	at app//org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:942)
	at app//org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608)
	at app//org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)
	at app//org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:436)
	at app//org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
	at app//org.springframework.boot.test.context.SpringBootContextLoader.lambda$loadContext$3(SpringBootContextLoader.java:137)
	at app//org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:58)
	at app//org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:46)
	at app//org.springframework.boot.SpringApplication.withHook(SpringApplication.java:1406)
	at app//org.springframework.boot.test.context.SpringBootContextLoader$ContextLoaderHook.run(SpringBootContextLoader.java:545)
	at app//org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:137)
	at app//org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:108)
	at app//org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:187)
	at app//org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:119)
	... 84 more
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'weightMeasurementsRepository': Unsatisfied dependency expressed through field 'evm': Error creating bean with name 'createEntityViewManager' defined in class path resource [com/nz/kiwi/config/BlazePersistenceConfiguration.class]: Unsatisfied dependency expressed through method 'createEntityViewManager' parameter 1: Error creating bean with name 'entityViewConfigurationProducer': Failed to instantiate [com.blazebit.persistence.integration.view.spring.impl.EntityViewConfigurationProducer$$SpringCGLIB$$0]: Constructor threw exception
	at app//org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:716)
	at app//org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:696)
	at app//org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:145)
	at app//org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:483)
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1416)
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:597)
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
	at app//org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at app//org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at app//org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at app//org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at app//org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
	at app//org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1417)
	at app//org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1337)
	at app//org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:713)
	... 109 more
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'createEntityViewManager' defined in class path resource [com/nz/kiwi/config/BlazePersistenceConfiguration.class]: Unsatisfied dependency expressed through method 'createEntityViewManager' parameter 1: Error creating bean with name 'entityViewConfigurationProducer': Failed to instantiate [com.blazebit.persistence.integration.view.spring.impl.EntityViewConfigurationProducer$$SpringCGLIB$$0]: Constructor threw exception
	at app//org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
	at app//org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:550)
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1332)
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1162)
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560)
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
	at app//org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at app//org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at app//org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at app//org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at app//org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
	at app//org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1417)
	at app//org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1337)
	at app//org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:713)
	... 123 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityViewConfigurationProducer': Failed to instantiate [com.blazebit.persistence.integration.view.spring.impl.EntityViewConfigurationProducer$$SpringCGLIB$$0]: Constructor threw exception
	at app//org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:326)
	at app//org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:314)
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1352)
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1189)
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560)
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
	at app//org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at app//org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at app//org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at app//org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at app//org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:417)
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1332)
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1162)
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560)
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
	at app//org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at app//org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at app//org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at app//org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at app//org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
	at app//org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1417)
	at app//org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1337)
	at app//org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:888)
	at app//org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	... 136 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.blazebit.persistence.integration.view.spring.impl.EntityViewConfigurationProducer$$SpringCGLIB$$0]: Constructor threw exception
	at app//org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:224)
	at app//org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:110)
	at app//org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:323)
	... 159 more
Caused by: java.lang.NoClassDefFoundError: javax/persistence/metamodel/Type
	at com.blazebit.persistence.view.impl.metamodel.AnnotationMappingReader.readAbstractClassMappings(AnnotationMappingReader.java:353)
	at com.blazebit.persistence.view.impl.metamodel.AnnotationMappingReader.readViewMapping(AnnotationMappingReader.java:325)
	at com.blazebit.persistence.view.impl.EntityViewConfigurationImpl.createEntityViewMapping(EntityViewConfigurationImpl.java:120)
	at com.blazebit.persistence.view.impl.EntityViewConfigurationImpl.addEntityView(EntityViewConfigurationImpl.java:114)
	at com.blazebit.persistence.integration.view.spring.impl.EntityViewConfigurationProducer.<init>(EntityViewConfigurationProducer.java:39)
	at com.blazebit.persistence.integration.view.spring.impl.EntityViewConfigurationProducer$$SpringCGLIB$$0.<init>(<generated>)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211)
	... 161 more
Caused by: java.lang.ClassNotFoundException: javax.persistence.metamodel.Type
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 171 more
	```

**Comment by beikov** [comment]
>Specifically the IDE is underlining 'entityViewConfiguration' with the "Could not autowire. No beans of 'EntityViewConfiguration' type found. " message.

You can ignore that message. The IDE is not able to figure out that there is a bean provided by an auto configuration for some reason.

The error you are seeing is because you're using wrong dependencies. You should be using this instead:

```java
	implementation 'com.blazebit:blaze-persistence-entity-view-api-jakarta:1.6.9'
	implementation group: 'com.blazebit', name: 'blaze-persistence-integration-spring-data-webmvc-jakarta', version: '1.6.9'
	implementation group: 'com.blazebit', name: 'blaze-persistence-integration-spring-data-3.1', version: '1.6.9'
	implementation group: 'com.blazebit', name: 'blaze-persistence-integration-hibernate-6.2', version: '1.6.9'
	implementation group: 'com.blazebit', name: 'blaze-persistence-core-api-jakarta', version: '1.6.9'
	runtimeOnly group: 'com.blazebit', name: 'blaze-persistence-core-impl-jakarta', version: '1.6.9'
```

**Comment by baikov-ilia** [comment]
Same thing here, proposed fix from above doesn't make sense

**Comment by beikov** [comment]
That's not correct @baikov-ilia, you rather need `implementation group: 'com.blazebit', name: 'blaze-persistence-integration-entity-view-spring-6.0', version: '1.6.9'`, but that comes as transitive dependency from `implementation group: 'com.blazebit', name: 'blaze-persistence-integration-spring-data-3.1', version: '1.6.9'`, so you shouldn't have to list this explicitly.

**Comment by baikov-ilia** [comment]
@beikov, Yep, just tried to exclude this dependency from build.gradle and app still starting but Intellij stsarted to highlight EntityViewConfiguration bean with warning "Could not autowire. No beans of 'EntityViewConfiguration' type found."
So might be IDE unable to index transitive dependencies
