### ISSUE TITLE
Blaze Persistence 1.6.10 is no longer compatible with spring boot 3.2.0

### ISSUE THREAD

**Issue by EugenMayer** [Blazebit/blaze-persistence#1845]
Early bird issue, one gets an exception with

```
java.lang.NoSuchMethodError: 'void org.springframework.util.Assert.notNull(java.lang.Object)'

    at com.blazebit.persistence.integration.view.spring.impl.EntityViewComponentProvider.<init>(EntityViewComponentProvider.java:41)
    at com.blazebit.persistence.integration.view.spring.impl.AbstractEntityViewConfigurationSource.getCandidates(AbstractEntityViewConfigurationSource.java:47)
    at com.blazebit.persistence.integration.view.spring.impl.EntityViewConfigurationDelegate.registerEntityViews(EntityViewConfigurationDelegate.java:50)
    at com.blazebit.persistence.integration.view.spring.impl.EntityViewRegistrar.registerBeanDefinitions(EntityViewRegistrar.java:82)
    at org.springframework.context.annotation.ImportBeanDe
```

BP: 1.6.10 (latest main), sb: 3.2.0 / spring-data-jpa 3.2.0 (https://github.com/spring-projects/spring-data-jpa/releases/tag/3.2.0)

**Comment by fk-currenxie** [comment]
Already fixed https://github.com/Blazebit/blaze-persistence/issues/1842
