### ISSUE TITLE
hibernate 6.6.1 java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by EugenMayer** [Blazebit/blaze-persistence#1949]
BP based on `0bb921bda`, hibernate 6.6.1, java 17 / jakarta

```
java.lang.NoSuchMethodError: 'org.hibernate.sql.results.internal.RowTransformerSingularReturnImpl org.hibernate.sql.results.internal.RowTransformerSingularReturnImpl.instance()'

    at com.blazebit.persistence.integration.hibernate.base.HibernateExtendedQuerySupport.determineRowTransformer(HibernateExtendedQuerySupport.java:767)
    at com.blazebit.persistence.integration.hibernate.base.HibernateExtendedQuerySupport.getResultList(HibernateExtendedQuerySupport.java:508)
    at com.blazebit.persistence.integration.hibernate.base.HibernateExtendedQuerySupport.getResultList(HibernateExtendedQuerySupport.java:501)
    at com.blazebit.persistence.impl.plan.CustomSelectQueryPlan.getResultList(CustomSelectQueryPlan.java:58)
    at com.blazebit.persistence.impl.query.CustomSQLTypedQuery.getResultList(CustomSQLTypedQuery.java:53)
    at com.blazebit.persistence.impl.AbstractQueryBuilder.getResultList(AbstractQueryBuilder.java:58)
    at
```

**Comment by EugenMayer** [comment]
I can confirm that this fixed the issue and all our tests are now running just fine with the latest master build (which is 1.6.13 now as i see) and hibernate 6.6.1
