### ISSUE TITLE
NPE on getResultList() for CTE, fails in HibernateExtendedQuerySupport.getNamedParams(..)

### ISSUE THREAD

**Issue by JWGmeligMeyling** [Blazebit/blaze-persistence#223]
Hi!

I am experimenting with recursive CTE functions. I have altered the `Cat` example from the documentation to my own entity (`Scope`). My CTE looks as follows:

```java
@CTE
@Data
@Entity
public class ScopeCte {

    @Id
    private Long id;

    @ManyToOne
    private Scope<?,?> ancestor;

}
```

(A supposedly minor difference with the documentation is that I use field annotations and have my getters and setters generated through Lombok).

When creating the following CriteriaBuilder and trying to obtain a result using `getResultList()`, I get the below exception.

```java
                CriteriaBuilder<ScopeCte> cb = cbf.create(entityManager, ScopeCte.class)
                    .withRecursive(ScopeCte.class)
                    .from(Scope.class, "scope")
                    .bind("id").select("scope.id")
                    .bind("ancestor").select("scope.parent")
                    .where("id").eq(36l)
                    .unionAll()
                    .from(Scope.class, "scope")
                    .from(ScopeCte.class, "parentScope")
                    .bind("id").select("scope.id")
                    .bind("ancestor").select("scope.parent")
                    .where("scope.id").eqExpression("parentScope.ancestor.id")
                    .end();

cb.getResultList();
```

The exception:

```
Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerException
	at com.blazebit.persistence.impl.hibernate.HibernateExtendedQuerySupport.getNamedParams(HibernateExtendedQuerySupport.java:655)
	at com.blazebit.persistence.impl.hibernate.HibernateExtendedQuerySupport.getOriginalQueryPlan(HibernateExtendedQuerySupport.java:118)
	at com.blazebit.persistence.impl.hibernate.HibernateExtendedQuerySupport.getSql(HibernateExtendedQuerySupport.java:92)
	at com.blazebit.persistence.impl.AbstractCommonQueryBuilder.getTypedQuery(AbstractCommonQueryBuilder.java:1085)
	at com.blazebit.persistence.impl.AbstractQueryBuilder.getQuery(AbstractQueryBuilder.java:51)
	at com.blazebit.persistence.impl.AbstractQueryBuilder.getResultList(AbstractQueryBuilder.java:56)
	at com.pallasathenagroup.portal.core.TestRun.main(TestRun.java:75)
Caused by: java.lang.NullPointerException
	at com.blazebit.persistence.impl.hibernate.HibernateExtendedQuerySupport.getNamedParams(HibernateExtendedQuerySupport.java:652)
	... 6 more
```

Any idea what I am doing wrong?

**Comment by beikov** [comment]
Which hibernate version are you using? If it's Hibernate 5.2 then that's expected because 1.1.0 does not have an integration for 5.2. Can you do your testing with Hibernate 5.1 for now and maybe switch to blaze-persistence 1.2.0-Alpha1 release when I have finished it in next days? Backporting the 5.2 integration might be a bit difficult and I'd like to focus on moving forward.

**Comment by JWGmeligMeyling** [comment]
I am indeed on Hibernate 5.2.1.Final, I will quickly switch to `5.1` and experiment with `1.2.0-Alpha` when it is available. I'll keep you posted about my findings!

**Comment by beikov** [comment]
Thanks :)

**Comment by JWGmeligMeyling** [comment]
Couldn't test on Hibernate 5.1 so quickly, because I see that for my domain I have to go trough some changes in custom and Java 8 datetime types. I installed the `1.2.0-SNAPSHOT` from the current master though, and that worked! (Had to switch to `blaze-persistence-integration-hibernate-5.2`)
