### ISSUE TITLE
Hibernate integration: CTE seems to break @Fetch(Subselect)

### ISSUE THREAD

**Issue by JWGmeligMeyling** [Blazebit/blaze-persistence#227]
Usecase: When loading entities from a recursive CTE query, I want to efficiently fetch OneToMany relations from the entity. One use case could be to load the [children](https://github.com/Blazebit/blaze-persistence/blob/master/core/testsuite/src/main/java/com/blazebit/persistence/testsuite/entity/RecursiveEntity.java#L84-L87) of the `RecursiveEntity`. In the very special case that this relation is in fact the recursive relation which is being traversed in breadth-first order this could even be optimised to be initialised with the very same query result (we know that we have all children already), but such a *recursive* fetch strategy sounds quite difficult to implement (correct me if I am wrong and this is in fact already possible).

Anyway supporting the [`FetchMode.SUBSELECT`](https://docs.jboss.org/hibernate/orm/3.5/api/org/hibernate/annotations/FetchMode.html#SUBSELECT) Fetch strategy for the returned entities would be nice for all sorts of `OneToMany` relations from the entity

 Currently, I get the following stacktrace:

```
Exception in thread "main" org.hibernate.exception.DataException: could not load collection by subselect: [com.pallasathenagroup.entities.Scope.subScopes#<1818, 2336, 2322, 2323, 2325, 2314, 2316, 2311, 2312, 765, 1779, 758, 1772, 1773, 2395, 1372, 2398, 1889, 1354, 1360, 2364, 2360, 1836, 1325, 1183, 2196, 1674, 2186, 2187, 2172, 2174, 2175, 2176, 1664, 2164, 2165, 2158, 1250, 2274, 2275, 1764, 1765, 1766, 2278, 1767, 1769, 2266, 2268, 2269, 1247, 2271, 2273, 1746, 1747, 1748, 2261, 2262, 2263, 2264, 2265, 2250, 2251, 2252, 2243, 2244, 2245, 2246, 2247, 2248, 2249, 701, 704, 691, 2218, 1571, 1572, 36, 1056, 1538, 1539, 1540, 1542, 1543, 2042, 2045, 1536, 2560, 1, 2039, 2040, 2538, 2033, 1637, 2151, 2152, 2141, 1618, 2136, 1611, 1612, 1609, 574, 1591, 1592, 2105, 1938, 397, 1936, 1937, 1923, 1924, 1925, 1926, 1415, 1416, 1928, 1929, 1417, 1404, 1917, 1409, 1909, 2424, 2007, 2001, 2498, 2490, 2491, 2492, 1981, 2493, 2494, 2495, 2496, 2497, 1458, 2482, 1459, 2489, 2478, 2480, 1456>]
	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:118)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:111)
	at org.hibernate.loader.Loader.loadCollectionSubselect(Loader.java:2394)
	at org.hibernate.loader.collection.SubselectOneToManyLoader.initialize(SubselectOneToManyLoader.java:62)
	at org.hibernate.persister.collection.AbstractCollectionPersister.initialize(AbstractCollectionPersister.java:682)
	at org.hibernate.event.internal.DefaultInitializeCollectionEventListener.onInitializeCollection(DefaultInitializeCollectionEventListener.java:75)
	at org.hibernate.internal.SessionImpl.initializeCollection(SessionImpl.java:2142)
	at org.hibernate.collection.internal.AbstractPersistentCollection$4.doWork(AbstractPersistentCollection.java:567)
	at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:249)
	at org.hibernate.collection.internal.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:563)
	at org.hibernate.collection.internal.AbstractPersistentCollection.read(AbstractPersistentCollection.java:132)
	at org.hibernate.collection.internal.PersistentBag.get(PersistentBag.java:449)
	at com.pallasathenagroup.portal.core.TestRun.main(TestRun.java:83)
Caused by: org.postgresql.util.PSQLException: The column index is out of range: 1, number of columns: 0.
	at org.postgresql.core.v3.SimpleParameterList.bind(SimpleParameterList.java:64)
	at org.postgresql.core.v3.SimpleParameterList.setBinaryParameter(SimpleParameterList.java:131)
	at org.postgresql.jdbc.PgPreparedStatement.bindBytes(PgPreparedStatement.java:1094)
	at org.postgresql.jdbc.PgPreparedStatement.setLong(PgPreparedStatement.java:326)
	at org.hibernate.type.descriptor.sql.BigIntTypeDescriptor$1.doBind(BigIntTypeDescriptor.java:46)
	at org.hibernate.type.descriptor.sql.BasicBinder.bind(BasicBinder.java:74)
	at org.hibernate.type.AbstractStandardBasicType.nullSafeSet(AbstractStandardBasicType.java:277)
	at org.hibernate.type.AbstractStandardBasicType.nullSafeSet(AbstractStandardBasicType.java:272)
	at org.hibernate.loader.Loader.bindNamedParameters(Loader.java:2096)
	at org.hibernate.loader.Loader.bindParameterValues(Loader.java:2016)
	at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1950)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1903)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1881)
	at org.hibernate.loader.Loader.doQuery(Loader.java:926)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:343)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:313)
	at org.hibernate.loader.Loader.loadCollectionSubselect(Loader.java:2387)
	... 10 more
```

I can imagine this being quite difficult to fix. I am not exactly sure how the [`FetchMode.SUBSELECT`](https://docs.jboss.org/hibernate/orm/3.5/api/org/hibernate/annotations/FetchMode.html#SUBSELECT) Fetch strategy works under the hood, but it figures out the result set from the previous query (and from my observations, it tries to execute the query again, and substituting a CTE query may be where this goes wrong). Also, from the documentation, I've seen that in fact `org.hibernate.annotations.Subselect` is used to implement CTE queries, so this may be another cause for the incompatibility. 

Working on a reproducible testcase, I may submit a PR later today.

**Comment by beikov** [comment]
Would be nice if you could create a testcase directly in the testsuite project so I can debug that.
Can you post the query so I can see what you are trying to do? Maybe there is a workaround or a different approach to what you want to achieve.

**Comment by JWGmeligMeyling** [comment]
I have added a testcase (wasn't exactly sure where to put it so I made another class for it). The exception is slightly different with these entities (and probably also due to running on H2). The new exception makes my assumption about the query substitution more likely:

```
org.hibernate.exception.SQLGrammarException: could not prepare statement

	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:123)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:124)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:193)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:157)
	at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1881)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1858)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1838)
	at org.hibernate.loader.Loader.doQuery(Loader.java:906)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:348)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:318)
	at org.hibernate.loader.Loader.loadCollectionSubselect(Loader.java:2329)
	at org.hibernate.loader.collection.SubselectOneToManyLoader.initialize(SubselectOneToManyLoader.java:79)
	at org.hibernate.persister.collection.AbstractCollectionPersister.initialize(AbstractCollectionPersister.java:674)
	at org.hibernate.event.internal.DefaultInitializeCollectionEventListener.onInitializeCollection(DefaultInitializeCollectionEventListener.java:86)
	at org.hibernate.internal.SessionImpl.initializeCollection(SessionImpl.java:1810)
	at org.hibernate.collection.internal.AbstractPersistentCollection.forceInitialization(AbstractPersistentCollection.java:696)
	at org.hibernate.Hibernate.initialize(Hibernate.java:77)
	at com.blazebit.persistence.testsuite.Issue227Test.testFetchModeSubselectOnCteQueryResult(Issue227Test.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
Caused by: org.h2.jdbc.JdbcSQLException: Table "ISSUE227TEST$RECURSIVEENTITYCTE" not found; SQL statement:
select children0_.parent_id as parent_i3_1_1_, children0_.id as id1_1_1_, children0_.id as id1_1_0_, children0_.name as name2_1_0_, children0_.parent_id as parent_i3_1_0_ from issue_227_recursive_entity children0_ where children0_.parent_id in (select issue227te1_.id from issue_227_recursive_entity issue227te0_ where issue227te0_.parent_id is not null
UNION ALL
select issue227te0_.id as col_0_0_, issue227te0_.name as col_1_0_, issue227te0_.parent_id as col_2_0_ from issue_227_recursive_entity issue227te0_ cross join Issue227Test$RecursiveEntityCte issue227te1_ where issue227te0_.id=issue227te1_.parent_id
)
select issue227te0_.id as id1_0_0_, issue227te1_.id as id1_1_1_, issue227te0_.name as name2_0_0_, issue227te0_.parent_id as parent_i3_0_0_, issue227te1_.name as name2_1_1_, issue227te1_.parent_id as parent_i3_1_1_ from Issue227Test$RecursiveEntityCte issue227te0_ left outer join issue_227_recursive_entity issue227te1_ on issue227te0_.parent_id=issue227te1_.id) [42102-183]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.readTableOrView(Parser.java:5239)
	at org.h2.command.Parser.readTableFilter(Parser.java:1227)
	at org.h2.command.Parser.readJoin(Parser.java:1548)
	at org.h2.command.Parser.parseJoinTableFilter(Parser.java:1872)
	at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1867)
	at org.h2.command.Parser.parseSelectSimple(Parser.java:1975)
	at org.h2.command.Parser.parseSelectSub(Parser.java:1860)
	at org.h2.command.Parser.parseSelectUnionExtension(Parser.java:1696)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1682)
	at org.h2.command.Parser.parseSelect(Parser.java:1669)
	at org.h2.command.Parser.readCondition(Parser.java:2113)
	at org.h2.command.Parser.readAnd(Parser.java:2030)
	at org.h2.command.Parser.readExpression(Parser.java:2022)
	at org.h2.command.Parser.parseSelectSimple(Parser.java:1979)
	at org.h2.command.Parser.parseSelectSub(Parser.java:1860)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1681)
	at org.h2.command.Parser.parseSelect(Parser.java:1669)
	at org.h2.command.Parser.parsePrepared(Parser.java:433)
	at org.h2.command.Parser.parse(Parser.java:305)
	at org.h2.command.Parser.parse(Parser.java:277)
	at org.h2.command.Parser.prepareCommand(Parser.java:242)
	at org.h2.engine.Session.prepareLocal(Session.java:446)
	at org.h2.engine.Session.prepareCommand(Session.java:388)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1189)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:72)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:277)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:159)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:183)
	... 39 more
```

**Comment by JWGmeligMeyling** [comment]
I am starting to think that this is actually a Hibernate issue, the way `FetchMode.SUBSELECT` is currently implemented, probably just doesn't work for all types of queries.

**Comment by beikov** [comment]
Which Hibernate version are you using exactly? Interestingly I can reproduce it with e.g. PostgreSQL but not with H2.

**Comment by JWGmeligMeyling** [comment]
In my project I used the newest 5.2 on the master 1.2.0, against a Postgres database. I am not exactly sure which databases the tests are ran against, but at least with the default Hibernate/H2 configuration, that test failed as well, untill commenting the Fetch annotation.

**Comment by SelaO** [comment]
How was this problem with FetchMode.SUBSELECT resolved? @beikov @jwgmeligmeyling

**Comment by jwgmeligmeyling** [comment]
By implementing custom `OneToMany` and `Collection-` Loader classes that change the ordering of the parameters. See https://github.com/Blazebit/blaze-persistence/pull/236. We later improved that implementation to also handle Hibernates propriertairy positional style parameters, which Filters heavily rely on: https://github.com/Blazebit/blaze-persistence/commit/6f8018e5bde54fdee1c40d8b399d89499eeeb303#diff-e8a48e45cf7e92ae7b85551cae7c6387
