### ISSUE TITLE
Question about Fetch joins for non-root entities

### ISSUE THREAD

**Issue by JWGmeligMeyling** [Blazebit/blaze-persistence#238]
#I am trying to recursively traverse a tree (Scope) for which any node is attached to a collection of elements. These elements (`DiscountCode` here) have a back reference to their scope (mapped by). Using the following criteriabuilder, with an `innerJoin` and then a `select` I observe `n` queries being ran to fetch the `scope` of the `discountCode` (even though it's already in the result set from the Inner join. When trying to optimize this using a `fetch` (enabling the commented line below), I get the exception: 

```
Exception in thread "main" java.lang.IllegalStateException: Fetch joins are only possible if the root entity is selected
	at com.blazebit.persistence.impl.AbstractFullQueryBuilder.checkFetchJoinAllowed(AbstractFullQueryBuilder.java:154)
	at com.blazebit.persistence.impl.AbstractFullQueryBuilder.fetch(AbstractFullQueryBuilder.java:162)
	at com.pallasathenagroup.portal.core.TestRun.main(TestRun.java:95)
```

```java
val cb = cbf.create(entityManager, ScopeDiscountCode.class)
    .from(ScopeCte.class)
    .withRecursive(ScopeCte.class)
        .from(Scope.class, "scope")
        .bind("id").select("scope.id")
        .bind("ancestor").select("scope.parent")
        .where("scope").eq(scope)
    .unionAll()
        .from(Scope.class, "scope")
        .from(ScopeCte.class, "parentScope")
        .bind("id").select("scope.id")
        .bind("ancestor").select("scope.parent")
        .where("scope.parent.id").eqExpression("parentScope.id")
    .end()
        .innerJoin("scope.discountCodes", "dc")
        .select("dc")
//        .fetch("dc.applicableIn")
        .getResultList();
```

Is there another way to express this in a CriteriaBuilder? Shouldn't the `@ManyToOne` relation be eagerly initialised anyway?

**Comment by beikov** [comment]
Unfortunately you just hit #190 which is on my todo list for the alpha release.
May I ask what it is that you want to achieve? You could base your query on a different root and do a `IN` like

```
val cb = cbf.create(entityManager, ScopeDiscountCode.class)
    .withRecursive(ScopeCte.class)
        .from(Scope.class, "scope")
        .bind("id").select("scope.id")
        .bind("ancestor").select("scope.parent")
        .where("scope").eq(scope)
    .unionAll()
        .from(Scope.class, "scope")
        .from(ScopeCte.class, "parentScope")
        .bind("id").select("scope.id")
        .bind("ancestor").select("scope.parent")
        .where("scope.parent.id").eqExpression("parentScope.id")
    .end()
    .from(DiscountCode.class, "dc")
        .select("dc")
        .fetch("dc.applicableIn")
        .getResultList();
```

**Comment by JWGmeligMeyling** [comment]
Had to alter the query to 

```
val cb = cbf.create(entityManager, ScopeDiscountCode.class)
    .withRecursive(ScopeCte.class)
        .from(Scope.class, "scope")
        .bind("id").select("scope.id")
        .bind("ancestor").select("scope.parent")
        .where("scope").eq(scope)
    .unionAll()
        .from(Scope.class, "scope")
        .from(ScopeCte.class, "parentScope")
        .bind("id").select("scope.id")
        .bind("ancestor").select("scope.parent")
        .where("scope.parent.id").eqExpression("parentScope.id")
    .end()
    .from(ScopeDiscountCode.class, "dc")
        .where("dc.applicableIn").in()
            .from(ScopeCte.class, "scope")
            .select("scope.id")
            .end()
    .fetch("applicableIn");
```

But this work around works. Thanks! Lets close this as a duplicate for enhancement #190.
