### ISSUE TITLE
org.hibernate.DuplicateMappingException in packaged JAR

### ISSUE THREAD

**Issue by JWGmeligMeyling** [Blazebit/blaze-persistence#258]
If I package my application to a JAR, start up fails with a `org.hibernate.DuplicateMappingException`, even though it runs just fine from my IDE.

My entities and `persistence.xml` live in a `domain` module, that is included in my application's `pom.xml` file. 

```xml
    <dependency>
      <groupId>com.pallasathenagroup</groupId>
      <artifactId>domain</artifactId>
      <version>1.0-SNAPSHOT</version>
    </dependency>
```

`blaze-persistence` is then loaded as a transitive dependency from `domain`. I am using the configuration from the `README.md`: 

```xml
        <dependency>
            <groupId>com.blazebit</groupId>
            <artifactId>blaze-persistence-core-api</artifactId>
            <version>${blaze-persistence.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.blazebit</groupId>
            <artifactId>blaze-persistence-core-impl</artifactId>
            <version>${blaze-persistence.version}</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>com.blazebit</groupId>
            <artifactId>blaze-persistence-entity-view-api</artifactId>
            <version>${blaze-persistence.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.blazebit</groupId>
            <artifactId>blaze-persistence-entity-view-impl</artifactId>
            <version>${blaze-persistence.version}</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>com.blazebit</groupId>
            <artifactId>blaze-persistence-integration-hibernate-5.2</artifactId>
            <version>${blaze-persistence.version}</version>
            <scope>runtime</scope>
        </dependency>
```

When I run the application from the JAR, using `java -classpath target/core-full.jar com.pallasathenagroup.portal.core.Iris` the application fails with:

```
Exception in thread "main" org.hibernate.DuplicateMappingException: Duplicate entity mapping com.blazebit.persistence.impl.function.entity.ValuesEntity
        at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.addEntityBinding(InFlightMetadataCollectorImpl.java:271)
        at org.hibernate.cfg.AnnotationBinder.bindClass(AnnotationBinder.java:760)
        at com.blazebit.persistence.impl.hibernate.Hibernate52MetadataContributor.addEntity(Hibernate52MetadataContributor.java:43)
        at com.blazebit.persistence.impl.hibernate.Hibernate52MetadataContributor.contribute(Hibernate52MetadataContributor.java:35)
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:275)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:857)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:884)
        at org.hibernate.jpa.HibernatePersistenceProvider.createEntityManagerFactory(HibernatePersistenceProvider.java:58)
        at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
        at com.pallasathenagroup.portal.core.IrisModule.provideEntityManagerFactory(IrisModule.java:84)
        at com.pallasathenagroup.portal.core.IrisModule_ProvideEntityManagerFactoryFactory.get(IrisModule_ProvideEntityManagerFactoryFactory.java:22)
        at com.pallasathenagroup.portal.core.IrisModule_ProvideEntityManagerFactoryFactory.get(IrisModule_ProvideEntityManagerFactoryFactory.java:8)
        at dagger.internal.ScopedProvider.get(ScopedProvider.java:46)
        at com.pallasathenagroup.portal.core.DaggerIris_IrisGraph.getEntityManagerFactory(DaggerIris_IrisGraph.java:272)
        at com.pallasathenagroup.portal.core.Iris.go(Iris.java:85)
        at com.pallasathenagroup.portal.core.Iris.main(Iris.java:142)
```

Any idea what could cause this issue?

**Comment by beikov** [comment]
I guess that annotation scanning picks up the ValuesEntity class from blaze-persistence-core-impl.jar but the integration tries to also add it. You could workaround that for now by declaring the classes explicitly and disable scanning by setting exclude-unlisted-classes to true in your persistence.xml
I will adapt the integration so that it doesn't get added twice.

**Comment by JWGmeligMeyling** [comment]
That means I have to add all of my `@Entity`s , including the `@CTE`s, and without this `ValuesEntity` right?

**Comment by beikov** [comment]
Yes unfortunately.

**Comment by JWGmeligMeyling** [comment]
I changed my `persistence.xml` to include the class files and exclude unlisted classes. However, now I get the following exception:

```
Exception in thread "main" java.util.ServiceConfigurationError: com.blazebit.persistence.spi.EntityManagerFactoryIntegrator: Provider com.blazebit.persistence.impl.hibernate.function.HibernateEntityManagerFactoryIntegrator could not be instantiated
        at java.util.ServiceLoader.fail(ServiceLoader.java:232)
        at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at com.blazebit.persistence.impl.CriteriaBuilderConfigurationImpl.loadEntityManagerIntegrator(CriteriaBuilderConfigurationImpl.java:437)
        at com.blazebit.persistence.impl.CriteriaBuilderConfigurationImpl.<init>(CriteriaBuilderConfigurationImpl.java:147)
        at com.blazebit.persistence.impl.CriteriaBuilderConfigurationProviderImpl.createConfiguration(CriteriaBuilderConfigurationProviderImpl.java:40)
        at com.blazebit.persistence.Criteria.getDefault(Criteria.java:54)
        at com.pallasathenagroup.portal.core.IrisModule.provideCriteriaBuilderFactory(IrisModule.java:57)
        at com.pallasathenagroup.portal.core.IrisModule_ProvideCriteriaBuilderFactoryFactory.get(IrisModule_ProvideCriteriaBuilderFactoryFactory.java:23)
        at com.pallasathenagroup.portal.core.IrisModule_ProvideCriteriaBuilderFactoryFactory.get(IrisModule_ProvideCriteriaBuilderFactoryFactory.java:9)
        at dagger.internal.ScopedProvider.get(ScopedProvider.java:46)
        at com.pallasathenagroup.portal.core.DaggerIris_IrisGraph.getCriteriaBuilderFactory(DaggerIris_IrisGraph.java:277)
        at com.pallasathenagroup.portal.core.Iris.go(Iris.java:86)
        at com.pallasathenagroup.portal.core.Iris.main(Iris.java:142)
Caused by: java.lang.ExceptionInInitializerError
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at java.lang.Class.newInstance(Class.java:442)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
        ... 13 more
Caused by: java.lang.NumberFormatException: For input string: "[WORKING]"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.parseInt(Integer.java:615)
        at com.blazebit.persistence.impl.hibernate.function.HibernateEntityManagerFactoryIntegrator.<clinit>(HibernateEntityManagerFactoryIntegrator.java:75)
        ... 19 more

```

**Comment by beikov** [comment]
What kind of custom Hibernate version are you using? ^^
I am expecting a dot separated version string.

**Comment by JWGmeligMeyling** [comment]
`mvn dependency:tree` lists:

```
[INFO] +- com.pallasathenagroup:domain:jar:1.0-SNAPSHOT:compile
[INFO] |  +- org.hibernate:hibernate-core:jar:5.2.1.Final:compile
```

Unless my `~/.m2` is corrupt, this should be the regular `5.2.1.Final` release.

**Comment by JWGmeligMeyling** [comment]
`[WORKING]` [actually seems](https://github.com/hibernate/hibernate-orm/blob/5.2.1/hibernate-core/src/main/java/org/hibernate/Version.java#L31-L39) to be the fallback if the implementation version of the JAR can not be found, which probably is the case because I am using a fat jar.

**Comment by beikov** [comment]
Apparently the version is read from the manifest which is removed when using fat jar.

**Comment by beikov** [comment]
Any idea how I could infer the version in the fat jar case?

**Comment by JWGmeligMeyling** [comment]
Currently trying to research that, maybe I can somehow include it in my own `MANIFEST.MF`. Playing with the manifest configuration for `maven-assembly-plugin` currently.

**Comment by JWGmeligMeyling** [comment]
After a bit of research I have come to the conclusion that this is impossible. If `Version` is really part of Hibernate's external API, they probably should use other methods to provide the version number, for example by providing the `${project.version}` using resource filtering. I will now work around the issue by simply not using a fat jar.

That still leaves the issue `DuplicateMappingException` described in this issue. The work around indeed works for me!

**Comment by beikov** [comment]
Apparently this changed recently: https://github.com/hibernate/hibernate-orm/commit/015be3df6ed3e0b7ffa1e0d2325ac8ad1e859aa7#diff-197d2841569f03ef77fff9b387e93425

**Comment by beikov** [comment]
Maybe I can get them to fix that for 5.2.3

**Comment by beikov** [comment]
Too bad, they are just about to release 5.2.3 so fat-jar support will have to wait for at least 5.2.4.
You could workaround it I guess by customizing the manifest

**Comment by beikov** [comment]
Just as a side note, it doesn't look like the Hibernate team is going to fix this anytime soon. As a workaround you could try to give implementing #274 a shot which would be a good workaround I guess.
