### ISSUE TITLE
Fetch joins in PagedCriteriaBuilder fails with QueryException

### ISSUE THREAD

**Issue by JWGmeligMeyling** [Blazebit/blaze-persistence#262]
When uncommenting the following line in my `CriteriaBuilder`, the query fails with the below exception. When I comment the fetch joins, the query runs just fine. Is this expected behaviour? And is this a known issue? (I am aware that PagedCriteriaBuilders with CTE's and Fetch joins are a bit of a todo, nevertheless, I thought it would be worthwhile to report this).

```java
public PagedList<OrderEntry> getOrderEntries(Scope<?,?> start, int skip, int limit) {
    return scopeEntityManager.getRecursiveScopeChildrenCriteriaBuilder(start, OrderEntry.class)
        .from(OrderEntry.class).where("product").in()
            .from(ScopeCte.class, "s")
            .select("s.id")
            .end()
        .whereOr()
            .where("paidPrice").eq(ZERO)
            .where("order.status").eq(PAID)
        .endOr()
        .orderBy("order.orderDateTime", false, true)
        .orderBy("id", false, true)
        .page(skip, limit)
        .fetch("order", "discountCode",  "globalPartner", "scopePartner")
        .getResultList();
}
```

And the stack trace:

```
org.hibernate.QueryException: query specified join fetching, but the owner of the fetched association was not present in the select list [FromElement{explicit,not a collection join,fetch join,fetch non-lazy properties,classAlias=order_1,role=com.pallasathenagroup.entities.hermes.OrderEntry.order,tableName=client_order,tableAlias=order1_,origin=order_entry orderentry0_,columns={orderentry0_.order_id ,className=com.pallasathenagroup.entities.hermes.Order}}] [SELECT COUNT(*                              ) FROM com.pallasathenagroup.entities.hermes.OrderEntry orderentry JOIN FETCH orderentry.order order_1 WHERE orderentry.product IN (SELECT s.id FROM com.pallasathenagroup.cte.ScopeCte s) AND (orderentry.paidPrice = :param_1 OR order_1.status = :param_2)]
java.lang.IllegalArgumentException: org.hibernate.QueryException: query specified join fetching, but the owner of the fetched association was not present in the select list [FromElement{explicit,not a collection join,fetch join,fetch non-lazy properties,classAlias=order_1,role=com.pallasathenagroup.entities.hermes.OrderEntry.order,tableName=client_order,tableAlias=order1_,origin=order_entry orderentry0_,columns={orderentry0_.order_id ,className=com.pallasathenagroup.entities.hermes.Order}}] [SELECT COUNT(*                              ) FROM com.pallasathenagroup.entities.hermes.OrderEntry orderentry JOIN FETCH orderentry.order order_1 WHERE orderentry.product IN (SELECT s.id FROM com.pallasathenagroup.cte.ScopeCte s) AND (orderentry.paidPrice = :param_1 OR order_1.status = :param_2)]
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:131) ~[hibernate-core-5.2.1.Final.jar:5.2.1.Final]
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:155) ~[hibernate-core-5.2.1.Final.jar:5.2.1.Final]
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:162) ~[hibernate-core-5.2.1.Final.jar:5.2.1.Final]
	at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:631) ~[hibernate-core-5.2.1.Final.jar:5.2.1.Final]
	at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:647) ~[hibernate-core-5.2.1.Final.jar:5.2.1.Final]
	at org.hibernate.internal.AbstractSessionImpl.createQuery(AbstractSessionImpl.java:23) ~[hibernate-core-5.2.1.Final.jar:5.2.1.Final]
	at com.blazebit.persistence.impl.PaginatedCriteriaBuilderImpl.getCountQuery(PaginatedCriteriaBuilderImpl.java:139) ~[classes/:na]
	at com.blazebit.persistence.impl.PaginatedCriteriaBuilderImpl.getQuery(PaginatedCriteriaBuilderImpl.java:173) ~[classes/:na]
	at com.blazebit.persistence.impl.PaginatedCriteriaBuilderImpl.getResultList(PaginatedCriteriaBuilderImpl.java:197) ~[classes/:na]
	at com.pallasathenagroup.entitymanagers.OrderEntryEntityManager.getOrderEntries(OrderEntryEntityManager.java:95) ~[classes/:na]
	at com.pallasathenagroup.portal.core.controllers.iris.ScopeController.lambda$routes$103(ScopeController.java:273) ~[classes/:na]
	at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47) ~[spark-core-2.3.jar:na]
	at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:162) ~[spark-core-2.3.jar:na]
	at spark.webserver.JettyHandler.doHandle(JettyHandler.java:61) ~[spark-core-2.3.jar:na]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189) ~[jetty-server-9.3.2.v20150730.jar:9.3.2.v20150730]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.3.2.v20150730.jar:9.3.2.v20150730]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119) ~[jetty-server-9.3.2.v20150730.jar:9.3.2.v20150730]
	at org.eclipse.jetty.server.Server.handle(Server.java:517) ~[jetty-server-9.3.2.v20150730.jar:9.3.2.v20150730]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:302) ~[jetty-server-9.3.2.v20150730.jar:9.3.2.v20150730]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242) ~[jetty-server-9.3.2.v20150730.jar:9.3.2.v20150730]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245) ~[jetty-io-9.3.2.v20150730.jar:9.3.2.v20150730]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) ~[jetty-io-9.3.2.v20150730.jar:9.3.2.v20150730]
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75) ~[jetty-io-9.3.2.v20150730.jar:9.3.2.v20150730]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213) ~[jetty-util-9.3.2.v20150730.jar:9.3.2.v20150730]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147) ~[jetty-util-9.3.2.v20150730.jar:9.3.2.v20150730]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654) ~[jetty-util-9.3.2.v20150730.jar:9.3.2.v20150730]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572) ~[jetty-util-9.3.2.v20150730.jar:9.3.2.v20150730]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_60]
Caused by: org.hibernate.QueryException: query specified join fetching, but the owner of the fetched association was not present in the select list [FromElement{explicit,not a collection join,fetch join,fetch non-lazy properties,classAlias=order_1,role=com.pallasathenagroup.entities.hermes.OrderEntry.order,tableName=client_order,tableAlias=order1_,origin=order_entry orderentry0_,columns={orderentry0_.order_id ,className=com.pallasathenagroup.entities.hermes.Order}}] [SELECT COUNT(*                              ) FROM com.pallasathenagroup.entities.hermes.OrderEntry orderentry JOIN FETCH orderentry.order order_1 WHERE orderentry.product IN (SELECT s.id FROM com.pallasathenagroup.cte.ScopeCte s) AND (orderentry.paidPrice = :param_1 OR order_1.status = :param_2)]
	at org.hibernate.QueryException.generateQueryException(QueryException.java:120) ~[hibernate-core-5.2.1.Final.jar:5.2.1.Final]
	at org.hibernate.QueryException.wrapWithQueryString(QueryException.java:103) ~[hibernate-core-5.2.1.Final.jar:5.2.1.Final]
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.doCompile(QueryTranslatorImpl.java:218) ~[hibernate-core-5.2.1.Final.jar:5.2.1.Final]
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.compile(QueryTranslatorImpl.java:142) ~[hibernate-core-5.2.1.Final.jar:5.2.1.Final]
	at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:115) ~[hibernate-core-5.2.1.Final.jar:5.2.1.Final]
	at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:77) ~[hibernate-core-5.2.1.Final.jar:5.2.1.Final]
	at org.hibernate.engine.query.spi.QueryPlanCache.getHQLQueryPlan(QueryPlanCache.java:152) ~[hibernate-core-5.2.1.Final.jar:5.2.1.Final]
	at org.hibernate.internal.AbstractSharedSessionContract.getQueryPlan(AbstractSharedSessionContract.java:521) ~[hibernate-core-5.2.1.Final.jar:5.2.1.Final]
	at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:623) ~[hibernate-core-5.2.1.Final.jar:5.2.1.Final]
	... 24 common frames omitted
Caused by: org.hibernate.QueryException: query specified join fetching, but the owner of the fetched association was not present in the select list [FromElement{explicit,not a collection join,fetch join,fetch non-lazy properties,classAlias=order_1,role=com.pallasathenagroup.entities.hermes.OrderEntry.order,tableName=client_order,tableAlias=order1_,origin=order_entry orderentry0_,columns={orderentry0_.order_id ,className=com.pallasathenagroup.entities.hermes.Order}}]
	at org.hibernate.hql.internal.ast.tree.SelectClause.initializeExplicitSelectClause(SelectClause.java:214) ~[hibernate-core-5.2.1.Final.jar:5.2.1.Final]
	at org.hibernate.hql.internal.ast.HqlSqlWalker.useSelectClause(HqlSqlWalker.java:991) ~[hibernate-core-5.2.1.Final.jar:5.2.1.Final]
	at org.hibernate.hql.internal.ast.HqlSqlWalker.processQuery(HqlSqlWalker.java:759) ~[hibernate-core-5.2.1.Final.jar:5.2.1.Final]
	at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.query(HqlSqlBaseWalker.java:675) ~[hibernate-core-5.2.1.Final.jar:5.2.1.Final]
	at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.selectStatement(HqlSqlBaseWalker.java:311) ~[hibernate-core-5.2.1.Final.jar:5.2.1.Final]
	at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.statement(HqlSqlBaseWalker.java:259) ~[hibernate-core-5.2.1.Final.jar:5.2.1.Final]
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.analyze(QueryTranslatorImpl.java:262) ~[hibernate-core-5.2.1.Final.jar:5.2.1.Final]
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.doCompile(QueryTranslatorImpl.java:190) ~[hibernate-core-5.2.1.Final.jar:5.2.1.Final]
	... 30 common frames omitted
```

**Comment by beikov** [comment]
Sorry to say that, but you found a bug that can't be worked around that easily.
The problem is that I render through the FETCH keywords to the count and probably also the id queries which is wrong. The reason to why this came up just now is because the paginated queries normally don't get used with entities in the projection by our users, but with entity views.
Are you doing any updates on the entities? If not, I can guide you to using entity views if you want.
Otherwise you'd have to build a custom snapshot with a fix for that for now. Working on the fix already..

**Comment by JWGmeligMeyling** [comment]
I am used to using the newest snapshot, so that isn't a problem for me :wink: EntityViews is still something I have to read upon, I could probably use that here as I am not doing  any updates indeed. But for now I just disabled the fetch joins.

**Comment by beikov** [comment]
Ok, so basically, entity views are analogous to views in RDBMS sense.
You define an entity view(interface) which is the structure of the projection of an entity related query.
Let's for example consider the following entity views.

```
@EntityView(OrderEntry.class)
public interface OrderEntryView {

  @IdMapping
  public Integer getId();

  public String getDiscountCode();

  public PartnerSubview getGlobalPartner();

  public PartnerSubview getScopePartner();

  public OrderView getOrder();

}

@EntityView(Partner.class)
public interface PartnerSubview {
  @IdMapping
  public Integer getId();

  public String getName();
}

@EntityView(Order.class)
public interface OrderView {
  @IdMapping
  public Integer getId();

  public BigDecimal getAmount();
}
```

Every interface is a projection of an entity class. The following projections only make use of "implicit" mappings e.g. the property name is used as mapping, but you can define custom mappings with `@Mapping`. The mapping expression can be any JPQL expression like e.g. `CONCAT(discountCode, '-CODE')`

I hope this gives you the basic idea. You can also map sets, maps and other advanced stuff. Just ask if you have any questions.

**Comment by JWGmeligMeyling** [comment]
Thanks for solving the issue so quickly and your introduction to `EntityViews`. I'll continue to play with that tomorrow 😄
