### ISSUE TITLE
NullPointerException on CriteriaBuilderFactory instantiate

### ISSUE THREAD

**Issue by weblogichub** [Blazebit/blaze-persistence#344]
### Description
Just confugure and execute my application with Blaze
### Expected behavior
Successful CriteriaBuilderFactory instantiate
### Actual behavior

Caused by: java.lang.NullPointerException
	at com.blazebit.persistence.impl.hibernate.HibernateExtendedQuerySupport.getColumnTypes(HibernateExtendedQuerySupport.java:180)
	at com.blazebit.persistence.impl.EntityMetamodelImpl.<init>(EntityMetamodelImpl.java:89)
	at com.blazebit.persistence.impl.CriteriaBuilderFactoryImpl.<init>(CriteriaBuilderFactoryImpl.java:80)
	at com.blazebit.persistence.impl.CriteriaBuilderConfigurationImpl.createCriteriaBuilderFactory(CriteriaBuilderConfigurationImpl.java:543)
	at org.jtoro.meta.model.base.config.system.MetaModelBaseSystemConfig.createCriteriaBuilderFactory(MetaModelBaseSystemConfig.java:127)
	at org.jtoro.meta.model.base.config.system.MetaModelBaseSystemConfig$$EnhancerBySpringCGLIB$$3c762780.CGLIB$createCriteriaBuilderFactory$7(<generated>)
	at org.jtoro.meta.model.base.config.system.MetaModelBaseSystemConfig$$EnhancerBySpringCGLIB$$3c762780$$FastClassBySpringCGLIB$$5bfeb8d7.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:356)
	at org.jtoro.meta.model.base.config.system.MetaModelBaseSystemConfig$$EnhancerBySpringCGLIB$$3c762780.createCriteriaBuilderFactory(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)

### Steps to reproduce
Problem is here : Hibernate5Integrator
My app uses schemas, metadata.getDatabase() contains multiple namespaces
and metadata.getDatabase().getDefaultNamespace() has no tables

### Environment

Version:   1.2.0-Alpha2	         
JPA-Provider:  Hibernate 5.0.11.Final       
DBMS:               PostgreSQL 9.4.4
Application Server:  Application Server: Java SE, Spring Boot

**Comment by beikov** [comment]
Sorry to hear you are running into this problem. Can you confirm that you have entities with a TablePerClass inheritance strategy or @Formula in use?
This was reported already and was fixed on master: https://github.com/Blazebit/blaze-persistence/issues/336

**Comment by weblogichub** [comment]
No, only InheritanceType.JOINED used, no @Formula in use.
Simple domain, but use schema
@Table( name="sys_base_model_t", schema="system")
Just now i,m explore a way to configure hibernate Database.class implicitNamespace in my configuration.

**Comment by beikov** [comment]
I'm going to create a testcase for this to see if I can reproduce and fix the problem. I'll keep you updated.

**Comment by beikov** [comment]
I was able to reproduce it.

**Comment by weblogichub** [comment]
I a'm find workaround :

        LocalContainerEntityManagerFactoryBean factoryBean = new LocalContainerEntityManagerFactoryBean();
        factoryBean.setDataSource(dataSource());
        factoryBean.setPersistenceUnitName("system");
        properties.put(AvailableSettings.DEFAULT_SCHEMA, "system");
        factoryBean.setJpaProperties(properties);
....

But now next Exception :
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at com.blazebit.persistence.impl.JpaUtils.resolveFieldClass(JpaUtils.java:270)
	at com.blazebit.persistence.impl.EntityMetamodelImpl.<init>(EntityMetamodelImpl.java:77)
	at com.blazebit.persistence.impl.CriteriaBuilderFactoryImpl.<init>(CriteriaBuilderFactoryImpl.java:80)
	at com.blazebit.persistence.impl.CriteriaBuilderConfigurationImpl.createCriteriaBuilderFactory(CriteriaBuilderConfigurationImpl.java:543)

**Comment by beikov** [comment]
Huh? Can you show me what your entity model is? I have a feeling you are using hbm.xml or some detyped mapping.

**Comment by weblogichub** [comment]
I'm found error.
Problem ih here :
fieldClass = ReflectionUtils.getResolvedFieldTypeArguments(resolverBaseClass, field)[0];
ReflectionUtils.resolveTypeArguments(Class<?> concreteClass, Type type) just return new Class<?>[0];

resolverBaseClass = SysEntityModel
field = propertyList

@Entity
@Table( name="sys_entity_model_t", schema="system")
public class SysEntityModel extends SysEntityModelGen
{
// empty
}

@MappedSuperclass
public abstract class SysEntityModelGen
{
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "entity", targetEntity = SysEntityPropModel.class)
    private List propertyList;
}

Just correct field with type and Blaze started successfully
    private List<SysEntityPropModel> propertyList;

**Comment by weblogichub** [comment]
Correct :
private List<SysEntityPropModel> propertyList;

**Comment by weblogichub** [comment]
`    private List<SysEntityPropModel> propertyList;
`

**Comment by beikov** [comment]
I think I fixed your schema issue and I am also looking into the other one. You can expect these fixes in the next release which is planned for mid-March. Sorry for the trouble. Just tell us if you have any other problems :)

**Comment by weblogichub** [comment]
Thankee! 
Alpha is alpha.

**Comment by anthofo** [comment]
I'm facing the same problem with Alpha 2. I'll try with the last snapshot

**Comment by beikov** [comment]
Hope the current snapshot works for you. The treat support is nearly done so a new release shouldn't be far away.
