### ISSUE TITLE
Hibernate52Integrator could not be instantiated on Master

### ISSUE THREAD

**Issue by AFbenHassine** [Blazebit/blaze-persistence#354]
Exception in thread "main" 

```
Exception in thread "main" java.util.ServiceConfigurationError: org.hibernate.integrator.spi.Integrator: Provider com.blazebit.persistence.impl.hibernate.Hibernate52Integrator could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.loadJavaServices(ClassLoaderServiceImpl.java:459)
	at org.hibernate.integrator.internal.IntegratorServiceImpl.<init>(IntegratorServiceImpl.java:40)
	at org.hibernate.boot.registry.BootstrapServiceRegistryBuilder.build(BootstrapServiceRegistryBuilder.java:224)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.buildBootstrapServiceRegistry(EntityManagerFactoryBuilderImpl.java:405)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:195)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:170)
	at org.hibernate.jpa.boot.spi.Bootstrap.getEntityManagerFactoryBuilder(Bootstrap.java:76)
	at org.hibernate.jpa.HibernatePersistenceProvider.getEntityManagerFactoryBuilder(HibernatePersistenceProvider.java:181)
	at org.hibernate.jpa.HibernatePersistenceProvider.getEntityManagerFactoryBuilderOrNull(HibernatePersistenceProvider.java:129)
	at org.hibernate.jpa.HibernatePersistenceProvider.getEntityManagerFactoryBuilderOrNull(HibernatePersistenceProvider.java:71)
	at org.hibernate.jpa.HibernatePersistenceProvider.createEntityManagerFactory(HibernatePersistenceProvider.java:52)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
	at com.pallasathena.export.Exporter.main(Exporter.java:84)
Caused by: java.lang.NoClassDefFoundError: com/blazebit/persistence/impl/hibernate/TableNameFormatter
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	... 15 more
Caused by: java.lang.ClassNotFoundException: com.blazebit.persistence.impl.hibernate.TableNameFormatter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 20 more
```

### Description

I seem to have this issue on the newest master. Is this expected?

### Environment

Version:            Master
JPA: Hibernate
DBMS:             Postgres  
Application Server: Java SE

**Comment by beikov** [comment]
Seems like you haven't build the whole thing. There is a new class `TableNameFormatter` in the hibernate-base integration project that seems to be missing. How did you build the master?

**Comment by AFbenHassine** [comment]
I was building using `mvn install -DskipCheckstyle=true -DskipTests=true`.. I think I had some files left over from a failed build ( there are 2 checkstyle errors). After cleaning and rebuilding it now works... Sorry!

**Comment by beikov** [comment]
No problem. We are here to help. We already noticed the checkstyle errors, thanks for the hint.
