### ISSUE TITLE
Query substitution for where clause in CriteriaBuilder fails when EntityViewSetting is applied 

### ISSUE THREAD

**Issue by JWGmeligMeyling** [Blazebit/blaze-persistence#453]
### Description
I am trying to convert one of my CTE queries to utilise EntityViews. The query used to be constructed as follows:

```java
return scopeEntityManager.getRecursiveScopeChildrenCriteriaBuilder(start, OrderEntry.class)
            .from(OrderEntry.class).where("product").in()
                .from(ScopeCte.class, "s")
                .select("s.id")
                .end()
            .where("order.status").in(PAID_ORDER_STATUSSES)
            .fetch("order", "discountCode",  "globalPartner", "scopePartner")
            .orderBy("order.orderDateTime", false, true)
            .orderBy("id", false, true)
            .page(skip, limit)
            .getResultList();
```

This query works, though slow due all the fetch joins. Now I am trying to apply an EntityView setting to it, as follows:

```java
CriteriaBuilder<OrderEntry> orderEntryCriteriaBuilder = scopeEntityManager.getRecursiveScopeChildrenCriteriaBuilder(start, OrderEntry.class)
        .from(OrderEntry.class, "oe")
        .where("oe.product").in()
        .from(ScopeCte.class, "s")
        .select("s.id")
        .end()
        .where("oe.order.status").in(PAID_ORDER_STATUSSES)
        .orderBy("oe.order.orderDateTime", false, true)
        .orderBy("oe.id", false, true);

PaginatedCriteriaBuilder<OrderEntry> page = orderEntryCriteriaBuilder
        .page(skip, limit);

EntityViewSetting<OrderFeedEntry, PaginatedCriteriaBuilder<OrderFeedEntry>> setting =
        EntityViewSetting.create(OrderFeedEntry.class, skip, limit);

return entityViewManager.applySetting(setting, orderEntryCriteriaBuilder)
        .getResultList();
```

### Expected behavior
Succesful query output.

### Actual behavior
It fails with the following stack traces:

```
10:47:47,859 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (default task-6) SQL Error: 0, SQLState: 42703
10:47:47,859 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (default task-6) ERROR: column "product_1" does not exist
  Hint: Perhaps you meant to reference the column "orderentry0_.product_id".
  Position: 488
10:47:47,861 SEVERE [com.blazebit.persistence.impl.hibernate.HibernateExtendedQuerySupport] (default task-6) Could not execute the following SQL query: with recursive ScopeCte(id, ancestor_scope_id) AS(
select scope0_.scope_id as col_0_0_, scope0_.parent_scope_id as col_1_0_ from scope scope0_ where scope0_.scope_id=?
UNION ALL
select scope0_.scope_id as col_0_0_, scope0_.parent_scope_id as col_1_0_ from scope scope0_ cross join ScopeCte scopecte1_ where scope0_.parent_scope_id=scopecte1_.id
)
select count(*) as col_0_0_ from order_entry orderentry0_ inner join client_order order1_ on orderentry0_.order_id=order1_.order_id where (product_1 in (select scopecte2_.id from ScopeCte scopecte2_)) and (order1_.order_status in (? , ? , ?))
10:47:47,862 ERROR [org.hibernate.internal.ExceptionConverterImpl] (default task-6) HHH000337: Unable to mark for rollback on PersistenceException: : java.lang.IllegalStateException: ARJUNA016072: No such transaction!
	at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.setRollbackOnly(BaseTransaction.java:157)
	at com.arjuna.ats.jbossatx.BaseTransactionManagerDelegate.setRollbackOnly(BaseTransactionManagerDelegate.java:143)
	at org.hibernate.resource.transaction.backend.jta.internal.JtaTransactionAdapterTransactionManagerImpl.markRollbackOnly(JtaTransactionAdapterTransactionManagerImpl.java:100)
	at org.hibernate.resource.transaction.backend.jta.internal.JtaTransactionCoordinatorImpl$TransactionDriverControlImpl.markRollbackOnly(JtaTransactionCoordinatorImpl.java:430)
	at org.hibernate.engine.transaction.internal.TransactionImpl.setRollbackOnly(TransactionImpl.java:143)
	at org.hibernate.Transaction.markRollbackOnly(Transaction.java:68)
	at org.hibernate.internal.AbstractSharedSessionContract.markForRollbackOnly(AbstractSharedSessionContract.java:357)
	at org.hibernate.internal.ExceptionConverterImpl.handlePersistenceException(ExceptionConverterImpl.java:271)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:148)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:155)
	at com.blazebit.persistence.impl.hibernate.Hibernate52Access.convert(Hibernate52Access.java:136)
	at com.blazebit.persistence.impl.hibernate.HibernateExtendedQuerySupport.getSingleResult(HibernateExtendedQuerySupport.java:433)
	at com.blazebit.persistence.impl.plan.CustomSelectQueryPlan.getSingleResult(CustomSelectQueryPlan.java:61)
	at com.blazebit.persistence.impl.query.CustomSQLTypedQuery.getSingleResult(CustomSQLTypedQuery.java:52)
	at com.blazebit.persistence.impl.PaginatedTypedQuery.getResultList(PaginatedTypedQuery.java:73)
	at com.blazebit.persistence.impl.PaginatedCriteriaBuilderImpl.getResultList(PaginatedCriteriaBuilderImpl.java:222)
	at com.pallasathenagroup.entitymanagers.OrderEntryEntityManager.getOrderEntries(OrderEntryEntityManager.java:58)
	at com.pallasathenagroup.entitymanagers.OrderEntryEntityManager$Proxy$_$$_WeldSubclass.getOrderEntries(Unknown Source)
	at com.pallasathenagroup.iris.impl.ScopeResourceImpl.getOrderFeed(ScopeResourceImpl.java:300)
	at com.pallasathenagroup.iris.impl.ScopeResourceImpl$Proxy$_$$_WeldClientProxy.getOrderFeed(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:402)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:209)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:805)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

10:47:47,863 ERROR [com.pallasathenagroup.iris.providers.ThrowableMapper] (default task-6) org.hibernate.exception.SQLGrammarException: could not extract ResultSet (f8c80b6b-a51c-42c6-a805-6554b4572693): javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:147)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:155)
	at com.blazebit.persistence.impl.hibernate.Hibernate52Access.convert(Hibernate52Access.java:136)
	at com.blazebit.persistence.impl.hibernate.HibernateExtendedQuerySupport.getSingleResult(HibernateExtendedQuerySupport.java:433)
	at com.blazebit.persistence.impl.plan.CustomSelectQueryPlan.getSingleResult(CustomSelectQueryPlan.java:61)
	at com.blazebit.persistence.impl.query.CustomSQLTypedQuery.getSingleResult(CustomSQLTypedQuery.java:52)
	at com.blazebit.persistence.impl.PaginatedTypedQuery.getResultList(PaginatedTypedQuery.java:73)
	at com.blazebit.persistence.impl.PaginatedCriteriaBuilderImpl.getResultList(PaginatedCriteriaBuilderImpl.java:222)
	at com.pallasathenagroup.entitymanagers.OrderEntryEntityManager.getOrderEntries(OrderEntryEntityManager.java:58)
	at com.pallasathenagroup.entitymanagers.OrderEntryEntityManager$Proxy$_$$_WeldSubclass.getOrderEntries(Unknown Source)
	at com.pallasathenagroup.iris.impl.ScopeResourceImpl.getOrderFeed(ScopeResourceImpl.java:300)
	at com.pallasathenagroup.iris.impl.ScopeResourceImpl$Proxy$_$$_WeldClientProxy.getOrderFeed(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:402)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:209)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:805)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:106)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:111)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:97)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:80)
	at org.hibernate.loader.Loader.getResultSet(Loader.java:2123)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1911)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1887)
	at org.hibernate.loader.Loader.doQuery(Loader.java:932)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:349)
	at org.hibernate.loader.Loader.doList(Loader.java:2615)
	at org.hibernate.loader.Loader.doList(Loader.java:2598)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2430)
	at org.hibernate.loader.Loader.list(Loader.java:2425)
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:502)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:379)
	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:216)
	at com.blazebit.persistence.impl.hibernate.Hibernate52Access.performList(Hibernate52Access.java:101)
	at com.blazebit.persistence.impl.hibernate.HibernateExtendedQuerySupport.list(HibernateExtendedQuerySupport.java:460)
	at com.blazebit.persistence.impl.hibernate.HibernateExtendedQuerySupport.getSingleResult(HibernateExtendedQuerySupport.java:407)
	... 60 more
Caused by: org.postgresql.util.PSQLException: ERROR: column "product_1" does not exist
  Hint: Perhaps you meant to reference the column "orderentry0_.product_id".
  Position: 488
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:168)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:116)
	at org.jboss.jca.adapters.jdbc.WrappedPreparedStatement.executeQuery(WrappedPreparedStatement.java:504)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:71)
	... 75 more
```

It seems to fail when substituting the field names in the where clause, for at least the count(*) query used for pagination.

### Steps to reproduce

Unfortunately the domain for this issue is quite big. Perhaps you can give me some pointers to narrow this down to a more isolated test case? Or one of you already have an idea of whats going on here? Perhaps I should change the construction of my criteria builder?

### Environment

Version:            1.2.0-Alpha3
JPA-Provider:   5.2.10 Hibernate (updated from 5.0 shipped with Wildfly)
DBMS:               Postgres 9.5.3 with postgresql-9.4.1212 JDBC
Application Server: Wildfly 10

**Comment by beikov** [comment]
Seems like you are comparing an entity against ids which is partly allowed in Hibernate. Try use `where("oe.product.id").in()` instead.
If I remember correctly, Hibernate has some problematic cases when doing this kind of comparison.

**Comment by JWGmeligMeyling** [comment]
Worked as a charm! Thanks a lot! I always forget about that flaw...

**Comment by beikov** [comment]
You're welcome. I opened a follow up issue to validate the usage more strictly.
