### ISSUE TITLE
The given mapping constructor 'null' does not map to a constructor of the proxy class

### ISSUE THREAD

**Issue by JWGmeligMeyling** [Blazebit/blaze-persistence#456]
### Description

In my schema I have one recursive entity mapping, used for CTE queries. Initially I tried creating an entity view as follows:

```java
@EntityView(Scope.class)
@EntityViewInheritance
public interface ScopeWithParentsEntityView {

    @IdMapping
    Long getId();

    @Mapping("parent")
    ScopeWithParentsEntityView getParent();

}
```

But this fails with an circular dependency error. So I decided to remove the mapping and move it to the outer levels:

```java
public interface ScopeWithParentsEntityView {

    @IdMapping
    Long getId();

   // Other fields omitted
}
```

```java
@EntityView(Course.class)
@EntityViewInheritance
@EntityView(Company.class)
@EntityViewInheritance
public interface CompanyWithParentsEntityView extends ScopeWithParentsEntityView {

    @Mapping("CoCNumber")
    String getCoCNumber();

    @Mapping("VATNumber")
    String getVATNumber();

    @Mapping("locale")
    Locale getLocale();

}
```

```java
@EntityView(Institute.class)
@EntityViewInheritance
public interface InstituteWithParentsEntityView extends ScopeWithParentsEntityView {

    @Mapping("parent")
    CompanyWithParentsEntityView getParent();

}
```

I have a few more entity views that come in to play, but I think this should give a rough idea of the use case. Now I get a slightly different error.

```
15:49:20,800 ERROR [com.pallasathenagroup.hermes.providers.ThrowableMapper] (default task-9) The given mapping constructor 'null' does not map to a constructor of the proxy class: com.pallasathenagroup.entityviews.ProductWithParentsEntityView_0_ProductWithParentsEntityView_$$_javassist_entityview_ (5573860d-2dee-4a57-ab6b-f85e78eabcc5): java.lang.IllegalArgumentException: The given mapping constructor 'null' does not map to a constructor of the proxy class: com.pallasathenagroup.entityviews.ProductWithParentsEntityView_0_ProductWithParentsEntityView_$$_javassist_entityview_
	at com.blazebit.persistence.view.impl.proxy.ReflectionInstantiator.<init>(ReflectionInstantiator.java:43)
	at com.blazebit.persistence.view.impl.objectbuilder.ViewTypeObjectBuilderTemplate.createInstantiator(ViewTypeObjectBuilderTemplate.java:322)
	at com.blazebit.persistence.view.impl.objectbuilder.ViewTypeObjectBuilderTemplate.<init>(ViewTypeObjectBuilderTemplate.java:279)
	at com.blazebit.persistence.view.impl.objectbuilder.ViewTypeObjectBuilderTemplate.applySubviewMapping(ViewTypeObjectBuilderTemplate.java:576)
	at com.blazebit.persistence.view.impl.objectbuilder.ViewTypeObjectBuilderTemplate.applyMapping(ViewTypeObjectBuilderTemplate.java:521)
	at com.blazebit.persistence.view.impl.objectbuilder.ViewTypeObjectBuilderTemplate.<init>(ViewTypeObjectBuilderTemplate.java:243)
	at com.blazebit.persistence.view.impl.objectbuilder.ViewTypeObjectBuilderTemplate.applySubviewMapping(ViewTypeObjectBuilderTemplate.java:576)
	at com.blazebit.persistence.view.impl.objectbuilder.ViewTypeObjectBuilderTemplate.applyMapping(ViewTypeObjectBuilderTemplate.java:412)
	at com.blazebit.persistence.view.impl.objectbuilder.ViewTypeObjectBuilderTemplate.<init>(ViewTypeObjectBuilderTemplate.java:243)
	at com.blazebit.persistence.view.impl.objectbuilder.ViewTypeObjectBuilderTemplate.<init>(ViewTypeObjectBuilderTemplate.java:118)
	at com.blazebit.persistence.view.impl.objectbuilder.ViewTypeObjectBuilderTemplate$Key.createValue(ViewTypeObjectBuilderTemplate.java:1105)
	at com.blazebit.persistence.view.impl.EntityViewManagerImpl.getTemplate(EntityViewManagerImpl.java:344)
	at com.blazebit.persistence.view.impl.EntityViewManagerImpl.createObjectBuilder(EntityViewManagerImpl.java:317)
	at com.blazebit.persistence.view.impl.EntityViewManagerImpl.applyObjectBuilder(EntityViewManagerImpl.java:292)
	at com.blazebit.persistence.view.impl.EntityViewManagerImpl.applyObjectBuilder(EntityViewManagerImpl.java:287)
	at com.blazebit.persistence.view.impl.EntityViewSettingHelper.apply(EntityViewSettingHelper.java:71)
	at com.blazebit.persistence.view.impl.EntityViewManagerImpl.applySetting(EntityViewManagerImpl.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:100)
	at com.blazebit.persistence.view.EntityViewManager$133044130$Proxy$_$$_WeldClientProxy.applySetting(Unknown Source)
	at com.pallasathenagroup.entitymanagers.OrderEntityManager.findOrderWithOrderEntriesWithScopeParentsViewById(OrderEntityManager.java:47)
	at com.pallasathenagroup.entitymanagers.OrderEntityManager$Proxy$_$$_WeldSubclass.findOrderWithOrderEntriesWithScopeParentsViewById(Unknown Source)
	at com.pallasathenagroup.hermes.impl.OrderResourceImpl.getOrder(OrderResourceImpl.java:86)
	at com.pallasathenagroup.hermes.impl.OrderResourceImpl$Proxy$_$$_WeldClientProxy.getOrder(Unknown Source)
	at com.pallasathenagroup.hermes.impl.MyAthenaResourceImpl.getOrder(MyAthenaResourceImpl.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:402)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:209)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:805)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodException: com.pallasathenagroup.entityviews.ProductWithParentsEntityView_0_ProductWithParentsEntityView_$$_javassist_entityview_.<init>(java.lang.Long, java.lang.String, java.lang.String, java.lang.String, com.pallasathenagroup.entities.ScopePartner, java.math.BigDecimal, com.pallasathenagroup.entities.embeddables.ScopeProperties, com.pallasathenagroup.entities.Visibility, java.lang.String, com.pallasathenagroup.entities.CourseType, com.pallasathenagroup.entityviews.AthenaStudiesCourseWithParentsEntityView)
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at com.blazebit.persistence.view.impl.proxy.ReflectionInstantiator.<init>(ReflectionInstantiator.java:40)
	... 80 more
```

So the `ReflectionInstantiator` fails to instantiate the proxy with the given types. Looking at the contents of the parameterTypes parameter I observe that the parameters should be:

```
parameterTypes = {Class[11]@18474} 
 0 = {Class@258} "class java.lang.Long"
 1 = {Class@328} "class java.lang.String"
 2 = {Class@328} "class java.lang.String"
 3 = {Class@328} "class java.lang.String"
 4 = {Class@12208} "class com.pallasathenagroup.entities.ScopePartner"
 5 = {Class@1780} "class java.math.BigDecimal"
 6 = {Class@13114} "class com.pallasathenagroup.entities.embeddables.ScopeProperties"
 7 = {Class@13174} "class com.pallasathenagroup.entities.Visibility"
 8 = {Class@328} "class java.lang.String"
 9 = {Class@13113} "class com.pallasathenagroup.entities.CourseType"
 10 = {Class@14822} "interface com.pallasathenagroup.entityviews.AthenaStudiesCourseWithParentsEntityView"
```

The parameters on the declared constructor of the proxy are however as follows:

```
parameterTypes = {Class[11]@18547} 
 0 = {Class@328} "class java.lang.String"
 1 = {Class@328} "class java.lang.String"
 2 = {Class@258} "class java.lang.Long"
 3 = {Class@328} "class java.lang.String"
 4 = {Class@12208} "class com.pallasathenagroup.entities.ScopePartner"
 5 = {Class@1780} "class java.math.BigDecimal"
 6 = {Class@13114} "class com.pallasathenagroup.entities.embeddables.ScopeProperties"
 7 = {Class@13174} "class com.pallasathenagroup.entities.Visibility"
 8 = {Class@328} "class java.lang.String"
 9 = {Class@13113} "class com.pallasathenagroup.entities.CourseType"
 10 = {Class@14822} "interface com.pallasathenagroup.entityviews.AthenaStudiesCourseWithParentsEntityView"
```

I.e. all the parameters seem to be there, but in a different order. Is this because my mapping is incorrect? Or is this caused by another problem, and should my current workaround work?

### Environment

Version: 1.2.0-Alpha3
JPA-Provider: 5.2.10 Hibernate (updated from 5.0 shipped with Wildfly)
DBMS: Postgres 9.5.3 with postgresql-9.4.1212 JDBC
Application Server: Wildfly 10

**Comment by beikov** [comment]
I think this should fail validation. The thing is, you can't have a circular mapping which this would introduce. With CTEs you can fetch all tree nodes efficiently, which you can map with entity views, but the tree structure would have to be built separately. Your CTE entity already looks quite like the view you are trying to map, why not use that type? That way hibernate takes care of building the references and you just have to find the root object in the result list.

**Comment by JWGmeligMeyling** [comment]
My structure is as follows:

A is abstract
AA extends A
BA extends A, has a parent AA
CA extends A, has a parent BA

B extends A and is abstract
DB extends B, has a parent CA

I have changed my EntityViews such that there is no circular dependency anymore:

Thus:

AView -> no inheritance, only mappings
AAView -> extends AView
BAView -> Extends AView, maps parent to AAView
CAView -> Extends AView, maps parent to BAView
DAView -> Extends BView which extends AView, maps parent to CAView

When I now load my CAViews it just loads fine and joins the BAViews and AAViews as well. But apparently the situation for the DAView is so complex, it fails to unload the proxy (even though all the parameters have been resolved, just in the wrong order).

Now I am not sure whether that is because I would like to fetch a DAView based on a DA for which I know only that it is a type of B (eg. that it fails on the InheritanceMapping). But it seems its not related to the inhertitance mapping at all, as it already works up to three levels deep. So I find it kind of odd that the first four parameters get ordered wrong in the array...

**Comment by beikov** [comment]
Well the problem might be a different one, but it would be good if you could produce a test case. Can you maybe try to copy your model, reproduce the issue and step by step try to remove things that seem unrelevant until you find the essence of the problem?
Here is a [template](https://github.com/Blazebit/blaze-persistence-test-case-template) which you can use for defining the testcase. Just post a ZIP here or create a PR on the test-case-template project. You can also create the testcase directly in the `entity-view-testsuite` project and post a PR for this repository.

**Comment by JWGmeligMeyling** [comment]
Ill try to reproduce the issue in a test case!


Jan-Willem


Op 26 okt. 2017 om 19:10 heeft Christian Beikov <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Well the problem might be a different one, but it would be good if you could produce a test case. Can you maybe try to copy your model, reproduce the issue and step by step try to remove things that seem unrelevant until you find the essence of the problem?
Here is a template<https://github.com/Blazebit/blaze-persistence-test-case-template> which you can use for defining the testcase. Just post a ZIP here or create a PR on the test-case-template project. You can also create the testcase directly in the entity-view-testsuite project and post a PR for this repository.

**Comment by JWGmeligMeyling** [comment]
I have observed that the parameters property used to construct the property are created in  [`ViewTypeObjectBuilderTemplate`](https://github.com/Blazebit/blaze-persistence/blob/1.2.0-Alpha3/entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/ViewTypeObjectBuilderTemplate.java), which stores the attributes in a [LinkedHashMap](https://github.com/Blazebit/blaze-persistence/blob/1.2.0-Alpha3/entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/ViewTypeObjectBuilderTemplate.java#L173) (sorted by insertion order), and [inserts the IdAttribute of the view first](https://github.com/Blazebit/blaze-persistence/blob/1.2.0-Alpha3/entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/objectbuilder/ViewTypeObjectBuilderTemplate.java#L208-L221), putting my Long field at the start of the list. In `ManagedViewTypeImpl` however, the properties are collected in a [`TreeMap`](https://github.com/Blazebit/blaze-persistence/blob/master/entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/metamodel/ManagedViewTypeImpl.java#L76-L77) (sorted by natural order). This eventually causes the misalignment of the parameter types and is why the proxy constructor fails to be invoked.

Does this ring a bell? I am wondering how this works in "good weather" cases?

Still working on a test case by the way, just stepping through the code now.

**Comment by beikov** [comment]
`ManagedViewType` is the metamodel and the attributes within there are ordered by the natural sort order of the attribute names. That you observed correctly. In the `ViewTypeObjectBuilderTemplate` the attributes are iterated in that natural sort order and put into the `LinkedHashMap` which basically guarantees the same order.
The proxy constructor treats the id attribute specially just like the `ViewTypeObjectBuilderTemplate` by considering it being the first attribute.
The missalignment as far as I can think of, can only happen because of the undetected cycle in your model, but I can't say for sure unless I see the code/testcase.

**Comment by beikov** [comment]
@JWGmeligMeyling what is the status on this? Is there a branch or some model I can use to try to reproduce it or do you have a test case already?

**Comment by JWGmeligMeyling** [comment]
I am still trying to reproduce the issue, but my test cases seem to fail on different issues instead. Lets look into those issues first, while I keep debugging / trying to reproduce this issue.

**Comment by beikov** [comment]
Thank you for the great work!
I will take a look later today and hopefully even fix these issues ;)

**Comment by JWGmeligMeyling** [comment]
Interesting observation: it tries to initialise a `ProductWithParentsEntityView_0_ProductWithParentsEntityView` where the proxy obviously should've been of type `SubType0_ProductWithParentsEntityView`.
