### ISSUE TITLE
Cyclic dependency check throws unnecessary when binding multiple fields from a join product to a CTE

### ISSUE THREAD

**Issue by JWGmeligMeyling** [Blazebit/blaze-persistence#514]
### Description

Cyclic dependency check throws unnecessary when binding multiple fields from a join product to a CTE.

As part of a larger CTE query, the following CTE segment is the part that throws an error:

```java
            .with(AccumulatedIncomeForecastCte.class)
                .from(IncomeForecastCte.class, "a")
                .innerJoinOn(CollegeYearCte.class, "cycte").on("a.orderDateTime")
                    .betweenExpression("cycte.collegeYearStart").andExpression("cycte.collegeYearEnd").end()
                .leftJoinOn(IncomeForecastCte.class, "b").on("b.orderDateTime")
                    .betweenExpression("cycte.collegeYearStart").andExpression("a.orderDateTime").end()
                .bind("orderDateTime").select("a.orderDateTime")
                .bind("realisedRevenue").select("MIN(a.realisedRevenue)")
                .bind("accumulatedRevenue").select("SUM(b.realisedRevenue)") // This is the problematic reference
                .bind("projectedRevenue").select("MIN(a.projectedRevenue)")
                .bind("accumulatedProjectedRevenue").select("SUM(b.projectedRevenue)")
                .groupBy("a.orderDateTime")
            .end()
            .from(AccumulatedIncomeForecastCte.class)
            .getResultList();
```

Fails with:

```
Exception in thread "main" java.lang.IllegalStateException: Cyclic join dependency: [com.blazebit.persistence.impl.JoinNode@729c8def, com.blazebit.persistence.impl.JoinNode@261f5a45, com.blazebit.persistence.impl.JoinNode@62f305bc]
	at com.blazebit.persistence.impl.JoinManager.updateClauseDependencies(JoinManager.java:2258)
	at com.blazebit.persistence.impl.JoinManager.updateClauseDependencies(JoinManager.java:2265)
	at com.blazebit.persistence.impl.JoinManager.updateClauseDependencies(JoinManager.java:2265)
	at com.blazebit.persistence.impl.JoinManager.implicitJoin(JoinManager.java:1724)
	at com.blazebit.persistence.impl.JoinManager.implicitJoin(JoinManager.java:1394)
	at com.blazebit.persistence.impl.JoinVisitor.visit(JoinVisitor.java:78)
	at com.blazebit.persistence.impl.JoinVisitor.visit(JoinVisitor.java:70)
	at com.blazebit.persistence.impl.expression.PathExpression.accept(PathExpression.java:74)
	at com.blazebit.persistence.impl.expression.VisitorAdapter.visit(VisitorAdapter.java:105)
	at com.blazebit.persistence.impl.JoinVisitor.visit(JoinVisitor.java:119)
	at com.blazebit.persistence.impl.expression.AggregateExpression.accept(AggregateExpression.java:71)
	at com.blazebit.persistence.impl.SelectManager.acceptVisitor(SelectManager.java:174)
	at com.blazebit.persistence.impl.AbstractCommonQueryBuilder.applyImplicitJoins(AbstractCommonQueryBuilder.java:1401)
	at com.blazebit.persistence.impl.AbstractCommonQueryBuilder.prepareAndCheck(AbstractCommonQueryBuilder.java:1811)
	at com.blazebit.persistence.impl.AbstractCTECriteriaBuilder.prepareAndCheck(AbstractCTECriteriaBuilder.java:172)
	at com.blazebit.persistence.impl.AbstractCTECriteriaBuilder.createCTEInfo(AbstractCTECriteriaBuilder.java:181)
	at com.blazebit.persistence.impl.CTEManager.onBuilderEnded(CTEManager.java:164)
	at com.blazebit.persistence.impl.AbstractCTECriteriaBuilder.end(AbstractCTECriteriaBuilder.java:160)
```

When the second join is removed from the query (eg. by moving its cross product into another temporary CTE) the query works fine.

### Environment

Version:            1.2.0.Alpha3 
JPA-Provider:       5.2.12
DBMS:               
Application Server:

**Comment by JWGmeligMeyling** [comment]
This fix seems to already be in my development build of 1.2.0.Alpha3. I'll try to create a reproduction test case.

**Comment by JWGmeligMeyling** [comment]
Still working on a reproducer, I have a query that always fails within my domain but still trying project the issue on the domain that stays as closest to the one already available in the test suite.

Meanwhile I have been experimenting with a patch. What do you guys think of this? 

```diff
diff --git a/core/impl/src/main/java/com/blazebit/persistence/impl/JoinManager.java b/core/impl/src/main/java/com/blazebit/persistence/impl/JoinManager.java
index 0fe0120..ce84f8d 100644
--- a/core/impl/src/main/java/com/blazebit/persistence/impl/JoinManager.java
+++ b/core/impl/src/main/java/com/blazebit/persistence/impl/JoinManager.java
@@ -73,6 +73,7 @@ import java.util.ArrayList;
 import java.util.Arrays;
 import java.util.Collections;
 import java.util.HashSet;
+import java.util.HashMap;
 import java.util.IdentityHashMap;
 import java.util.Iterator;
 import java.util.LinkedHashSet;
@@ -1720,7 +1721,7 @@ public class JoinManager extends AbstractManager<ExpressionModifier> {
 
             // Don't forget to update the clause dependencies!!
             if (fromClause != null) {
-                updateClauseDependencies(result.baseNode, fromClause, new HashSet<JoinNode>());
+                updateClauseDependencies(result.baseNode, fromClause, new HashMap<JoinNode, ClauseType>());
             }
 
             if (result.isLazy()) {
@@ -2251,10 +2252,11 @@ public class JoinManager extends AbstractManager<ExpressionModifier> {
         return new JoinResult(newBaseNode, field == null ? null : Arrays.asList(field), type, lazy);
     }
 
-    private void updateClauseDependencies(JoinNode baseNode, ClauseType clauseDependency, Set<JoinNode> seenNodes) {
-        if (!seenNodes.add(baseNode)) {
+    private void updateClauseDependencies(JoinNode baseNode, ClauseType clauseDependency, Map<JoinNode, ClauseType> seenNodes) {
+        ClauseType formerValue = seenNodes.put(baseNode, clauseDependency);
+        if (formerValue != null && !formerValue.equals(clauseDependency)) {
             // Cyclic dependency
-            throw new IllegalStateException("Cyclic join dependency: " + seenNodes);
+            throw new IllegalStateException(String.format("Cyclic join dependency %s as %s in %s", baseNode, clauseDependency, seenNodes));
         }
 
         JoinNode current = baseNode;
```
