### ISSUE TITLE
EntityMetamodel instantiation fails on Blaze-persist Alpha4

### ISSUE THREAD

**Issue by JWGmeligMeyling** [Blazebit/blaze-persistence#518]
EntityMetamodel instantiation fails on Blaze-persist Alpha4. In this case it fails on finding the id property of a referenced type for which the id property is defined in the super class.

(PartnerDiscountCode references GlobalPartner which extends Partner which has the id property).

The stack trace is as follows:

```
org.hibernate.QueryException: could not resolve property: partner.id of: com.pallasathenagroup.entities.PartnerDiscountCode

	at org.hibernate.persister.entity.AbstractPropertyMapping.propertyException(AbstractPropertyMapping.java:62)
	at org.hibernate.persister.entity.AbstractPropertyMapping.toType(AbstractPropertyMapping.java:56)
	at org.hibernate.persister.entity.AbstractEntityPersister.getPropertyType(AbstractEntityPersister.java:4579)
	at com.blazebit.persistence.impl.hibernate.HibernateJpaProvider.isForeignJoinColumn(HibernateJpaProvider.java:275)
	at com.blazebit.persistence.impl.EntityMetamodelImpl$AttributeEntry.<init>(EntityMetamodelImpl.java:505)
	at com.blazebit.persistence.impl.EntityMetamodelImpl.<init>(EntityMetamodelImpl.java:112)
	at com.blazebit.persistence.impl.CriteriaBuilderFactoryImpl.<init>(CriteriaBuilderFactoryImpl.java:106)
	at com.blazebit.persistence.impl.CriteriaBuilderConfigurationImpl.createCriteriaBuilderFactory(CriteriaBuilderConfigurationImpl.java:601)
	at com.pallasathenagroup.entitymanagers.AbstractEntityManagerTest.initializeEntityManagerFactory(AbstractEntityManagerTest.java:71)
```

### Environment

Version:            1.2.0-alpha4
JPA-Provider:       Hibernate 5.2.12
DBMS:               Postgresql 9.5
Application Server: Wildfly 10

**Comment by beikov** [comment]
Thanks, gonna take a look at that later today.

**Comment by beikov** [comment]
Could you maybe explain the mapping to me? I used the following and the model build succeeded.

```
    @Entity
    public static class PartnerDiscountCode {
        @Id
        @GeneratedValue
        private Long id;
        @JoinColumn(name = "partner_id")
        @ManyToOne(fetch = FetchType.LAZY)
        private GlobalPartner partner;

    }

    @Entity
    public static abstract class Partner {
        @Id
        private Long id;
    }

    @Entity
    public static class GlobalPartner extends Partner {
    }
```

**Comment by JWGmeligMeyling** [comment]
These are the entities: https://gist.github.com/JWGmeligMeyling/b1e700b765600a67c77349fba9b12047

**Comment by JWGmeligMeyling** [comment]
Perhaps the table per class inheritance strategy?

**Comment by beikov** [comment]
Thanks, have a reproducer now. Investigating the reasons now.

**Comment by JWGmeligMeyling** [comment]
Thanks! 👍
