### ISSUE TITLE
Non-PK (unique) referencedColumnName in JoinColumn leads to exception while building CriteriaBuilderFactoryProducer

### ISSUE THREAD

**Issue by JWGmeligMeyling** [Blazebit/blaze-persistence#526]
Given the entities:

```java
public class PaynlTransaction extends IdIdentifiable<Long> implements Comparable<PaynlTransaction> {

    @Id
    @Column(name = "order_entry_id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotEmpty
    @NaturalId
    @Column(name = "transaction_id", nullable = false, unique = true)
    private String transactionId;

```

And:

```java
@Getter
@Setter
@Entity
@Table(name = "client_order_clearing_date")
public class ClientOrderClearingDate extends IdIdentifiable<Long> implements TableView {

    @Id
    private Long id;

    @MapsId
    @OneToOne
    @JoinColumn(name = "order_id")
    private Order order;

    @OneToOne
    @JoinColumn(name = "transaction_id", referencedColumnName = "transaction_id")
    private PaynlTransaction paynlTransaction;

    @Column(name = "clearing_date")
    private LocalDate clearingDate;

    @Column(name = "invoice_date")
    private LocalDate invoiceDate;
}

```

Initialising the CriteriaBuilderFactoryProducer results in the following exception:

```
Caused by: org.hibernate.QueryException: could not resolve property: paynlTransaction.id of: com.pallasathenagroup.entities.views.ClientOrderClearingDate
	at org.hibernate.persister.entity.AbstractPropertyMapping.propertyException(AbstractPropertyMapping.java:62)
	at org.hibernate.persister.entity.AbstractPropertyMapping.toType(AbstractPropertyMapping.java:56)
	at org.hibernate.persister.entity.AbstractEntityPersister.getPropertyType(AbstractEntityPersister.java:4579)
	at com.blazebit.persistence.impl.hibernate.HibernateJpaProvider.isForeignJoinColumn(HibernateJpaProvider.java:276)
	at com.blazebit.persistence.impl.EntityMetamodelImpl$AttributeEntry.<init>(EntityMetamodelImpl.java:505)
	at com.blazebit.persistence.impl.EntityMetamodelImpl.<init>(EntityMetamodelImpl.java:112)
	at com.blazebit.persistence.impl.CriteriaBuilderFactoryImpl.<init>(CriteriaBuilderFactoryImpl.java:106)
	at com.blazebit.persistence.impl.CriteriaBuilderConfigurationImpl.createCriteriaBuilderFactory(CriteriaBuilderConfigurationImpl.java:601)
	at com.pallasathenagroup.iris.producers.CriteriaBuilderFactoryProducer.init(CriteriaBuilderFactoryProducer.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.as.ee.component.ManagedReferenceLifecycleMethodInterceptor.processInvocation(ManagedReferenceLifecycleMethodInterceptor.java:96)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
	at org.jboss.as.weld.ejb.Jsr299BindingsInterceptor.doLifecycleInterception(Jsr299BindingsInterceptor.java:114)
	at org.jboss.as.weld.ejb.Jsr299BindingsInterceptor.processInvocation(Jsr299BindingsInterceptor.java:103)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
	at org.jboss.invocation.InterceptorContext$Invocation.proceed(InterceptorContext.java:437)
	at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:73)
	at org.jboss.as.weld.ejb.EjbRequestScopeActivationInterceptor.processInvocation(EjbRequestScopeActivationInterceptor.java:83)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
	at org.jboss.as.weld.injection.WeldInjectionInterceptor.processInvocation(WeldInjectionInterceptor.java:53)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
	at org.jboss.as.ee.component.ManagedReferenceFieldInjectionInterceptorFactory$ManagedReferenceFieldInjectionInterceptor.processInvocation(ManagedReferenceFieldInjectionInterceptorFactory.java:107)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
	at org.jboss.as.ee.component.AroundConstructInterceptorFactory$1.processInvocation(AroundConstructInterceptorFactory.java:28)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
	at org.jboss.as.weld.injection.WeldInterceptorInjectionInterceptor.processInvocation(WeldInterceptorInjectionInterceptor.java:56)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
	at org.jboss.as.weld.ejb.Jsr299BindingsCreateInterceptor.processInvocation(Jsr299BindingsCreateInterceptor.java:100)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
	at org.jboss.as.ee.component.NamespaceContextInterceptor.processInvocation(NamespaceContextInterceptor.java:50)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:275)
	... 29 more
```

Now, based on the underlying code where it fails it is hard to see whether this is actually a problem in Blaze-persist 1.2.0-Alpha4 or Hibernate 5.2.12. And it can even be the case that my mapping is incorrect. But what I do know is that this issue is non-reproducible under Alpha3, and currently only occurs under Alpha4.

### Environment

Version:            current master
JPA-Provider:       Hibernate 5.2.12
DBMS:               Postgresql
Application Server: Wildfly

**Comment by JWGmeligMeyling** [comment]
Easily worked around the issue by the way. So no blocker for me right now. I'll finish my other work and I hope to submit a reproducer, or even a fix, somewhere tomorrow 😄  Unless you're first of course 😉

**Comment by beikov** [comment]
I'll leave that to you ;)

**Comment by JWGmeligMeyling** [comment]
Proper implementation for this requires access to:

```java
((HashMap) ((SingleTableEntityPersister) entityPersister).propertyMapping.typesByPropertyPath).keySet()
```

Which returns all property paths including derived properties (ie. `id`, `book`, `book.isbn`). 
These properties have protected visibility and can't be accessed through public methods (other than brute-forcing the `AbstractEntityPersister#getPropertyType(name)` method). Its either accessing that or reconstructing it by duplicating the about 500 lines of code in Hibernate that fill this thing.

@beikov I think that the best we can do here is remain the existing logic (that assumes the id as RHS), but catch the exception and simply ignore it. Or  would you rather obtain access to `typesByPropertyPath` through reflection for now, and request public access to the `PropertyMapping` through the `AbstractEntityPersister` in a Hibernate issue?

**Comment by beikov** [comment]
Why would we require access to the map? Every *ToOne association must have a join column. The only thing we have to check is if that join column refers to the primary key or to a unique key. Maybe you can share what you have in mind so I understand better why you think this is necessary?

**Comment by JWGmeligMeyling** [comment]
For this optimisation to work, the `AttributeEntry` needs to be created with a property that is resolvable by `AbstractEntityPersister#getPropertyType(name)`. The code below is used for that:

```java
EntityType<?> fieldEntityType = delegate.entity(fieldType);
SingularAttribute<?, ?> idAttribute = JpaMetamodelUtils.getIdAttribute(fieldEntityType);
Class<?> idType = JpaMetamodelUtils.resolveFieldClass(fieldType, idAttribute);
String idPath = attribute.getName() + "." + idAttribute.getName();
attributeMap.put(idPath, new AttributeEntry(jpaProvider, t, idAttribute, idPath, idType, Arrays.asList(attribute, idAttribute)));
```

The exception happens in `AttributeEntry` and is Hibernate specific. To make matters worse, it is not a very descriptive error type, namely a `QueryException`. Without access to the Hibernate classpath in this module, we would end up with something like:


```java
EntityType<?> fieldEntityType = delegate.entity(fieldType);
SingularAttribute<?, ?> idAttribute = JpaMetamodelUtils.getIdAttribute(fieldEntityType);
Class<?> idType = JpaMetamodelUtils.resolveFieldClass(fieldType, idAttribute);
String idPath = attribute.getName() + "." + idAttribute.getName();
try {
     attributeMap.put(idPath, new AttributeEntry(jpaProvider, t, idAttribute, idPath, idType, Arrays.asList(attribute, idAttribute)));
} catch (Exception exception) {
// Ignore, non-identity join columns are currently not optimised
}
```

Actually, there are multiple valid paths for `idPath`, and it is very well possible that this is not the IdentifierProperty (for example in the case of a non-primary / natural id join column).
`AbstractEntityPersister#getPropertyType(name)` returns the values from `AbstractEntityPersister.propertyMapping`, which is initialised through `initPropertyPaths` in `AbstractEntityPersisterpostConstruct`.  The method does the following:

```java
	protected void initPropertyPaths(Mapping mapping) throws MappingException {
		initOrdinaryPropertyPaths(mapping);
		initOrdinaryPropertyPaths(mapping); //do two passes, for collection property-ref!
		initIdentifierPropertyPaths(mapping);
		if ( entityMetamodel.isPolymorphic() ) {
			initDiscriminatorPropertyPath( mapping );
		}
	}


	private void initOrdinaryPropertyPaths(Mapping mapping) throws MappingException {
		for ( int i = 0; i < getSubclassPropertyNameClosure().length; i++ ) {
			propertyMapping.initPropertyPaths( getSubclassPropertyNameClosure()[i],
					getSubclassPropertyTypeClosure()[i],
					getSubclassPropertyColumnNameClosure()[i],
					getSubclassPropertyColumnReaderClosure()[i],
					getSubclassPropertyColumnReaderTemplateClosure()[i],
					getSubclassPropertyFormulaTemplateClosure()[i],
					mapping );
		}
	}

	private void initIdentifierPropertyPaths(Mapping mapping) throws MappingException {
		String idProp = getIdentifierPropertyName();
		if ( idProp != null ) {
			propertyMapping.initPropertyPaths( idProp, getIdentifierType(), getIdentifierColumnNames(),
					getIdentifierColumnReaders(), getIdentifierColumnReaderTemplates(), null, mapping );
		}
		if ( entityMetamodel.getIdentifierProperty().isEmbedded() ) {
			propertyMapping.initPropertyPaths( null, getIdentifierType(), getIdentifierColumnNames(),
					getIdentifierColumnReaders(), getIdentifierColumnReaderTemplates(), null, mapping );
		}
		if ( ! entityMetamodel.hasNonIdentifierPropertyNamedId() ) {
			propertyMapping.initPropertyPaths( ENTITY_ID, getIdentifierType(), getIdentifierColumnNames(),
					getIdentifierColumnReaders(), getIdentifierColumnReaderTemplates(), null, mapping );
		}
	}

	private void initDiscriminatorPropertyPath(Mapping mapping) throws MappingException {
		propertyMapping.initPropertyPaths( ENTITY_CLASS,
				getDiscriminatorType(),
				new String[]{getDiscriminatorColumnName()},
				new String[]{getDiscriminatorColumnReaders()},
				new String[]{getDiscriminatorColumnReaderTemplate()},
				new String[]{getDiscriminatorFormulaTemplate()},
				getFactory() );
	}

	protected void initPropertyPaths(Mapping mapping) throws MappingException {
		initOrdinaryPropertyPaths(mapping);
		initOrdinaryPropertyPaths(mapping); //do two passes, for collection property-ref!
		initIdentifierPropertyPaths(mapping);
		if ( entityMetamodel.isPolymorphic() ) {
			initDiscriminatorPropertyPath( mapping );
		}
	}
```

As you see the code to compute all possible property paths is quite extensive. But by passing all these property paths to our attribute map we're able to eliminate unnecessary joins.

**Comment by beikov** [comment]
We could catch the exception during model querying in the hibernate specific code and throw a custom exception. The EntityMetamodel code then catches that and tries other unique key properties instead of the primary key one. IMO that shouldn't be too expensive.
