### ISSUE TITLE
SimpleDatabase initialisation fails for types with AttributeConverters

### ISSUE THREAD

**Issue by JWGmeligMeyling** [Blazebit/blaze-persistence#528]
Given the entity:

```java
@Getter
@Setter
@ToString
@Entity
@Table(name = "course_group_timeslot_summary")
public class CourseGroupTimeSlotSummary extends IdIdentifiable<Long> implements TableView {

    @Id
    @Column(name = "scope_id", insertable = false, updatable = false)
    private Long id;

    @Column(name = "course_start", insertable = false, updatable = false)
    private LocalDateTime courseStart;

    @Column(name = "course_end", insertable = false, updatable = false)
    private LocalDateTime courseEnd;

    @Column(name = "month", insertable = false, updatable = false)
    @Convert(converter = YearMonthAttributeConverter.class)
    private YearMonth month;

}
```

And the `AttributeConverter`:

```java
@Converter
public class YearMonthAttributeConverter implements AttributeConverter<YearMonth, LocalDateTime> {

    @Override
    public LocalDateTime convertToDatabaseColumn(YearMonth attribute) {
        return attribute.atDay(1).atStartOfDay();
    }

    @Override
    public YearMonth convertToEntityAttribute(LocalDateTime dbData) {
        return YearMonth.from(dbData);
    }

}
```

Bootstrapping the session factory fails with:

```
javax.persistence.PersistenceException: [PersistenceUnit: athena-test] Unable to build Hibernate SessionFactory

	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.persistenceException(EntityManagerFactoryBuilderImpl.java:967)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:892)
	at org.hibernate.jpa.HibernatePersistenceProvider.createEntityManagerFactory(HibernatePersistenceProvider.java:58)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
	at com.pallasathenagroup.entitymanagers.AbstractEntityManagerTest.initializeEntityManagerFactory(AbstractEntityManagerTest.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.hibernate.MappingException: No Dialect mapping for JDBC type: 2016949136
	at org.hibernate.dialect.TypeNames.get(TypeNames.java:70)
	at org.hibernate.dialect.TypeNames.get(TypeNames.java:101)
	at org.hibernate.dialect.Dialect.getTypeName(Dialect.java:346)
	at org.hibernate.mapping.Column.getSqlType(Column.java:231)
	at com.blazebit.persistence.impl.hibernate.SimpleDatabase.<init>(SimpleDatabase.java:49)
	at com.blazebit.persistence.impl.hibernate.Hibernate52Integrator.integrate(Hibernate52Integrator.java:54)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:282)
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:452)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:889)
	... 18 more
```

### Environment

Version:            1.2.0-Alpha4 (master)
JPA-Provider:       Hibernate 5.2.12
DBMS:               PostgreSQL 
Application Server: WildFly

**Comment by JWGmeligMeyling** [comment]
Nevermind, after stepping through the code I think this is a bug in Hibernate instead...

**Comment by beikov** [comment]
So I analyzed this further and my findings were that Hibernate would set the value via `setObject` on a prepared statement in this case. The problem is, that you have a user type `YearMonth` with a converter, that converts to a type(`LocalDateTime`) Hibernate treats like an JDBC object type. Not sure what's going on here in Hibernate, but this is most definitely a bug we can't properly work around. I'm not even sure if persisiting with this setup would work. If it does, you might just be lucky that the JDBC driver accepts `LocalDateTime` in `setObject`, but as far as I can tell, this is something we can't workaround at all.

**Comment by MichaelF25** [comment]
So what's the workaround for this? I am facing the same issue in my Spring Boot 2.5.14 based app which uses Hibernate 5.4.33.

**Comment by beikov** [comment]
AFAICS, the workaround would be to use `java.sql.Timestamp` instead of `LocalDateTime` in your converter.

**Comment by jwgmeligmeyling** [comment]
I started using a custom type for YearMonth mappings: YearMonthTimestampType from https://github.com/vladmihalcea/hibernate-types/blob/master/hibernate-types-52/src/main/java/com/vladmihalcea/hibernate/type/basic/YearMonthTimestampType.java

**Comment by MichaelF25** [comment]
Thx for you fast replies! The thing is, in my project I use type-safe ID value types with respective attribute converters as a replacement for `@ManyToOne` annotated properties. The concept is described here : http://odrotbohm.de/2021/02/Architecturally-evident-code-with-jMolecules/

Since we are also already using a custom `Dialect` implementation, maybe a workaround can be established there by overriding the `getTypeName()` method.

**Comment by beikov** [comment]
Not sure I understand what your particular issue is exactly, since you are not using `LocalDateTime` or anything like that. Maybe create a new issue on GitHub with some more details or maybe even a reproducer for the problem you have.

**Comment by MichaelF25** [comment]
I am using many `AttributeConverter<SomeIdValueType, UUID>`. Since `UUID` itself is not a basic type (similar to `LocalDateTime`), I am running into this issue. We also have `AttributeConverter<SomeOtherIdValueType, Integer>` which are working fine.

**Comment by beikov** [comment]
I see. Well in that case, you could try to map to `AttributeConverter<SomeIdValueType, byte[]>` or `AttributeConverter<SomeIdValueType, String>` instead, depending on your DB representation.

**Comment by MichaelF25** [comment]
Thx for the hint. Now this one seems to work, but now I am facing a NPE if `AbstractHibernateEntityManagerFactoryIntegrator` tries to access the `TYPE` part of the version string (which is `5.4.33`). Should I create a new ticket for that one?

**Comment by beikov** [comment]
The problem is that Spring uses a "wrong" Hibernate version. Switch to the one ending with .Final pleas
