### ISSUE TITLE
Execution of CTE set query in non-jta tx fails in Wildfly

### ISSUE THREAD

**Issue by Mobe91** [Blazebit/blaze-persistence#563]
### Description

Execution of CTE set query in non-jta tx fails in Wildfly with

```
12:45:03,404 SEVERE [com.ordami.geo.service.impl.service.MatrixUpdateServiceImpl] (EE-ManagedExecutorService-default-Thread-1) null: java.lang.ClassCastException: org.jboss.as.jpa.container.QueryNonTxInvocationDetacher cannot be cast to javax.persistence.TypedQuery
	at com.blazebit.persistence.impl.BaseFinalSetOperationBuilderImpl.getTypedQuery(BaseFinalSetOperationBuilderImpl.java:233)
	at com.blazebit.persistence.impl.BaseFinalSetOperationBuilderImpl.getQuery(BaseFinalSetOperationBuilderImpl.java:322)
	at com.blazebit.persistence.impl.BaseFinalSetOperationBuilderImpl.getQuery(BaseFinalSetOperationBuilderImpl.java:45)
	at com.blazebit.persistence.impl.AbstractCommonQueryBuilder.getQuery(AbstractCommonQueryBuilder.java:1717)
	at com.blazebit.persistence.impl.AbstractCommonQueryBuilder.getCteNodes(AbstractCommonQueryBuilder.java:1613)
	at com.blazebit.persistence.impl.AbstractCommonQueryBuilder.getTypedQuery(AbstractCommonQueryBuilder.java:1553)
	at com.blazebit.persistence.impl.AbstractQueryBuilder.getQuery(AbstractQueryBuilder.java:52)
	at com.blazebit.persistence.impl.AbstractQueryBuilder.getResultList(AbstractQueryBuilder.java:57)
	at com.ordami.geo.service.impl.service.MatrixUpdateServiceImpl.initializeMatrix(MatrixUpdateServiceImpl.java:127)
	at com.ordami.geo.service.impl.service.MatrixUpdateServiceImpl$Proxy$_$$_WeldSubclass.initializeMatrix$$super(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:49)
	at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:77)
	at com.arjuna.ats.jta.cdi.transactional.TransactionalInterceptorBase.invokeInNoTx(TransactionalInterceptorBase.java:141)
```
This likely to be broken also for other application servers but I encountered it in Wildfly.
The purpose of `org.jboss.as.jpa.container.QueryNonTxInvocationDetacher` created by Wildfly is to detach the returned entities.

### Expected behavior

That it works

### Actual behavior

Exception during query execution

### Environment

Version:            1.2.0
JPA-Provider:       Hibernate
DBMS:               -
Application Server: Wildfly 10

**Comment by beikov** [comment]
Interesting that you only seem to have the problem when having no active transaction. IMO this could also happen when having a transaction. The problem is that some queries are created via `javax.persistence.EntityManager#createQuery(java.lang.String)` which is rightfully allowed to return an instance of type `javax.persistence.Query` rather than `javax.persistence.TypedQuery`.

IMO the proper fix is to avoid requiring `TypedQuery` within `com.blazebit.persistence.impl.BaseFinalSetOperationBuilderImpl#getTypedQuery` i.e. remove the casts and use `Query` in `com.blazebit.persistence.impl.query.CustomSQLTypedQuery` instead.

**Comment by beikov** [comment]
Please try out the pull request and tell me if that fixes it for you.
https://github.com/Blazebit/blaze-persistence/pull/592

**Comment by beikov** [comment]
@Mobe91 I just went ahead and merged the PR as I'm pretty confident this will fix the issue. If this didn't fix it, please report that as new issue.
