### ISSUE TITLE
Support specifying fetches for collections within embeddables

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#598]
### Description

Defining fetches for a collection that is contained in an embeddable currently does not work.
Consider the following mapping:

```
@UpdatableEntityView
@EntityView(Group.class)
interface GroupDetailView extends View<Group> {
    @IdMapping
    Long getId();
    @Mapping(fetches = "localizedValues")
    LocalizedString getTitle();
    @Mapping(fetches = "localizedValues")
    LocalizedString getDescription();
}
```

### Expected behavior

That it works

### Actual behavior

```
java.lang.IllegalStateException: Some join nodes specified fetch joining but their fetch owners weren't included in the select clause! Missing fetch owners: [generatedGroup_0, generatedGroup_0]
    at com.blazebit.persistence.impl.AbstractCommonQueryBuilder.applyImplicitJoins(AbstractCommonQueryBuilder.java:1514)
    at com.blazebit.persistence.impl.AbstractCommonQueryBuilder.prepareAndCheck(AbstractCommonQueryBuilder.java:1895)
    at com.blazebit.persistence.impl.AbstractCommonQueryBuilder.getBaseQueryStringWithCheck(AbstractCommonQueryBuilder.java:1578)
    at com.blazebit.persistence.impl.AbstractCommonQueryBuilder.getTypedQuery(AbstractCommonQueryBuilder.java:1593)
    at com.blazebit.persistence.impl.AbstractQueryBuilder.getQuery(AbstractQueryBuilder.java:52)
    at com.blazebit.persistence.impl.AbstractQueryBuilder.getSingleResult(AbstractQueryBuilder.java:62)
```

### Environment

Version:            1.2.1
JPA-Provider:       Hibernate
DBMS:               
Application Server:

**Comment by beikov** [comment]
Note that this can't be implemented because Hibernate does not support it. See the test case that will follow for details.
