### ISSUE TITLE
NullPointerException when using correlation mapping with updatable entity view

### ISSUE THREAD

**Issue by haderlena** [Blazebit/blaze-persistence#614]
### Description

I tried to use a correlation mapping with an `UpdatableEntityView` in an `UpdatableEntityView`. Even with `@UpdatableMapping(updatable = false)` I get a NPE (see stack trace).

### Expected behavior

see Description

### Actual behavior

see Description

### Steps to reproduce

see Description

### Environment

Version: 1.3.0-Alpha2           
JPA-Provider:       
DBMS:               
Application Server: 

```
Jul 30, 2018 12:56:40 PM com.blazebit.persistence.impl.CriteriaBuilderConfigurationProviderImpl createConfiguration
INFORMATION: Blaze-Persistence version: Blaze-Persistence 'Fury' 1.3.0-Alpha2

org.jboss.weld.exceptions.WeldException: WELD-000049: Unable to invoke public void com.curecomp.testsuite.integration.persistence.EntityViewManagerProducer.init() on com.curecomp.testsuite.integration.persistence.EntityViewManagerProducer@31054abd

	at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.invokeMethods(DefaultLifecycleCallbackInvoker.java:100)
	at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.postConstruct(DefaultLifecycleCallbackInvoker.java:81)
	at org.jboss.weld.injection.producer.BasicInjectionTarget.postConstruct(BasicInjectionTarget.java:126)
	at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:162)
	at org.jboss.weld.context.unbound.DependentContextImpl.get(DependentContextImpl.java:70)
	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:101)
	at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
	at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:742)
	at org.jboss.weld.injection.producer.AbstractMemberProducer.getReceiver(AbstractMemberProducer.java:123)
	at org.jboss.weld.injection.producer.AbstractMemberProducer.produce(AbstractMemberProducer.java:158)
	at org.jboss.weld.bean.AbstractProducerBean.create(AbstractProducerBean.java:181)
	at org.jboss.weld.context.AbstractContext.get(AbstractContext.java:96)
	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:101)
	at org.jboss.weld.bean.ContextualInstanceStrategy$ApplicationScopedContextualInstanceStrategy.get(ContextualInstanceStrategy.java:141)
	at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
	at org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:99)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:99)
	at com.blazebit.persistence.view.EntityViewManager$769573355$Proxy$_$$_WeldClientProxy.getReference(Unknown Source)
	at com.curecomp.support.testsuite.service.clientServiceTest.CreateClientTest.before(CreateClientTest.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at com.curecomp.testsuite.integration.ContainerRunner$3$1.evaluate(ContainerRunner.java:296)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at com.curecomp.testsuite.integration.ContainerRunner$2.evaluate(ContainerRunner.java:229)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.invokeMethods(DefaultLifecycleCallbackInvoker.java:98)
	... 44 more
Caused by: java.lang.IllegalArgumentException: An error happened during entity view metamodel building!
	at com.blazebit.persistence.view.impl.EntityViewManagerImpl.<init>(EntityViewManagerImpl.java:175)
	at com.blazebit.persistence.view.impl.EntityViewConfigurationImpl.createEntityViewManager(EntityViewConfigurationImpl.java:117)
	at com.blazebit.persistence.view.impl.EntityViewConfigurationImpl.createEntityViewManager(EntityViewConfigurationImpl.java:122)
	at com.curecomp.testsuite.integration.persistence.EntityViewManagerProducer.init(EntityViewManagerProducer.java:39)
	... 49 more
Caused by: java.lang.NullPointerException
	at com.blazebit.persistence.view.impl.metamodel.MethodAttributeMapping.determineMappedBy(MethodAttributeMapping.java:293)
	at com.blazebit.persistence.view.impl.metamodel.AbstractMethodSingularAttribute.<init>(AbstractMethodSingularAttribute.java:147)
	at com.blazebit.persistence.view.impl.metamodel.attribute.CorrelatedMethodSingularAttribute.<init>(CorrelatedMethodSingularAttribute.java:33)
	at com.blazebit.persistence.view.impl.metamodel.MethodAttributeMapping.getMethodAttribute(MethodAttributeMapping.java:510)
	at com.blazebit.persistence.view.impl.metamodel.ManagedViewTypeImpl.<init>(ManagedViewTypeImpl.java:157)
	at com.blazebit.persistence.view.impl.metamodel.ViewTypeImpl.<init>(ViewTypeImpl.java:46)
	at com.blazebit.persistence.view.impl.metamodel.ViewMappingImpl.getManagedViewType(ViewMappingImpl.java:557)
	at com.blazebit.persistence.view.impl.metamodel.ViewMetamodelImpl.<init>(ViewMetamodelImpl.java:67)
	at com.blazebit.persistence.view.impl.EntityViewManagerImpl.<init>(EntityViewManagerImpl.java:159)
	... 52 more
```

**Comment by beikov** [comment]
I'm going to support cascading just like we talked about which will hopefully allow you to remove a few lines of code ;)
