### ISSUE TITLE
Use entity view as Spring Data repository method argument

### ISSUE THREAD

**Issue by heruan** [Blazebit/blaze-persistence#742]
A Spring Data repository can have this method signature:

```java
interface ArticleRepository {

    List<ArticleView> findByAuthor(Person entity);

}
```

where `Author` is the `@Entity`. It would be useful to be able to have also this signature:

```java
interface ArticleRepository {

    List<ArticleView> findByAuthor(PersonView view);

}
```

where `PersonView` is `@EntityView(Person.class)`.

In 1.3.2 a method like this will throw runtime with this exception:

```
java.lang.IllegalArgumentException: Parameter value [PersonView_$$_javassist_entityview_@fa] did not match expected type [Person (n/a)]
    at org.hibernate.query.spi.QueryParameterBindingValidator.validate(QueryParameterBindingValidator.java:54)
    at org.hibernate.query.spi.QueryParameterBindingValidator.validate(QueryParameterBindingValidator.java:27)
    at org.hibernate.query.internal.QueryParameterBindingImpl.validate(QueryParameterBindingImpl.java:90)
    at org.hibernate.query.internal.QueryParameterBindingImpl.setBindValue(QueryParameterBindingImpl.java:55)
    at org.hibernate.query.internal.AbstractProducedQuery.setParameter(AbstractProducedQuery.java:493)
    at org.hibernate.query.internal.AbstractProducedQuery.setParameter(AbstractProducedQuery.java:106)
    at com.blazebit.persistence.impl.query.TypedQueryWrapper.setParameter(TypedQueryWrapper.java:96)
    at com.blazebit.persistence.impl.query.TypedQueryWrapper.setParameter(TypedQueryWrapper.java:35)
    at com.blazebit.persistence.spring.data.base.query.AbstractCriteriaQueryParameterBinder.bind(AbstractCriteriaQueryParameterBinder.java:90)
    at com.blazebit.persistence.spring.data.base.query.ParameterBinder.bind(ParameterBinder.java:104)
    at com.blazebit.persistence.spring.data.base.query.ParameterBinder.bindAndPrepare(ParameterBinder.java:164)
    at com.blazebit.persistence.spring.data.base.query.ParameterBinder.bindAndPrepare(ParameterBinder.java:155)
    at com.blazebit.persistence.spring.data.base.query.AbstractPartTreeBlazePersistenceQuery$QueryPreparer.invokeBinding(AbstractPartTreeBlazePersistenceQuery.java:447)
    at com.blazebit.persistence.spring.data.base.query.AbstractPartTreeBlazePersistenceQuery$QueryPreparer.createQuery(AbstractPartTreeBlazePersistenceQuery.java:401)
    at com.blazebit.persistence.spring.data.base.query.AbstractPartTreeBlazePersistenceQuery.doCreateQuery(AbstractPartTreeBlazePersistenceQuery.java:117)
    at org.springframework.data.jpa.repository.query.AbstractJpaQuery.createQuery(AbstractJpaQuery.java:210)
    at org.springframework.data.jpa.repository.query.JpaQueryExecution$CollectionExecution.doExecute(JpaQueryExecution.java:129)
    at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:91)
    at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:136)
    at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:125)
    at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:605)
    at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.lambda$invoke$3(RepositoryFactorySupport.java:595)
    at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:595)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
    at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:59)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
    at com.blazebit.persistence.spring.data.repository.EntityViewReplacingMethodInterceptor.invoke(EntityViewReplacingMethodInterceptor.java:51)
    ...
```

**Comment by beikov** [comment]
This was added in 1.4.0-Alpha2
