### ISSUE TITLE
Add support for natural id based join tables

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#846]
### Description

ToMany relations currently don't work when using natural ids rather than primary keys. Add support for them.

### Environment

Version:            
JPA-Provider:       
DBMS:               
Application Server:

**Comment by EugenMayer** [comment]
As talked to @JWGmeligMeyling on Slack, there is a new issue when using the latest build

```
 Caused by:
        javassist.CannotCompileException: [source error] ; is missing
            at javassist.CtBehavior.setBody(CtBehavior.java:474)
            at javassist.CtBehavior.setBody(CtBehavior.java:440)
            at com.blazebit.persistence.view.impl.proxy.ProxyFactory.createEquals(ProxyFactory.java:1945)
            at com.blazebit.persistence.view.impl.proxy.ProxyFactory.createIdEquals(ProxyFactory.java:1864)
com.blazebit.persistence.view.impl.proxy.ProxyFactory.createEqualsHashCodeMethods(ProxyFactory.java:808)
            at com.blazebit.persistence.view.impl.proxy.ProxyFactory.createProxyClass(ProxyFactory.java:457)
            ... 59 more
​
            Caused by:
            compile error: ; is missing
                at javassist.compiler.Parser.parseReturn(Parser.java:527)
                at javassist.compiler.Parser.parseStatement(Parser.java:287)
                at javassist.compiler.Parser.parseBlock(Parser.java:307)
                at javassist.compiler.Parser.parseStatement(Parser.java:261)
                at javassist.compiler.Javac.compileBody(Javac.java:219)
                at javassist.CtBehavior.setBody(CtBehavior.java:466)
                ... 64 more
```

For us it happens if an BlazeSpecifictation is used:

```
    Set<GroupInfoView> groupsView = groupRepository.findAll((rootAlias, builder) -> {
      builder.where("name").isNotNull();
    });
```
