### ISSUE TITLE
Integration with spring-data-rest doesn't work with WebFlux

### ISSUE THREAD

**Issue by aboodz** [Blazebit/blaze-persistence#937]
### Description
I have a project spring WebFlux where I use blaze-persistence. Everything work fine unless when importing `blaze-persistence-integration-spring-data-rest`, the application won't be able to start. Sadly without `blaze-persistence-integration-spring-data-rest` Jackson won't be able to deserialize EntityViews. As far as I know, `blaze-persistence-integration-spring-data-rest` has a dependency on `spring-webmvc` which doesn't run when using Netty. 
 
### Expected behavior
Spring application to start normally.

### Actual behavior
```Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.  
 2019-11-14T10:14:11 [] ERROR [main] o.s.boot.SpringApplication - Application run failed org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [me.beam.pg.portal.PortalServiceApplication]; nested exception is java.io.FileNotFoundException: class path resource [org/springframework/web/servlet/config/annotation/WebMvcConfigurerAdapter.class] cannot be opened because it does not exist
	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:599)
	at org.springframework.context.annotation.ConfigurationClassParser.access$900(ConfigurationClassParser.java:108)
	at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGroupingHandler.lambda$processGroupImports$1(ConfigurationClassParser.java:808)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGroupingHandler.processGroupImports(ConfigurationClassParser.java:804)
	at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorHandler.process(ConfigurationClassParser.java:774)
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:185)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:315)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:232)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:275)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:95)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:705)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531)
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:67)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at com.examplel.Application.main(Application.java:12)
Caused by: java.io.FileNotFoundException: class path resource [org/springframework/web/servlet/config/annotation/WebMvcConfigurerAdapter.class] cannot be opened because it does not exist
	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:180)
	at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:51)
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:103)
	at org.springframework.boot.type.classreading.ConcurrentReferenceCachingMetadataReaderFactory.createMetadataReader(ConcurrentReferenceCachingMetadataReaderFactory.java:88)
	at org.springframework.boot.type.classreading.ConcurrentReferenceCachingMetadataReaderFactory.getMetadataReader(ConcurrentReferenceCachingMetadataReaderFactory.java:75)
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:81)
	at org.springframework.context.annotation.ConfigurationClassParser.asSourceClass(ConfigurationClassParser.java:685)
	at org.springframework.context.annotation.ConfigurationClassParser$SourceClass.getSuperClass(ConfigurationClassParser.java:998)
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:332)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:242)
	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:589)
	... 19 common frames omitted
```
### Steps to reproduce
use  `blaze-persistence-integration-spring-data-rest` in Spring WebFlux project

### Environment
Version: 1.4.0-Alpha3
Spring-Boot: 2.1.3.RELEASE
Application Server: Netty 4.1.33

**Comment by beikov** [comment]
Thanks for trying this out and reporting the issue. It was mentioned before that the naming of the integration is confusing, as the spring-data-rest module was supposed to integrate spring-data with spring-webmvc only. I renamed it and introduced a new module spring-data-webflux that integrates that part. It's not fully reactive(I think), some parts might still block at some point I guess, but I don't use that so I would welcome feedback regarding the integration.
Could you give the PR a try? https://github.com/Blazebit/blaze-persistence/pull/938

**Comment by aboodz** [comment]
Thanks for this amazing fast response. I've just tried using the newly created `spring-data-webflux` from PR #938. My WebFlux application runs successfully but it seems that deserialization is broken for non entity view types when using `bodyToMono`.

**Comment by beikov** [comment]
I just added a sample to the PR but couldn't see deserialization failing. Would you mind giving me some details what it is exactly that is failing for you?

**Comment by aboodz** [comment]
Looks like I use the dto in a slightly different way.  I don't have use setters in my dto (I don't like mutable fields). But it works with the default object mapper.
```
@Data
@NoArgsConstructor(force = true, access = AccessLevel.PROTECTED) // For Jackson to be happy
@RequiredArgsConstructor
public class LoginRequest {
    private final String username;
    private final String password;
}
```

**Comment by beikov** [comment]
I think I fixed that now, just pushed again.

**Comment by aboodz** [comment]
It works well now. Thanks a lot.
