### ISSUE TITLE
EqualFilter doesn't support passing String as argument for Enum Type attribute

### ISSUE THREAD

**Issue by aboodz** [Blazebit/blaze-persistence#952]
### Description
Attribute filter `EqualFilter` doesn't work when using on enum type attributes
### Expected behavior
Apply the filter normally
### Actual behavior
It throws an exception
```java.lang.RuntimeException: Could not create an instance of the filter class 'com.blazebit.persistence.view.impl.filter.EqualFilterImpl'
	at com.blazebit.persistence.view.impl.EntityViewManagerImpl.createFilterInstance(EntityViewManagerImpl.java:573)
	at com.blazebit.persistence.view.impl.EntityViewManagerImpl.createAttributeFilter(EntityViewManagerImpl.java:539)
	at com.blazebit.persistence.view.impl.EntityViewSettingHelper.applyAttributeFilters(EntityViewSettingHelper.java:222)
	at com.blazebit.persistence.view.impl.EntityViewSettingHelper.applyAttributeFilters(EntityViewSettingHelper.java:158)
	at com.blazebit.persistence.view.impl.EntityViewSettingHelper.apply(EntityViewSettingHelper.java:70)
	at com.blazebit.persistence.view.impl.EntityViewManagerImpl.applySetting(EntityViewManagerImpl.java:489)
	at com.blazebit.persistence.spring.data.base.query.AbstractPartTreeBlazePersistenceQuery$QueryPreparer.createPaginatedQuery(AbstractPartTreeBlazePersistenceQuery.java:271)
	at com.blazebit.persistence.spring.data.base.query.AbstractPartTreeBlazePersistenceQuery.createPaginatedQuery(AbstractPartTreeBlazePersistenceQuery.java:155)
	at com.blazebit.persistence.spring.data.impl.query.PartTreeBlazePersistenceQuery$PagedExecution.doExecute(PartTreeBlazePersistenceQuery.java:128)
	at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:91)
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:136)
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:125)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:605)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.lambda$invoke$3(RepositoryFactorySupport.java:595)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:595)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:59)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at com.blazebit.persistence.spring.data.repository.EntityViewReplacingMethodInterceptor.invoke(EntityViewReplacingMethodInterceptor.java:51)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at com.blazebit.persistence.spring.data.base.repository.EntityViewAwareCrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(EntityViewAwareCrudMethodMetadataPostProcessor.java:142)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy139.findAll(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy139.findAll(Unknown Source)
	at my.package.service.AbstractCrudService.lambda$list$10(AbstractCrudService.java:81)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at my.package.auth.service.util.TransactionalUtil.lambda$inTransactionalMono$0(TransactionalUtil.java:22)
	at reactor.core.publisher.MonoCallable.call(MonoCallable.java:91)
	at reactor.core.publisher.FluxSubscribeOnCallable$CallableSubscribeOnSubscription.run(FluxSubscribeOnCallable.java:225)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:50)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:27)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.blazebit.persistence.view.impl.EntityViewManagerImpl.createFilterInstance(EntityViewManagerImpl.java:550)
	... 54 common frames omitted
Caused by: java.lang.IllegalArgumentException: Unknown return type
	at com.blazebit.text.FormatUtils.getParsedValue(FormatUtils.java:148)
	at com.blazebit.text.FormatUtils.getParsedValue(FormatUtils.java:123)
	at com.blazebit.persistence.view.impl.filter.FilterUtils.parseValue(FilterUtils.java:37)
	at com.blazebit.persistence.view.impl.filter.ComparisonFilterHelper.<init>(ComparisonFilterHelper.java:50)
	at com.blazebit.persistence.view.impl.filter.EqualFilterImpl.<init>(EqualFilterImpl.java:33)
	... 59 common frames omitted
```

### Steps to reproduce
Use EqualFilter on enum attribute.

### Workaround
Create your own filter.
```
 class StatusAttributeFilterProvider extends AttributeFilterProvider {
        private EntityStatus value;
        public StatusAttributeFilterProvider(Object value) {
            this.value = EntityStatus.valueOf((String) value);
        }

        @Override
        protected <T> T apply(RestrictionBuilder<T> restrictionBuilder) {
            return restrictionBuilder.eq(value);
        }
    }
```

### Environment
Version:    1.4.0-Alpha3

**Comment by beikov** [comment]
Thanks for reporting this. Actually, it does support the enum type, it just doesn't support parsing the a string value with `valueOf` as you noticed. Using the enum value on the filter though will work just fine.

```
entityViewSetting.addAttributeFilter("someEnumAttribute", SomeEnum.MY_VALUE);
```
